window.SHARAWLA_WEB_V1=Object.freeze({
  supabaseUrl:'https://YOUR_PROJECT.supabase.co',
  publishableKey:'sb_publishable_...',
  businessId:'YOUR-BUSINESS-ID-OR-CODE',
  defaultProfile:'retail',
  allowProfileQuery:false,
  retailPortal:'../retail-website/index.html',
  currency:'EGP'
});
