(function(global){
'use strict';
const VERSION='dfr04-activity-log-v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const rpc=(n,p)=>global.rpc(n,p),branch=()=>Number(global.currentBranchId?.()||0),toast=m=>{try{return global.toast?.(m)}catch{};console.warn(m)};
const today=()=>new Date().toISOString().slice(0,10),monthStart=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`};
const startIso=v=>new Date(`${v}T00:00:00`).toISOString(),endIso=v=>{const d=new Date(`${v}T00:00:00`);d.setDate(d.getDate()+1);return d.toISOString()};
function onReports(){return /التقارير/.test(String(document.querySelector('#pageTitle')?.textContent||''))||!!document.querySelector('[data-reports-v2-open]')}
function inject(){if(!onReports()||document.querySelector('[data-dfr04-activity]'))return;const host=document.querySelector('#page .section-head')||document.querySelector('#page .panel')||document.querySelector('#page');if(!host)return;const b=document.createElement('button');b.className='secondary';b.dataset.dfr04Activity='1';b.textContent='🕘 سجل النشاط';host.appendChild(b)}
function summary(x){if(!x||typeof x!=='object')return '—';return Object.entries(x).map(([k,v])=>`${k}: ${v}`).join(' • ')||'—'}
async function open(){if(navigator.onLine===false)return toast('سجل النشاط يحتاج اتصالًا بالإنترنت');const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-card" style="width:min(1050px,96vw);max-height:94vh;overflow:auto"><div class="section-head"><div><h2>🕘 سجل النشاط</h2><p class="muted">سجل قراءة آمن؛ التفاصيل الخام غير معروضة، والتغطية تقتصر على الأحداث المسجلة فعليًا.</p></div><button class="secondary" data-close>إغلاق</button></div><div class="form-grid"><label>من<input data-from type="date" value="${monthStart()}"></label><label>إلى<input data-to type="date" value="${today()}"></label><label>&nbsp;<button class="primary" data-run>عرض</button></label></div><div data-out></div></div>`;document.body.appendChild(m);const run=async()=>{const out=m.querySelector('[data-out]'),f=m.querySelector('[data-from]').value,t=m.querySelector('[data-to]').value;out.innerHTML='<div class="empty">جاري التحميل…</div>';try{const rows=await rpc('activity_log_read_v1',{p_branch_id:branch(),p_from:startIso(f),p_to:endIso(t),p_limit:500});out.innerHTML=`<div class="table-wrap"><table><thead><tr><th>الوقت</th><th>الموظف</th><th>العملية</th><th>الكيان</th><th>ملخص آمن</th></tr></thead><tbody>${(rows||[]).map(x=>`<tr><td>${esc(new Date(x.created_at).toLocaleString('ar-EG'))}</td><td>${esc(x.employee_name||'—')}</td><td>${esc(x.action)}</td><td>${esc(`${x.entity_type||'—'} #${x.entity_id??'—'}`)}</td><td>${esc(summary(x.safe_summary))}</td></tr>`).join('')||'<tr><td colspan="5">لا توجد أحداث مسجلة في الفترة</td></tr>'}</tbody></table></div>`}catch(e){out.innerHTML=`<div class="empty">${esc(e.message||e)}</div>`}};m.onclick=e=>{if(e.target===m||e.target.closest('[data-close]'))m.remove();else if(e.target.closest('[data-run]'))run()};run()}
function start(){document.addEventListener('click',e=>{if(e.target.closest('[data-dfr04-activity]'))open()});const o=new MutationObserver(inject);o.observe(document.body,{childList:true,subtree:true});inject();global.__SharawlaDFR04ActivityLog=Object.freeze({version:VERSION,open})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})(window);