const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const cfg={url:localStorage.getItem('sbUrl')||'',key:localStorage.getItem('sbKey')||''};
let session=JSON.parse(localStorage.getItem('sbSession')||'null');
let state={employee:null,branches:[],categories:[],products:[],cart:[],cat:'all'};
const money=n=>`${Number(n||0).toFixed(2)} ج.م`;
const fmtDate=s=>new Date(s).toLocaleString('ar-EG');
function toast(m){const e=$('#toast');e.textContent=m;e.style.display='block';setTimeout(()=>e.style.display='none',2600)}
function show(id){['setupView','loginView','appView'].forEach(x=>$('#'+x).classList.add('hidden'));$('#'+id).classList.remove('hidden')}
function headers(auth=true){return {'Content-Type':'application/json','apikey':cfg.key,...(auth&&session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{})}}
async function req(path,opt={}){const r=await fetch(cfg.url+path,{...opt,headers:{...headers(opt.auth!==false),...(opt.headers||{})}});let d=null;try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.message||d?.error_description||d?.hint||`خطأ ${r.status}`);return d}
async function rest(table,query='',opt={}){return req(`/rest/v1/${table}${query?`?${query}`:''}`,opt)}
async function signIn(email,password){const d=await req('/auth/v1/token?grant_type=password',{method:'POST',auth:false,body:JSON.stringify({email,password})});session=d;localStorage.setItem('sbSession',JSON.stringify(d));return d}
async function logout(){try{await req('/auth/v1/logout',{method:'POST'})}catch{}session=null;localStorage.removeItem('sbSession');show('loginView')}
function branchName(id){return state.branches.find(b=>String(b.id)===String(id))?.name||''}

async function bootstrap(){
  const [emps,branches,cats,products]=await Promise.all([
    rest('employees','select=*&auth_user_id=eq.'+session.user.id),
    rest('branches','select=*&active=eq.true&order=id'),
    rest('categories','select=*&active=eq.true&order=sort_order'),
    rest('products','select=*&active=eq.true&order=id')
  ]);
  if(!emps?.length)throw new Error('الحساب غير مربوط بموظف في النظام');
  state.employee=emps[0];state.branches=branches||[];state.categories=cats||[];state.products=products||[];
  $('#who').textContent=`${state.employee.name} • ${state.employee.role}`;
  $('#branchName').textContent=branchName(state.employee.branch_id);
  $$('#nav [data-page="users"],#nav [data-page="settings"]').forEach(b=>b.classList.toggle('hidden',state.employee.role!=='admin'));
  show('appView');showPage('pos');
}

$('#setupForm').addEventListener('submit',async e=>{e.preventDefault();const url=$('#supabaseUrl').value.trim().replace(/\/$/,'');const key=$('#publishableKey').value.trim();if(!/^https:\/\/.+\.supabase\.co$/.test(url))return toast('راجع Project URL');if(!key.startsWith('sb_'))return toast('راجع Publishable key');localStorage.setItem('sbUrl',url);localStorage.setItem('sbKey',key);location.reload()});
$('#changeConnection').onclick=()=>{localStorage.removeItem('sbUrl');localStorage.removeItem('sbKey');localStorage.removeItem('sbSession');location.reload()};
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();try{await signIn($('#email').value.trim(),$('#password').value);await bootstrap()}catch(err){toast(err.message)}});
$('#logoutBtn').onclick=logout;$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');
$('#nav').onclick=e=>{const b=e.target.closest('button[data-page]');if(b)showPage(b.dataset.page)};
setInterval(()=>{if($('#clock'))$('#clock').textContent=new Date().toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit'})},1000);
const titles={pos:'الكاشير',orders:'الطلبات',shifts:'الشيفت',inventory:'المخزون',expenses:'المصروفات',products:'الأصناف',reports:'التقارير',users:'المستخدمون',settings:'الإعدادات'};
function navActive(p){$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));$('.sidebar').classList.remove('open')}
async function showPage(p){try{navActive(p);$('#pageTitle').textContent=titles[p]||p;await ({pos:renderPOS,orders:renderOrders,shifts:renderShifts,inventory:renderInventory,expenses:renderExpenses,products:renderProducts,reports:renderReports,users:renderUsers,settings:renderSettings}[p]||renderPOS)()}catch(e){toast(e.message)}}

function renderPOS(){
 $('#page').innerHTML=`<div class="pos-layout"><section class="catalog"><div class="cat-tabs" id="catTabs"><button data-cat="all" class="active">الكل</button>${state.categories.map(c=>`<button data-cat="${c.id}">${c.name}</button>`).join('')}</div><div class="products-grid" id="productsGrid"></div></section><aside class="cart"><div class="cart-head"><select id="orderType"><option value="takeaway">تيك أواي</option><option value="delivery">دليفري</option><option value="dinein">صالة</option></select><input id="customerName" placeholder="اسم العميل"></div><div class="cart-items" id="cartItems"></div><div class="cart-foot"><div class="totline"><span>الإجمالي الفرعي</span><b id="subtotal">0</b></div><div class="totline"><span>خصم</span><input id="discount" type="number" min="0" value="0" style="width:110px;padding:5px"></div><div class="totline grand"><span>المطلوب</span><span id="grand">0</span></div><div class="pay-actions"><button class="primary" data-pay="cash">نقدي</button><button class="secondary" data-pay="card">فيزا</button><button class="secondary" data-pay="wallet">محفظة</button></div></div></aside></div>`;
 $('#catTabs').onclick=e=>{const b=e.target.closest('button');if(!b)return;state.cat=b.dataset.cat;$$('#catTabs button').forEach(x=>x.classList.toggle('active',x===b));drawProducts()};
 $('#discount').oninput=drawCart;$('.pay-actions').onclick=e=>{const b=e.target.closest('[data-pay]');if(b)checkout(b.dataset.pay)};drawProducts();drawCart();
}
function drawProducts(){const list=state.products.filter(p=>state.cat==='all'||String(p.category_id)===String(state.cat));$('#productsGrid').innerHTML=list.map(p=>`<button class="product" data-id="${p.id}"><b>${p.name}</b><span>${money(p.price)}</span></button>`).join('')||'<div class="empty">أضف أصناف من صفحة الأصناف</div>';$('#productsGrid').onclick=e=>{const b=e.target.closest('.product');if(b){const p=state.products.find(x=>String(x.id)===String(b.dataset.id));const ex=state.cart.find(x=>x.product_id===p.id);ex?ex.qty++:state.cart.push({product_id:p.id,name:p.name,price:Number(p.price),cost:Number(p.cost||0),qty:1});drawCart()}}}
function cartCalc(){const subtotal=state.cart.reduce((s,i)=>s+i.price*i.qty,0),discount=Number($('#discount')?.value||0);return{subtotal,discount,total:Math.max(0,subtotal-discount)}}
function drawCart(){if(!$('#cartItems'))return;$('#cartItems').innerHTML=state.cart.length?state.cart.map((i,n)=>`<div class="cart-item"><div class="cart-row"><b>${i.name}</b><b>${money(i.price*i.qty)}</b></div><div class="qty"><button data-a="plus" data-i="${n}">+</button><b>${i.qty}</b><button data-a="minus" data-i="${n}">−</button><button data-a="del" data-i="${n}">🗑</button></div></div>`).join(''):'<div class="empty">أضف أصناف للأوردر</div>';$('#cartItems').onclick=e=>{const b=e.target.closest('button[data-a]');if(!b)return;const i=state.cart[+b.dataset.i];if(b.dataset.a==='plus')i.qty++;if(b.dataset.a==='minus'){i.qty--;if(i.qty<=0)state.cart.splice(+b.dataset.i,1)}if(b.dataset.a==='del')state.cart.splice(+b.dataset.i,1);drawCart()};const c=cartCalc();$('#subtotal').textContent=money(c.subtotal);$('#grand').textContent=money(c.total)}
async function checkout(payment){if(!state.cart.length)return toast('الأوردر فارغ');const c=cartCalc();const order=[{branch_id:state.employee.branch_id,employee_id:state.employee.id,order_type:$('#orderType').value,payment_method:payment,subtotal:c.subtotal,discount:c.discount,total:c.total,status:'completed',notes:$('#customerName').value?`العميل: ${$('#customerName').value}`:null}];const created=await rest('orders','select=*',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(order)});const o=created[0];const items=state.cart.map(i=>({order_id:o.id,product_id:i.product_id,product_name:i.name,quantity:i.qty,unit_price:i.price,cost:i.cost,total:i.price*i.qty}));await rest('order_items','',{method:'POST',body:JSON.stringify(items)});state.cart=[];toast(`تم حفظ أوردر #${o.id}`);renderPOS()}

async function renderOrders(){const rows=await rest('orders','select=*&order=created_at.desc&limit=100');$('#page').innerHTML=`<div class="panel"><h2>آخر الطلبات</h2><div class="table-wrap"><table><thead><tr><th>#</th><th>التاريخ</th><th>الفرع</th><th>النوع</th><th>الدفع</th><th>الإجمالي</th></tr></thead><tbody>${rows.map(o=>`<tr><td>${o.id}</td><td>${fmtDate(o.created_at)}</td><td>${branchName(o.branch_id)}</td><td>${o.order_type}</td><td>${o.payment_method}</td><td>${money(o.total)}</td></tr>`).join('')}</tbody></table></div></div>`}

async function renderShifts(){const rows=await rest('shifts',`select=*&employee_id=eq.${state.employee.id}&order=opened_at.desc&limit=30`),open=rows.find(s=>s.status==='open'&&!s.closed_at);$('#page').innerHTML=`<div class="panel"><h2>${open?'الشيفت الحالي مفتوح':'فتح شيفت جديد'}</h2>${open?`<p>بدأ: ${fmtDate(open.opened_at)} — افتتاحية: ${money(open.opening_cash)}</p><div class="toolbar"><label>النقدية الفعلية<input id="closingCash" type="number" value="0"></label><button id="closeShift" class="danger">إغلاق الشيفت</button></div>`:`<div class="toolbar"><label>عهدة بداية الشيفت<input id="openingCash" type="number" value="0"></label><button id="openShift" class="primary">فتح الشيفت</button></div>`}</div>`;if(open)$('#closeShift').onclick=async()=>{await rest('shifts',`id=eq.${open.id}`,{method:'PATCH',body:JSON.stringify({closing_cash:Number($('#closingCash').value||0),closed_at:new Date().toISOString(),status:'closed'})});toast('تم إغلاق الشيفت');renderShifts()};else $('#openShift').onclick=async()=>{await rest('shifts','',{method:'POST',body:JSON.stringify([{branch_id:state.employee.branch_id,employee_id:state.employee.id,opening_cash:Number($('#openingCash').value||0),status:'open'}])});toast('تم فتح الشيفت');renderShifts()}}

async function renderExpenses(){const rows=await rest('expenses','select=*&order=created_at.desc&limit=100');$('#page').innerHTML=`<div class="panel"><h2>إضافة مصروف</h2><div class="form-grid"><label>البيان<input id="exTitle"></label><label>المبلغ<input id="exAmount" type="number"></label></div><button id="addExpense" class="primary">حفظ المصروف</button></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>التاريخ</th><th>البيان</th><th>المبلغ</th><th>الفرع</th></tr></thead><tbody>${rows.map(e=>`<tr><td>${fmtDate(e.created_at)}</td><td>${e.description}</td><td>${money(e.amount)}</td><td>${branchName(e.branch_id)}</td></tr>`).join('')}</tbody></table></div></div>`;$('#addExpense').onclick=async()=>{if(!$('#exTitle').value||!$('#exAmount').value)return toast('أدخل البيان والمبلغ');await rest('expenses','',{method:'POST',body:JSON.stringify([{branch_id:state.employee.branch_id,employee_id:state.employee.id,description:$('#exTitle').value,amount:Number($('#exAmount').value)}])});toast('تم حفظ المصروف');renderExpenses()}}

async function renderProducts(){state.products=await rest('products','select=*&order=id');$('#page').innerHTML=`<div class="panel"><h2>إضافة صنف</h2><div class="form-grid"><label>الاسم<input id="pName"></label><label>القسم<select id="pCat">${state.categories.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select></label><label>سعر البيع<input id="pPrice" type="number"></label><label>التكلفة<input id="pCost" type="number"></label><label>باركود<input id="pBarcode"></label></div><button id="addProduct" class="primary">إضافة الصنف</button></div><div class="panel"><h2>الأصناف</h2><div class="table-wrap"><table><thead><tr><th>الصنف</th><th>السعر</th><th>التكلفة</th><th>الحالة</th></tr></thead><tbody>${state.products.map(p=>`<tr><td>${p.name}</td><td>${money(p.price)}</td><td>${money(p.cost)}</td><td>${p.active?'فعال':'موقوف'}</td></tr>`).join('')}</tbody></table></div></div>`;$('#addProduct').onclick=async()=>{if(!$('#pName').value)return toast('اكتب اسم الصنف');await rest('products','',{method:'POST',body:JSON.stringify([{name:$('#pName').value,category_id:Number($('#pCat').value),price:Number($('#pPrice').value||0),cost:Number($('#pCost').value||0),barcode:$('#pBarcode').value||null,active:true}])});toast('تمت إضافة الصنف');state.products=await rest('products','select=*&active=eq.true&order=id');renderProducts()}}

async function renderInventory(){const rows=await rest('ingredient_stock','select=id,branch_id,quantity,ingredients(name,unit)&order=id');$('#page').innerHTML=`<div class="panel"><h2>مخزون الخامات</h2><div class="table-wrap"><table><thead><tr><th>الخامة</th><th>الوحدة</th><th>الفرع</th><th>الرصيد</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.ingredients?.name||''}</td><td>${r.ingredients?.unit||''}</td><td>${branchName(r.branch_id)}</td><td>${r.quantity}</td></tr>`).join('')}</tbody></table></div></div>`}

async function renderReports(){const [orders,expenses]=await Promise.all([rest('orders','select=total,payment_method,created_at'),rest('expenses','select=amount,created_at')]);const today=new Date().toISOString().slice(0,10),todOrd=orders.filter(x=>x.created_at.slice(0,10)===today),todExp=expenses.filter(x=>x.created_at.slice(0,10)===today),sales=todOrd.reduce((s,x)=>s+Number(x.total||0),0),ex=todExp.reduce((s,x)=>s+Number(x.amount||0),0);$('#page').innerHTML=`<div class="grid kpis"><div class="card kpi"><small>مبيعات اليوم</small><strong>${money(sales)}</strong></div><div class="card kpi"><small>طلبات اليوم</small><strong>${todOrd.length}</strong></div><div class="card kpi"><small>مصروفات اليوم</small><strong>${money(ex)}</strong></div><div class="card kpi"><small>صافي قبل تكلفة الخامات</small><strong>${money(sales-ex)}</strong></div></div>`}

async function renderUsers(){const rows=await rest('employees','select=id,name,username,role,branch_id,active&order=id');$('#page').innerHTML=`<div class="panel"><h2>المستخدمون</h2><p>إنشاء حسابات تسجيل الدخول الجديدة يتم حاليًا من Supabase Authentication ثم ربطها بجدول employees.</p><div class="table-wrap"><table><thead><tr><th>الاسم</th><th>المستخدم</th><th>الدور</th><th>الفرع</th><th>الحالة</th></tr></thead><tbody>${rows.map(u=>`<tr><td>${u.name}</td><td>${u.username||''}</td><td>${u.role}</td><td>${branchName(u.branch_id)}</td><td>${u.active?'فعال':'موقوف'}</td></tr>`).join('')}</tbody></table></div></div>`}

function renderSettings(){$('#page').innerHTML=`<div class="panel"><h2>إعداد الاتصال</h2><p>البرنامج متصل حاليًا بـ Supabase.</p><button id="resetConn" class="danger">تغيير بيانات Supabase</button></div><div class="panel"><h2>ملاحظات النسخة الحالية</h2><p>هذه نسخة Cloud MVP بدون Node محلي. الخطوة التالية بعد اعتماد التشغيل: الطباعة المباشرة، شاشة المطبخ، وصفات الخامات التلقائية، الموردون والمشتريات، وصلاحيات كل وظيفة.</p></div>`;$('#resetConn').onclick=()=>{if(confirm('سيتم تسجيل الخروج ومسح بيانات الاتصال من هذا الجهاز فقط.')){$('#changeConnection').click()}}}

async function init(){if(!cfg.url||!cfg.key)return show('setupView');if(!session?.access_token)return show('loginView');try{await bootstrap()}catch(e){localStorage.removeItem('sbSession');session=null;show('loginView');toast(e.message)}}
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
init();
