(function(global){
'use strict';
const VERSION='finance-b2b-ui.1',KEY='sharawlaRuntimeConfigV1';let observer=null;
const F=['finance.credit','finance.receivables','finance.collections','finance.aging','commerce.price_tiers','commerce.b2b_orders'];
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));const money=v=>Number(v||0).toFixed(2);const uuid=()=>global.uuid?.()||crypto.randomUUID();const rpc=(n,p)=>global.rpc(n,p),rest=(t,q)=>global.rest(t,q),toast=m=>{try{return global.toast?.(m)}catch{};console.warn(m)};
function cfg(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch{return {}}}function has(c){return (cfg().enabled_features||[]).map(x=>String(x).toLowerCase()).includes(String(c).toLowerCase())}function any(){return F.some(has)}function branch(){try{return Number(global.currentBranchId?.()||0)}catch{return 0}}function pageOk(){return /العملاء|التقارير/.test(String(document.querySelector('#pageTitle')?.textContent||''))}
async function promptv(m,d='',o={}){try{return await global.uiPrompt?.(m,d,o)??null}catch{return prompt(m,d)}}
function inject(){if(!any()||!pageOk()||document.querySelector('[data-finance-v1]'))return;const page=document.querySelector('#page');if(!page)return;const host=page.querySelector('.section-head')||page.firstElementChild||page;const b=document.createElement('button');b.className='primary';b.dataset.financeV1='1';b.textContent='💳 الائتمان والمديونيات';b.onclick=open;host.appendChild(b)}
async function open(){const m=document.createElement('div');m.className='modal';document.body.appendChild(m);async function render(){let aging=[],tiers=[];try{aging=has('finance.aging')?await rpc('finance_aging_v2',{p_branch_id:branch(),p_as_of:new Date().toISOString().slice(0,10)}):[];tiers=has('commerce.price_tiers')?await rest('commerce_price_tiers','select=*&active=eq.true&order=priority.desc,id'):[]}catch(e){m.remove();return toast(e.message)}m.innerHTML=`<div class="modal-card" style="width:min(1150px,96vw);max-height:94vh;overflow:auto"><div class="section-head"><div><h2>💳 Finance / B2B</h2><p class="muted">ائتمان، تحصيلات، Aging وفئات أسعار.</p></div><button class="secondary" data-f-close>إغلاق</button></div><div class="variant-v1-actions">${has('finance.credit')?'<button class="primary" data-f-credit>ضبط ائتمان عميل</button>':''}${has('finance.receivables')?'<button class="secondary" data-f-recv>إضافة مديونية</button>':''}${has('finance.collections')?'<button class="secondary" data-f-collect>تسجيل تحصيل</button>':''}${has('commerce.price_tiers')?'<button class="secondary" data-f-tier>فئة سعر جديدة</button><button class="secondary" data-f-assign>ربط عميل بفئة</button>':''}</div>${has('finance.aging')?`<div class="panel"><h3>Aging 30/60/90</h3><div class="table-wrap"><table><thead><tr><th>العميل</th><th>حالي</th><th>1-30</th><th>31-60</th><th>61-90</th><th>+90</th><th>الإجمالي</th><th>Limit</th><th>متاح</th><th>Hold</th></tr></thead><tbody>${(aging||[]).map(x=>`<tr><td>${esc(x.customer_name||x.customer_id)}</td><td>${money(x.current_due)}</td><td>${money(x.days_1_30)}</td><td>${money(x.days_31_60)}</td><td>${money(x.days_61_90)}</td><td>${money(x.days_over_90)}</td><td><b>${money(x.total_due)}</b></td><td>${money(x.credit_limit)}</td><td>${x.available_credit===null?'∞':money(x.available_credit)}</td><td>${x.credit_hold?'⛔':'—'}</td></tr>`).join('')||'<tr><td colspan="10">لا توجد مديونيات مفتوحة</td></tr>'}</tbody></table></div></div>`:''}${has('commerce.price_tiers')?`<div class="panel"><h3>فئات الأسعار</h3>${tiers.map(t=>`<span class="tag">${esc(t.name)} (${esc(t.code)})</span>`).join(' ')||'<span class="muted">لا توجد فئات</span>'}</div>`:''}</div>`}
 m.onclick=async e=>{if(e.target===m||e.target.closest('[data-f-close]'))return m.remove();let b=e.target.closest('[data-f-credit]');if(b){const cid=await promptv('رقم العميل','',{title:'ائتمان',type:'number'});if(cid===null)return;const lim=await promptv('حد الائتمان','0',{title:'Credit Limit',type:'number'});if(lim===null)return;const days=await promptv('أيام السداد','30',{title:'Payment Terms',type:'number'});if(days===null)return;const hold=confirm('وضع العميل على Credit Hold؟');try{await rpc('finance_customer_account_set_v2',{p_customer_id:Number(cid),p_credit_limit:Number(lim),p_payment_terms_days:Number(days),p_credit_hold:hold,p_notes:null});toast('تم حفظ الائتمان');await render()}catch(x){toast(x.message)}return}b=e.target.closest('[data-f-recv]');if(b){const cid=await promptv('رقم العميل','',{title:'مديونية',type:'number'});if(cid===null)return;const amt=await promptv('القيمة','0',{title:'مديونية',type:'number'});if(amt===null)return;try{await rpc('finance_receivable_create_v2',{p_branch_id:branch(),p_customer_id:Number(cid),p_amount:Number(amt),p_source_type:'manual',p_source_id:null,p_document_number:null,p_due_date:null,p_notes:null,p_client_tx_id:uuid()});toast('تم إنشاء المديونية');await render()}catch(x){toast(x.message)}return}b=e.target.closest('[data-f-collect]');if(b){const cid=await promptv('رقم العميل','',{title:'تحصيل',type:'number'});if(cid===null)return;const amt=await promptv('القيمة','0',{title:'تحصيل',type:'number'});if(amt===null)return;const method=await promptv('طريقة الدفع','cash',{title:'تحصيل'});if(method===null)return;try{await rpc('finance_collection_create_v2',{p_branch_id:branch(),p_customer_id:Number(cid),p_amount:Number(amt),p_method:method,p_reference:null,p_allocations:[],p_notes:null,p_client_tx_id:uuid()});toast('تم تسجيل التحصيل');await render()}catch(x){toast(x.message)}return}b=e.target.closest('[data-f-tier]');if(b){const code=await promptv('كود الفئة','wholesale_a',{title:'فئة سعر'});if(code===null)return;const name=await promptv('اسم الفئة','جملة A',{title:'فئة سعر'});if(name===null)return;try{await rpc('commerce_price_tier_save_v2',{p_tier_id:null,p_code:code,p_name:name,p_priority:0,p_active:true});toast('تم إنشاء فئة السعر');await render()}catch(x){toast(x.message)}return}b=e.target.closest('[data-f-assign]');if(b){if(!tiers.length)return toast('أنشئ فئة سعر أولًا');const cid=await promptv('رقم العميل','',{title:'ربط فئة',type:'number'});if(cid===null)return;const tid=await promptv(`رقم الفئة:\n${tiers.map(t=>`${t.id} - ${t.name}`).join('\n')}`,String(tiers[0].id),{title:'فئة السعر',type:'number'});if(tid===null)return;try{await rpc('commerce_customer_price_tier_set_v2',{p_customer_id:Number(cid),p_tier_id:Number(tid)});toast('تم ربط العميل بالفئة')}catch(x){toast(x.message)}return}}
}await render()}
function start(){inject();observer=new MutationObserver(inject);observer.observe(document.body,{childList:true,subtree:true});global.__SharawlaFinanceB2B=Object.freeze({version:VERSION,open})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})(window);
