-- Sharawla POS — Permissions V2 Profile / Feature Applicability (PV2-A)
-- SOURCE-ONLY artifact. Do not deploy until PV2-B Trusted Operational Profile is ready.
-- Runtime baseline: 10.5.4-beta.58.29
-- Production SH-0005 / SH-0006 remain untouched.

begin;

create table if not exists public.permission_action_profiles_v2(
  action_code text not null references public.permission_actions_v2(code) on delete cascade,
  profile_code text not null,
  required_feature_code text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key(action_code,profile_code),
  constraint permission_action_profiles_v2_profile_not_blank check(trim(profile_code)<>''),
  constraint permission_action_profiles_v2_feature_not_blank check(required_feature_code is null or trim(required_feature_code)<>'')
);

comment on table public.permission_action_profiles_v2 is
'Permissions V2 applicability metadata. profile_code and required_feature_code are Sharawla Cloud identifiers; they are metadata only until PV2-B/C trusted server-side evaluation is deployed.';

comment on column public.permission_action_profiles_v2.required_feature_code is
'Optional Sharawla Cloud feature code. No FK exists because the authoritative Feature catalog lives in Sharawla Cloud, not the operational backend.';

insert into public.permission_action_profiles_v2(action_code,profile_code,required_feature_code,active)
values
 ('customers.create','logistics','core.customers',true),
 ('customers.create','membership','core.customers',true),
 ('customers.create','pharmacy','core.customers',true),
 ('customers.create','restaurant','core.customers',true),
 ('customers.create','retail','core.customers',true),
 ('customers.create','service','core.customers',true),
 ('customers.create','warehouse','core.customers',true),
 ('delivery.mark_delivered','pharmacy','commerce.delivery',true),
 ('delivery.mark_delivered','restaurant','commerce.delivery',true),
 ('delivery.mark_delivered','retail','commerce.delivery',true),
 ('delivery.payment.change_at_delivery','pharmacy','commerce.delivery',true),
 ('delivery.payment.change_at_delivery','restaurant','commerce.delivery',true),
 ('delivery.payment.change_at_delivery','retail','commerce.delivery',true),
 ('delivery.settlement.create','pharmacy','commerce.delivery',true),
 ('delivery.settlement.create','restaurant','commerce.delivery',true),
 ('delivery.settlement.create','retail','commerce.delivery',true),
 ('delivery.settlement.view','pharmacy','commerce.delivery',true),
 ('delivery.settlement.view','restaurant','commerce.delivery',true),
 ('delivery.settlement.view','retail','commerce.delivery',true),
 ('finance.collection.post','logistics','finance.collections',true),
 ('finance.collection.post','membership','finance.collections',true),
 ('finance.collection.post','pharmacy','finance.collections',true),
 ('finance.collection.post','restaurant','finance.collections',true),
 ('finance.collection.post','retail','finance.collections',true),
 ('finance.collection.post','service','finance.collections',true),
 ('finance.collection.post','warehouse','finance.collections',true),
 ('finance.credit.manage','logistics','finance.credit',true),
 ('finance.credit.manage','membership','finance.credit',true),
 ('finance.credit.manage','pharmacy','finance.credit',true),
 ('finance.credit.manage','restaurant','finance.credit',true),
 ('finance.credit.manage','retail','finance.credit',true),
 ('finance.credit.manage','service','finance.credit',true),
 ('finance.credit.manage','warehouse','finance.credit',true),
 ('finance.supplier.payment.post','pharmacy','inventory.purchasing',true),
 ('finance.supplier.payment.post','restaurant','inventory.purchasing',true),
 ('finance.supplier.payment.post','retail','inventory.purchasing',true),
 ('finance.supplier.payment.post','warehouse','inventory.purchasing',true),
 ('finance.supplier.statement.view','pharmacy','inventory.suppliers',true),
 ('finance.supplier.statement.view','restaurant','inventory.suppliers',true),
 ('finance.supplier.statement.view','retail','inventory.suppliers',true),
 ('finance.supplier.statement.view','warehouse','inventory.suppliers',true),
 ('food.ingredients.conversion.manage','restaurant','food.ingredients',true),
 ('food.ingredients.manage','restaurant','food.ingredients',true),
 ('food.ingredients.stock.adjust','restaurant','food.ingredients',true),
 ('food.prep.manage','restaurant','food.prep',true),
 ('food.production.complete','restaurant','food.production',true),
 ('food.production.start','restaurant','food.production',true),
 ('food.purchasing.approve','restaurant','inventory.purchasing',true),
 ('food.purchasing.cancel','restaurant','inventory.purchasing',true),
 ('food.purchasing.create','restaurant','inventory.purchasing',true),
 ('food.purchasing.receive','restaurant','inventory.receiving',true),
 ('food.purchasing.return','restaurant','inventory.purchasing',true),
 ('food.recipes.activate','restaurant','food.recipes',true),
 ('food.recipes.manage','restaurant','food.recipes',true),
 ('food.stock_count.post','restaurant','inventory.stock',true),
 ('food.suppliers.manage','restaurant','inventory.suppliers',true),
 ('food.transfer.cancel','restaurant','inventory.stock',true),
 ('food.transfer.create','restaurant','inventory.stock',true),
 ('food.transfer.receive','restaurant','inventory.stock',true),
 ('food.waste.post','restaurant','food.waste',true),
 ('hr.adjustments.manage','logistics',null,true),
 ('hr.adjustments.manage','membership',null,true),
 ('hr.adjustments.manage','pharmacy',null,true),
 ('hr.adjustments.manage','restaurant',null,true),
 ('hr.adjustments.manage','retail',null,true),
 ('hr.adjustments.manage','service',null,true),
 ('hr.adjustments.manage','warehouse',null,true),
 ('hr.adjustments.view','logistics',null,true),
 ('hr.adjustments.view','membership',null,true),
 ('hr.adjustments.view','pharmacy',null,true),
 ('hr.adjustments.view','restaurant',null,true),
 ('hr.adjustments.view','retail',null,true),
 ('hr.adjustments.view','service',null,true),
 ('hr.adjustments.view','warehouse',null,true),
 ('hr.advances.approve','logistics',null,true),
 ('hr.advances.approve','membership',null,true),
 ('hr.advances.approve','pharmacy',null,true),
 ('hr.advances.approve','restaurant',null,true),
 ('hr.advances.approve','retail',null,true),
 ('hr.advances.approve','service',null,true),
 ('hr.advances.approve','warehouse',null,true),
 ('hr.advances.create','logistics',null,true),
 ('hr.advances.create','membership',null,true),
 ('hr.advances.create','pharmacy',null,true),
 ('hr.advances.create','restaurant',null,true),
 ('hr.advances.create','retail',null,true),
 ('hr.advances.create','service',null,true),
 ('hr.advances.create','warehouse',null,true),
 ('hr.advances.disburse','logistics',null,true),
 ('hr.advances.disburse','membership',null,true),
 ('hr.advances.disburse','pharmacy',null,true),
 ('hr.advances.disburse','restaurant',null,true),
 ('hr.advances.disburse','retail',null,true),
 ('hr.advances.disburse','service',null,true),
 ('hr.advances.disburse','warehouse',null,true),
 ('hr.advances.view','logistics',null,true),
 ('hr.advances.view','membership',null,true),
 ('hr.advances.view','pharmacy',null,true),
 ('hr.advances.view','restaurant',null,true),
 ('hr.advances.view','retail',null,true),
 ('hr.advances.view','service',null,true),
 ('hr.advances.view','warehouse',null,true),
 ('hr.employees.create','logistics',null,true),
 ('hr.employees.create','membership',null,true),
 ('hr.employees.create','pharmacy',null,true),
 ('hr.employees.create','restaurant',null,true),
 ('hr.employees.create','retail',null,true),
 ('hr.employees.create','service',null,true),
 ('hr.employees.create','warehouse',null,true),
 ('hr.employees.edit','logistics',null,true),
 ('hr.employees.edit','membership',null,true),
 ('hr.employees.edit','pharmacy',null,true),
 ('hr.employees.edit','restaurant',null,true),
 ('hr.employees.edit','retail',null,true),
 ('hr.employees.edit','service',null,true),
 ('hr.employees.edit','warehouse',null,true),
 ('hr.employees.view','logistics',null,true),
 ('hr.employees.view','membership',null,true),
 ('hr.employees.view','pharmacy',null,true),
 ('hr.employees.view','restaurant',null,true),
 ('hr.employees.view','retail',null,true),
 ('hr.employees.view','service',null,true),
 ('hr.employees.view','warehouse',null,true),
 ('hr.payroll.approve','logistics',null,true),
 ('hr.payroll.approve','membership',null,true),
 ('hr.payroll.approve','pharmacy',null,true),
 ('hr.payroll.approve','restaurant',null,true),
 ('hr.payroll.approve','retail',null,true),
 ('hr.payroll.approve','service',null,true),
 ('hr.payroll.approve','warehouse',null,true),
 ('hr.payroll.pay','logistics',null,true),
 ('hr.payroll.pay','membership',null,true),
 ('hr.payroll.pay','pharmacy',null,true),
 ('hr.payroll.pay','restaurant',null,true),
 ('hr.payroll.pay','retail',null,true),
 ('hr.payroll.pay','service',null,true),
 ('hr.payroll.pay','warehouse',null,true),
 ('hr.payroll.run','logistics',null,true),
 ('hr.payroll.run','membership',null,true),
 ('hr.payroll.run','pharmacy',null,true),
 ('hr.payroll.run','restaurant',null,true),
 ('hr.payroll.run','retail',null,true),
 ('hr.payroll.run','service',null,true),
 ('hr.payroll.run','warehouse',null,true),
 ('hr.payroll.view','logistics',null,true),
 ('hr.payroll.view','membership',null,true),
 ('hr.payroll.view','pharmacy',null,true),
 ('hr.payroll.view','restaurant',null,true),
 ('hr.payroll.view','retail',null,true),
 ('hr.payroll.view','service',null,true),
 ('hr.payroll.view','warehouse',null,true),
 ('hr.salary.manage','logistics',null,true),
 ('hr.salary.manage','membership',null,true),
 ('hr.salary.manage','pharmacy',null,true),
 ('hr.salary.manage','restaurant',null,true),
 ('hr.salary.manage','retail',null,true),
 ('hr.salary.manage','service',null,true),
 ('hr.salary.manage','warehouse',null,true),
 ('hr.salary.view','logistics',null,true),
 ('hr.salary.view','membership',null,true),
 ('hr.salary.view','pharmacy',null,true),
 ('hr.salary.view','restaurant',null,true),
 ('hr.salary.view','retail',null,true),
 ('hr.salary.view','service',null,true),
 ('hr.salary.view','warehouse',null,true),
 ('inventory.adjust','pharmacy','inventory.stock',true),
 ('inventory.adjust','retail','inventory.stock',true),
 ('inventory.adjust','warehouse','inventory.stock',true),
 ('inventory.supply.configure','pharmacy','inventory.multi_warehouse',true),
 ('inventory.supply.configure','restaurant','inventory.multi_warehouse',true),
 ('inventory.supply.configure','retail','inventory.multi_warehouse',true),
 ('inventory.supply.configure','warehouse','inventory.multi_warehouse',true),
 ('inventory.supply.request.approve','pharmacy','inventory.multi_warehouse',true),
 ('inventory.supply.request.approve','restaurant','inventory.multi_warehouse',true),
 ('inventory.supply.request.approve','retail','inventory.multi_warehouse',true),
 ('inventory.supply.request.approve','warehouse','inventory.multi_warehouse',true),
 ('inventory.supply.request.create','pharmacy','inventory.multi_warehouse',true),
 ('inventory.supply.request.create','restaurant','inventory.multi_warehouse',true),
 ('inventory.supply.request.create','retail','inventory.multi_warehouse',true),
 ('inventory.supply.request.create','warehouse','inventory.multi_warehouse',true),
 ('inventory.supply.request.emergency','pharmacy','inventory.multi_warehouse',true),
 ('inventory.supply.request.emergency','restaurant','inventory.multi_warehouse',true),
 ('inventory.supply.request.emergency','retail','inventory.multi_warehouse',true),
 ('inventory.supply.request.emergency','warehouse','inventory.multi_warehouse',true),
 ('inventory.supply.request.fulfill','pharmacy','inventory.multi_warehouse',true),
 ('inventory.supply.request.fulfill','restaurant','inventory.multi_warehouse',true),
 ('inventory.supply.request.fulfill','retail','inventory.multi_warehouse',true),
 ('inventory.supply.request.fulfill','warehouse','inventory.multi_warehouse',true),
 ('inventory.supply.request.receive','pharmacy','inventory.multi_warehouse',true),
 ('inventory.supply.request.receive','restaurant','inventory.multi_warehouse',true),
 ('inventory.supply.request.receive','retail','inventory.multi_warehouse',true),
 ('inventory.supply.request.receive','warehouse','inventory.multi_warehouse',true),
 ('inventory.supply.request.submit','pharmacy','inventory.multi_warehouse',true),
 ('inventory.supply.request.submit','restaurant','inventory.multi_warehouse',true),
 ('inventory.supply.request.submit','retail','inventory.multi_warehouse',true),
 ('inventory.supply.request.submit','warehouse','inventory.multi_warehouse',true),
 ('inventory.supply.shortages.create','pharmacy','inventory.multi_warehouse',true),
 ('inventory.supply.shortages.create','restaurant','inventory.multi_warehouse',true),
 ('inventory.supply.shortages.create','retail','inventory.multi_warehouse',true),
 ('inventory.supply.shortages.create','warehouse','inventory.multi_warehouse',true),
 ('inventory.supply.shortages.view','pharmacy','inventory.multi_warehouse',true),
 ('inventory.supply.shortages.view','restaurant','inventory.multi_warehouse',true),
 ('inventory.supply.shortages.view','retail','inventory.multi_warehouse',true),
 ('inventory.supply.shortages.view','warehouse','inventory.multi_warehouse',true),
 ('inventory.supply.stock.availability','pharmacy','inventory.multi_warehouse',true),
 ('inventory.supply.stock.availability','restaurant','inventory.multi_warehouse',true),
 ('inventory.supply.stock.availability','retail','inventory.multi_warehouse',true),
 ('inventory.supply.stock.availability','warehouse','inventory.multi_warehouse',true),
 ('inventory.supply.stock.exact','pharmacy','inventory.multi_warehouse',true),
 ('inventory.supply.stock.exact','restaurant','inventory.multi_warehouse',true),
 ('inventory.supply.stock.exact','retail','inventory.multi_warehouse',true),
 ('inventory.supply.stock.exact','warehouse','inventory.multi_warehouse',true),
 ('inventory.supply.view','pharmacy','inventory.multi_warehouse',true),
 ('inventory.supply.view','restaurant','inventory.multi_warehouse',true),
 ('inventory.supply.view','retail','inventory.multi_warehouse',true),
 ('inventory.supply.view','warehouse','inventory.multi_warehouse',true),
 ('logistics.cod.settle','logistics','logistics.cod',true),
 ('logistics.shipment.create','logistics','logistics.shipments',true),
 ('logistics.shipment.status','logistics','logistics.shipments',true),
 ('membership.checkin','membership','membership.checkin',true),
 ('membership.freeze','membership','membership.freeze',true),
 ('membership.subscription.manage','membership','membership.subscriptions',true),
 ('orders.custom.manage','pharmacy','commerce.custom_orders',true),
 ('orders.custom.manage','restaurant','commerce.custom_orders',true),
 ('orders.custom.manage','retail','commerce.custom_orders',true),
 ('orders.custom.manage','service','commerce.custom_orders',true),
 ('orders.quotation.manage','pharmacy','commerce.quotations',true),
 ('orders.quotation.manage','restaurant','commerce.quotations',true),
 ('orders.quotation.manage','retail','commerce.quotations',true),
 ('orders.quotation.manage','service','commerce.quotations',true),
 ('orders.sales.approve','pharmacy','commerce.b2b_orders',true),
 ('orders.sales.approve','restaurant','commerce.b2b_orders',true),
 ('orders.sales.approve','retail','commerce.b2b_orders',true),
 ('orders.sales.approve','service','commerce.b2b_orders',true),
 ('production.manage','restaurant','food.production',true),
 ('purchasing.attachments.delete','pharmacy','inventory.purchasing',true),
 ('purchasing.attachments.delete','restaurant','inventory.purchasing',true),
 ('purchasing.attachments.delete','retail','inventory.purchasing',true),
 ('purchasing.attachments.delete','warehouse','inventory.purchasing',true),
 ('purchasing.attachments.upload','pharmacy','inventory.purchasing',true),
 ('purchasing.attachments.upload','restaurant','inventory.purchasing',true),
 ('purchasing.attachments.upload','retail','inventory.purchasing',true),
 ('purchasing.attachments.upload','warehouse','inventory.purchasing',true),
 ('purchasing.attachments.view','pharmacy','inventory.purchasing',true),
 ('purchasing.attachments.view','restaurant','inventory.purchasing',true),
 ('purchasing.attachments.view','retail','inventory.purchasing',true),
 ('purchasing.attachments.view','warehouse','inventory.purchasing',true),
 ('purchasing.po.approve','pharmacy','inventory.purchase_orders',true),
 ('purchasing.po.approve','restaurant','inventory.purchase_orders',true),
 ('purchasing.po.approve','retail','inventory.purchase_orders',true),
 ('purchasing.po.approve','warehouse','inventory.purchase_orders',true),
 ('purchasing.po.create','pharmacy','inventory.purchase_orders',true),
 ('purchasing.po.create','restaurant','inventory.purchase_orders',true),
 ('purchasing.po.create','retail','inventory.purchase_orders',true),
 ('purchasing.po.create','warehouse','inventory.purchase_orders',true),
 ('purchasing.receive','pharmacy','inventory.receiving',true),
 ('purchasing.receive','restaurant','inventory.receiving',true),
 ('purchasing.receive','retail','inventory.receiving',true),
 ('purchasing.receive','warehouse','inventory.receiving',true),
 ('purchasing.request.approve','pharmacy','inventory.purchase_orders',true),
 ('purchasing.request.approve','restaurant','inventory.purchase_orders',true),
 ('purchasing.request.approve','retail','inventory.purchase_orders',true),
 ('purchasing.request.approve','warehouse','inventory.purchase_orders',true),
 ('purchasing.request.create','pharmacy','inventory.purchase_orders',true),
 ('purchasing.request.create','restaurant','inventory.purchase_orders',true),
 ('purchasing.request.create','retail','inventory.purchase_orders',true),
 ('purchasing.request.create','warehouse','inventory.purchase_orders',true),
 ('purchasing.supplier_return','pharmacy','inventory.supplier_returns',true),
 ('purchasing.supplier_return','restaurant','inventory.supplier_returns',true),
 ('purchasing.supplier_return','retail','inventory.supplier_returns',true),
 ('purchasing.supplier_return','warehouse','inventory.supplier_returns',true),
 ('recipe.manage','restaurant','food.recipes',true),
 ('reports.export','logistics','core.reports',true),
 ('reports.export','membership','core.reports',true),
 ('reports.export','pharmacy','core.reports',true),
 ('reports.export','restaurant','core.reports',true),
 ('reports.export','retail','core.reports',true),
 ('reports.export','service','core.reports',true),
 ('reports.export','warehouse','core.reports',true),
 ('restaurant.tables.manage','restaurant','food.tables',true),
 ('restaurant.tables.use','restaurant','food.tables',true),
 ('service.appointment.manage','service','service.appointments',true),
 ('service.job.complete','service','service.jobs',true),
 ('service.job.manage','service','service.jobs',true),
 ('service.warranty.manage','service','service.warranty',true),
 ('settings.capabilities','logistics','core.permissions',true),
 ('settings.capabilities','membership','core.permissions',true),
 ('settings.capabilities','pharmacy','core.permissions',true),
 ('settings.capabilities','restaurant','core.permissions',true),
 ('settings.capabilities','retail','core.permissions',true),
 ('settings.capabilities','service','core.permissions',true),
 ('settings.capabilities','warehouse','core.permissions',true),
 ('treasury.post','logistics',null,true),
 ('treasury.post','membership',null,true),
 ('treasury.post','pharmacy',null,true),
 ('treasury.post','restaurant',null,true),
 ('treasury.post','retail',null,true),
 ('treasury.post','service',null,true),
 ('treasury.post','warehouse',null,true),
 ('treasury.view','logistics',null,true),
 ('treasury.view','membership',null,true),
 ('treasury.view','pharmacy',null,true),
 ('treasury.view','restaurant',null,true),
 ('treasury.view','retail',null,true),
 ('treasury.view','service',null,true),
 ('treasury.view','warehouse',null,true),
 ('waste.post','restaurant','food.waste',true)
on conflict(action_code,profile_code) do update
set required_feature_code=excluded.required_feature_code,
    active=excluded.active,
    updated_at=now();

alter table public.permission_action_profiles_v2 enable row level security;

drop policy if exists permission_action_profiles_v2_read on public.permission_action_profiles_v2;
create policy permission_action_profiles_v2_read
on public.permission_action_profiles_v2
for select
to authenticated
using(active=true);

revoke all on table public.permission_action_profiles_v2 from public,anon,authenticated;
grant select on table public.permission_action_profiles_v2 to authenticated;

commit;
