-- Restaurant POS V5 Foundation
-- Run once in Supabase SQL Editor before uploading V5 files.

-- 1) Rename the two current branches
update public.branches set name = 'العشرين' where id = 1;
update public.branches set name = 'الدقي' where id = 2;

-- 2) Customers: extra searchable data
alter table public.customers add column if not exists area text;
alter table public.customers add column if not exists updated_at timestamptz default now();

create table if not exists public.customer_addresses (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  label text,
  address text not null,
  area text,
  notes text,
  is_default boolean not null default false,
  created_at timestamptz default now()
);

-- 3) Delivery zones
create table if not exists public.delivery_zones (
  id bigint generated by default as identity primary key,
  name text not null,
  delivery_fee numeric(12,2) not null default 0,
  branch_id bigint references public.branches(id) on delete set null,
  active boolean not null default true,
  created_at timestamptz default now()
);

-- 4) Delivery drivers
create table if not exists public.delivery_drivers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  branch_id bigint references public.branches(id) on delete set null,
  active boolean not null default true,
  created_at timestamptz default now()
);

-- 5) Branch-specific product availability / optional price override
create table if not exists public.branch_products (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  active boolean not null default true,
  price_override numeric(12,2),
  unique(branch_id, product_id)
);

-- 6) Expanded orders
alter table public.orders add column if not exists source text not null default 'pos';
alter table public.orders add column if not exists customer_phone text;
alter table public.orders add column if not exists delivery_address text;
alter table public.orders add column if not exists delivery_zone_id bigint references public.delivery_zones(id) on delete set null;
alter table public.orders add column if not exists driver_id bigint references public.delivery_drivers(id) on delete set null;
alter table public.orders add column if not exists assigned_at timestamptz;
alter table public.orders add column if not exists delivered_at timestamptz;
alter table public.orders add column if not exists cancelled_reason text;
alter table public.orders add column if not exists order_number text;

-- delivery_fee already existed in the original schema; this is safe if it exists
alter table public.orders add column if not exists delivery_fee numeric(12,2) not null default 0;

-- 7) Split / mixed payments
create table if not exists public.order_payments (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  method text not null check (method in ('cash','wallet','instapay')),
  amount numeric(12,2) not null check (amount >= 0),
  created_at timestamptz default now()
);

-- 8) Audit log
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  employee_id bigint references public.employees(id) on delete set null,
  branch_id bigint references public.branches(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id bigint,
  details jsonb,
  created_at timestamptz default now()
);

-- 9) Settings for the sales-first rollout
insert into public.app_settings ("key","value") values
('enable_kitchen','false'),
('enable_inventory','false'),
('enable_delivery','true'),
('enable_customer_search','true'),
('enable_delivery_drivers','true'),
('enable_prep_receipt','true'),
('enable_receipt_print','true'),
('enable_mixed_payment','true')
on conflict ("key") do update set "value" = excluded."value";

-- 10) Enable RLS on new tables
alter table public.customer_addresses enable row level security;
alter table public.delivery_zones enable row level security;
alter table public.delivery_drivers enable row level security;
alter table public.branch_products enable row level security;
alter table public.order_payments enable row level security;
alter table public.audit_logs enable row level security;

grant select, insert, update, delete on
  public.customer_addresses,
  public.delivery_zones,
  public.delivery_drivers,
  public.branch_products,
  public.order_payments,
  public.audit_logs
to authenticated;

grant usage, select on all sequences in schema public to authenticated;

-- Admin keeps full access, matching the current security model.
do $$
declare t text;
begin
  foreach t in array array[
    'customer_addresses','delivery_zones','delivery_drivers',
    'branch_products','order_payments','audit_logs'
  ]
  loop
    execute format('drop policy if exists admin_all on public.%I', t);
    execute format(
      'create policy admin_all on public.%I for all to authenticated using (public.is_admin()) with check (public.is_admin())',
      t
    );
  end loop;
end $$;

notify pgrst, 'reload schema';
