-- Sharawla POS 10.5.16 — Production Restaurant Inventory/Food Operations
-- Sandbox-first additive migration for SH-0007.
-- Reuses the existing Restaurant supplier/purchase/ingredient/stock-transfer tables.
-- Adds transactional receiving, supplier returns, ingredient stock count and safe transfers. Tables are out of scope.

begin;

-- -----------------------------------------------------------------------------
-- 1) Legacy Restaurant purchasing tables: additive workflow columns only
-- -----------------------------------------------------------------------------
alter table public.suppliers add column if not exists email text;
alter table public.suppliers add column if not exists tax_no text;
alter table public.suppliers add column if not exists updated_at timestamptz not null default now();

alter table public.purchases add column if not exists status text not null default 'draft';
alter table public.purchases add column if not exists client_tx_id text;
alter table public.purchases add column if not exists created_by_employee_id bigint references public.employees(id);
alter table public.purchases add column if not exists approved_by_employee_id bigint references public.employees(id);
alter table public.purchases add column if not exists approved_at timestamptz;
alter table public.purchases add column if not exists received_by_employee_id bigint references public.employees(id);
alter table public.purchases add column if not exists received_at timestamptz;
alter table public.purchases add column if not exists updated_at timestamptz not null default now();
create unique index if not exists purchases_client_tx_uidx on public.purchases(client_tx_id) where client_tx_id is not null;
create index if not exists purchases_branch_status_idx on public.purchases(branch_id,status,created_at desc);

alter table public.purchase_items add column if not exists unit_code text;
alter table public.purchase_items add column if not exists conversion_factor_to_base numeric(18,6) not null default 1;
alter table public.purchase_items add column if not exists received_quantity numeric(18,6) not null default 0;
alter table public.purchase_items add column if not exists base_quantity_ordered numeric(18,6);
alter table public.purchase_items add column if not exists base_quantity_received numeric(18,6) not null default 0;

alter table public.stock_transfers add column if not exists client_tx_id text;
alter table public.stock_transfers add column if not exists created_by_employee_id bigint references public.employees(id);
alter table public.stock_transfers add column if not exists received_by_employee_id bigint references public.employees(id);
alter table public.stock_transfers add column if not exists cancelled_by_employee_id bigint references public.employees(id);
alter table public.stock_transfers add column if not exists received_at timestamptz;
alter table public.stock_transfers add column if not exists cancelled_at timestamptz;
create unique index if not exists stock_transfers_client_tx_uidx on public.stock_transfers(client_tx_id) where client_tx_id is not null;

alter table public.stock_transfer_items add column if not exists unit_code text;
alter table public.stock_transfer_items add column if not exists conversion_factor_to_base numeric(18,6) not null default 1;
alter table public.stock_transfer_items add column if not exists base_quantity numeric(18,6);
alter table public.stock_transfer_items add column if not exists unit_cost_snapshot numeric(18,6) not null default 0;

-- -----------------------------------------------------------------------------
-- 2) Transactional receipt / supplier-return / stock-count documents
-- -----------------------------------------------------------------------------
create table if not exists public.food_purchase_receipts(
 id bigint generated by default as identity primary key,
 purchase_id bigint not null references public.purchases(id) on delete restrict,
 branch_id bigint not null references public.branches(id) on delete restrict,
 supplier_id bigint null references public.suppliers(id) on delete restrict,
 client_tx_id text not null unique,
 created_by_employee_id bigint null references public.employees(id),
 received_at timestamptz not null default now()
);

create table if not exists public.food_purchase_receipt_items(
 id bigint generated by default as identity primary key,
 receipt_id bigint not null references public.food_purchase_receipts(id) on delete cascade,
 purchase_item_id bigint not null references public.purchase_items(id) on delete restrict,
 ingredient_id bigint not null references public.ingredients(id) on delete restrict,
 quantity numeric(18,6) not null check(quantity>0),
 unit_code text not null,
 conversion_factor_to_base numeric(18,6) not null check(conversion_factor_to_base>0),
 base_quantity numeric(18,6) not null check(base_quantity>0),
 unit_cost numeric(18,6) not null check(unit_cost>=0),
 base_unit_cost numeric(18,6) not null check(base_unit_cost>=0)
);

create table if not exists public.food_supplier_returns(
 id bigint generated by default as identity primary key,
 branch_id bigint not null references public.branches(id) on delete restrict,
 supplier_id bigint null references public.suppliers(id) on delete restrict,
 notes text null,
 client_tx_id text not null unique,
 created_by_employee_id bigint null references public.employees(id),
 created_at timestamptz not null default now()
);

create table if not exists public.food_supplier_return_items(
 id bigint generated by default as identity primary key,
 supplier_return_id bigint not null references public.food_supplier_returns(id) on delete cascade,
 ingredient_id bigint not null references public.ingredients(id) on delete restrict,
 quantity numeric(18,6) not null check(quantity>0),
 unit_code text not null,
 conversion_factor_to_base numeric(18,6) not null check(conversion_factor_to_base>0),
 base_quantity numeric(18,6) not null check(base_quantity>0),
 unit_cost_snapshot numeric(18,6) not null default 0 check(unit_cost_snapshot>=0)
);

create table if not exists public.food_stock_counts(
 id bigint generated by default as identity primary key,
 branch_id bigint not null references public.branches(id) on delete restrict,
 status text not null default 'posted' check(status in('posted','cancelled')),
 notes text null,
 client_tx_id text not null unique,
 created_by_employee_id bigint null references public.employees(id),
 created_at timestamptz not null default now()
);

create table if not exists public.food_stock_count_items(
 id bigint generated by default as identity primary key,
 stock_count_id bigint not null references public.food_stock_counts(id) on delete cascade,
 ingredient_id bigint not null references public.ingredients(id) on delete restrict,
 system_quantity numeric(18,6) not null,
 counted_quantity numeric(18,6) not null check(counted_quantity>=0),
 variance numeric(18,6) not null,
 unit_cost_snapshot numeric(18,6) not null default 0,
 unique(stock_count_id,ingredient_id)
);

create index if not exists food_purchase_receipts_branch_idx on public.food_purchase_receipts(branch_id,received_at desc);
create index if not exists food_supplier_returns_branch_idx on public.food_supplier_returns(branch_id,created_at desc);
create index if not exists food_stock_counts_branch_idx on public.food_stock_counts(branch_id,created_at desc);

-- -----------------------------------------------------------------------------
-- 4) Read policies. All writes stay behind SECURITY DEFINER RPCs.
-- -----------------------------------------------------------------------------
alter table public.food_purchase_receipts enable row level security;
alter table public.food_purchase_receipt_items enable row level security;
alter table public.food_supplier_returns enable row level security;
alter table public.food_supplier_return_items enable row level security;
alter table public.food_stock_counts enable row level security;
alter table public.food_stock_count_items enable row level security;

drop policy if exists food_purchase_receipts_select_v1 on public.food_purchase_receipts;
create policy food_purchase_receipts_select_v1 on public.food_purchase_receipts for select to authenticated
 using(public.has_branch_access(branch_id));
drop policy if exists food_purchase_receipt_items_select_v1 on public.food_purchase_receipt_items;
create policy food_purchase_receipt_items_select_v1 on public.food_purchase_receipt_items for select to authenticated
 using(exists(select 1 from public.food_purchase_receipts r where r.id=receipt_id and public.has_branch_access(r.branch_id)));
drop policy if exists food_supplier_returns_select_v1 on public.food_supplier_returns;
create policy food_supplier_returns_select_v1 on public.food_supplier_returns for select to authenticated
 using(public.has_branch_access(branch_id));
drop policy if exists food_supplier_return_items_select_v1 on public.food_supplier_return_items;
create policy food_supplier_return_items_select_v1 on public.food_supplier_return_items for select to authenticated
 using(exists(select 1 from public.food_supplier_returns r where r.id=supplier_return_id and public.has_branch_access(r.branch_id)));
drop policy if exists food_stock_counts_select_v1 on public.food_stock_counts;
create policy food_stock_counts_select_v1 on public.food_stock_counts for select to authenticated
 using(public.has_branch_access(branch_id));
drop policy if exists food_stock_count_items_select_v1 on public.food_stock_count_items;
create policy food_stock_count_items_select_v1 on public.food_stock_count_items for select to authenticated
 using(exists(select 1 from public.food_stock_counts c where c.id=stock_count_id and public.has_branch_access(c.branch_id)));
-- Existing Restaurant master/document read policies for permissioned non-admins.
drop policy if exists beta55_restaurant_suppliers_select on public.suppliers;
create policy beta55_restaurant_suppliers_select on public.suppliers for select to authenticated
 using(public.is_admin() or public.has_permission('suppliers') or public.has_permission('purchasing'));
drop policy if exists beta55_restaurant_purchases_select on public.purchases;
create policy beta55_restaurant_purchases_select on public.purchases for select to authenticated
 using(public.has_branch_access(branch_id) and (public.is_admin() or public.has_permission('purchasing')));
drop policy if exists beta55_restaurant_purchase_items_select on public.purchase_items;
create policy beta55_restaurant_purchase_items_select on public.purchase_items for select to authenticated
 using(exists(select 1 from public.purchases p where p.id=purchase_id and public.has_branch_access(p.branch_id) and (public.is_admin() or public.has_permission('purchasing'))));
drop policy if exists beta55_restaurant_transfers_select on public.stock_transfers;
create policy beta55_restaurant_transfers_select on public.stock_transfers for select to authenticated
 using((public.has_branch_access(from_branch_id) or public.has_branch_access(to_branch_id)) and (public.is_admin() or public.has_permission('transfers')));
drop policy if exists beta55_restaurant_transfer_items_select on public.stock_transfer_items;
create policy beta55_restaurant_transfer_items_select on public.stock_transfer_items for select to authenticated
 using(exists(select 1 from public.stock_transfers t where t.id=transfer_id and (public.has_branch_access(t.from_branch_id) or public.has_branch_access(t.to_branch_id))));

revoke insert,update,delete on public.food_purchase_receipts,public.food_purchase_receipt_items,
 public.food_supplier_returns,public.food_supplier_return_items,public.food_stock_counts,public.food_stock_count_items
 from authenticated;
grant select on public.food_purchase_receipts,public.food_purchase_receipt_items,
 public.food_supplier_returns,public.food_supplier_return_items,public.food_stock_counts,public.food_stock_count_items
 to authenticated;

-- -----------------------------------------------------------------------------
-- 5) Internal stock mutation helper (never callable directly by authenticated)
-- -----------------------------------------------------------------------------
create or replace function public.food_apply_ingredient_delta_internal_v1(
 p_branch_id bigint,
 p_ingredient_id bigint,
 p_quantity_delta numeric,
 p_unit_cost numeric,
 p_movement_type text,
 p_reference_type text,
 p_reference_id bigint,
 p_notes text
) returns jsonb
language plpgsql security definer set search_path=public as $$
declare
 v_stock public.ingredient_stock%rowtype;
 v_track boolean;
 v_new numeric(18,6);
 v_avg numeric(18,6);
 v_cost numeric(18,6):=greatest(0,coalesce(p_unit_cost,0));
begin
 if coalesce(p_quantity_delta,0)=0 then
   select * into v_stock from public.ingredient_stock where branch_id=p_branch_id and ingredient_id=p_ingredient_id;
   return jsonb_build_object('quantity',coalesce(v_stock.quantity,0),'average_unit_cost',coalesce(v_stock.average_unit_cost,0));
 end if;
 select track_inventory into v_track from public.ingredients where id=p_ingredient_id and active is distinct from false;
 if not found then raise exception 'الخامة غير موجودة أو موقوفة'; end if;
 if not coalesce(v_track,true) then raise exception 'الخامة غير متتبعة بالمخزون'; end if;
 insert into public.ingredient_stock(branch_id,ingredient_id,quantity) values(p_branch_id,p_ingredient_id,0)
 on conflict(branch_id,ingredient_id) do nothing;
 select * into v_stock from public.ingredient_stock where branch_id=p_branch_id and ingredient_id=p_ingredient_id for update;
 v_new:=round(v_stock.quantity+p_quantity_delta,6);
 if v_new<0 then raise exception 'مخزون الخامة غير كافٍ'; end if;
 v_avg:=v_stock.average_unit_cost;
 if p_quantity_delta>0 and v_cost>0 then
   v_avg:=case when v_new<=0 then v_cost else round(((v_stock.quantity*v_stock.average_unit_cost)+(p_quantity_delta*v_cost))/v_new,6) end;
 end if;
 update public.ingredient_stock
 set quantity=v_new,
     average_unit_cost=greatest(0,coalesce(v_avg,0)),
     last_purchase_cost=case when p_movement_type='purchase' and v_cost>0 then v_cost else last_purchase_cost end,
     last_costed_at=case when p_movement_type='purchase' and v_cost>0 then now() else last_costed_at end,
     updated_at=now()
 where id=v_stock.id;
 insert into public.stock_movements(branch_id,ingredient_id,movement_type,quantity,reference_type,reference_id,notes)
 values(p_branch_id,p_ingredient_id,p_movement_type,round(p_quantity_delta,6),p_reference_type,p_reference_id,p_notes);
 return jsonb_build_object('quantity',v_new,'average_unit_cost',greatest(0,coalesce(v_avg,0)));
end;$$;
revoke all on function public.food_apply_ingredient_delta_internal_v1(bigint,bigint,numeric,numeric,text,text,bigint,text) from public,authenticated;

-- -----------------------------------------------------------------------------
-- 6) Suppliers + raw-material Purchase Order / Receive / Return
-- -----------------------------------------------------------------------------
create or replace function public.food_supplier_save_v1(
 p_supplier_id bigint,
 p_name text,
 p_phone text,
 p_email text,
 p_tax_no text,
 p_address text,
 p_notes text,
 p_active boolean
) returns bigint
language plpgsql security definer set search_path=public as $$
declare v_id bigint;
begin
 if auth.uid() is null then raise exception 'غير مصرح'; end if;
 if not public.has_action_permission_v2('food.suppliers.manage') then raise exception 'ليس لديك صلاحية إدارة الموردين'; end if;
 if nullif(trim(coalesce(p_name,'')),'') is null then raise exception 'اسم المورد مطلوب'; end if;
 if p_supplier_id is null then
   insert into public.suppliers(name,phone,email,tax_no,address,notes,active,updated_at)
   values(trim(p_name),nullif(trim(coalesce(p_phone,'')),''),nullif(trim(coalesce(p_email,'')),''),nullif(trim(coalesce(p_tax_no,'')),''),nullif(trim(coalesce(p_address,'')),''),nullif(trim(coalesce(p_notes,'')),''),coalesce(p_active,true),now()) returning id into v_id;
 else
   update public.suppliers set name=trim(p_name),phone=nullif(trim(coalesce(p_phone,'')),''),email=nullif(trim(coalesce(p_email,'')),''),tax_no=nullif(trim(coalesce(p_tax_no,'')),''),address=nullif(trim(coalesce(p_address,'')),''),notes=nullif(trim(coalesce(p_notes,'')),''),active=coalesce(p_active,true),updated_at=now()
   where id=p_supplier_id returning id into v_id;
   if v_id is null then raise exception 'المورد غير موجود'; end if;
 end if;
 insert into public.audit_logs(employee_id,branch_id,action,entity_type,entity_id,details)
 values(public.current_employee_id(),null,'food.suppliers.manage','supplier',v_id,jsonb_build_object('name',p_name,'active',p_active));
 return v_id;
end;$$;

create or replace function public.food_purchase_order_create_v1(
 p_branch_id bigint,
 p_supplier_id bigint,
 p_invoice_number text,
 p_notes text,
 p_items jsonb,
 p_client_tx_id text
) returns bigint
language plpgsql security definer set search_path=public as $$
declare
 v_id bigint;v_emp bigint;v_key text:=nullif(trim(coalesce(p_client_tx_id,'')),'');v record;
 v_base text;v_unit text;v_factor numeric(18,6);v_qty numeric(18,6);v_cost numeric(18,6);v_total numeric(18,6):=0;
begin
 if auth.uid() is null then raise exception 'غير مصرح'; end if;
 if not public.has_action_permission_v2('food.purchasing.create') then raise exception 'ليس لديك صلاحية إنشاء أمر شراء خامات'; end if;
 if not public.has_branch_access(p_branch_id) then raise exception 'ليس لديك صلاحية لهذا الفرع'; end if;
 if v_key is null then raise exception 'معرف الحركة مطلوب'; end if;
 if not exists(select 1 from public.suppliers where id=p_supplier_id and active is distinct from false) then raise exception 'المورد غير موجود أو موقوف'; end if;
 if jsonb_array_length(coalesce(p_items,'[]'::jsonb))=0 then raise exception 'أضف خامة واحدة على الأقل'; end if;
 perform pg_advisory_xact_lock(hashtextextended('food-po:'||v_key,0));
 select id into v_id from public.purchases where client_tx_id=v_key;
 if v_id is not null then return v_id; end if;
 v_emp:=public.current_employee_id();
 insert into public.purchases(branch_id,supplier_id,invoice_number,total,paid,notes,status,client_tx_id,created_by_employee_id,updated_at)
 values(p_branch_id,p_supplier_id,nullif(trim(coalesce(p_invoice_number,'')),''),0,0,nullif(trim(coalesce(p_notes,'')),''),'draft',v_key,v_emp,now()) returning id into v_id;
 for v in select * from jsonb_to_recordset(p_items) as x(ingredient_id bigint,quantity numeric,unit_code text,unit_cost numeric) loop
   select coalesce(base_unit_code,unit),coalesce(purchase_unit_code,base_unit_code,unit) into v_base,v_unit from public.ingredients where id=v.ingredient_id and active is distinct from false;
   if not found then raise exception 'خامة غير صالحة %',v.ingredient_id; end if;
   v_qty:=round(coalesce(v.quantity,0)::numeric,6);v_cost:=round(coalesce(v.unit_cost,-1)::numeric,6);v_unit:=coalesce(nullif(trim(coalesce(v.unit_code,'')),''),v_unit,v_base);
   if v_qty<=0 or v_cost<0 then raise exception 'كمية/تكلفة غير صحيحة للخامة %',v.ingredient_id; end if;
   v_factor:=public.ingredient_unit_factor_v1(v.ingredient_id,v_unit,v_base);
   if v_factor is null or v_factor<=0 then raise exception 'لا يوجد تحويل وحدة صالح للخامة % من % إلى %',v.ingredient_id,v_unit,v_base; end if;
   insert into public.purchase_items(purchase_id,ingredient_id,quantity,unit_cost,total,unit_code,conversion_factor_to_base,received_quantity,base_quantity_ordered,base_quantity_received)
   values(v_id,v.ingredient_id,v_qty,v_cost,round(v_qty*v_cost,6),v_unit,v_factor,0,round(v_qty*v_factor,6),0);
   v_total:=v_total+round(v_qty*v_cost,6);
 end loop;
 update public.purchases set total=round(v_total,6),updated_at=now() where id=v_id;
 insert into public.audit_logs(employee_id,branch_id,action,entity_type,entity_id,details)
 values(v_emp,p_branch_id,'food.purchasing.create','purchase',v_id,jsonb_build_object('supplier_id',p_supplier_id,'client_tx_id',v_key,'total',round(v_total,6)));
 return v_id;
end;$$;

create or replace function public.food_purchase_order_approve_v1(p_purchase_id bigint) returns bigint
language plpgsql security definer set search_path=public as $$
declare v_po public.purchases%rowtype;v_emp bigint;
begin
 if auth.uid() is null then raise exception 'غير مصرح'; end if;
 if not public.has_action_permission_v2('food.purchasing.approve') then raise exception 'ليس لديك صلاحية اعتماد أمر شراء خامات'; end if;
 select * into v_po from public.purchases where id=p_purchase_id for update;
 if not found then raise exception 'أمر الشراء غير موجود'; end if;
 if not public.has_branch_access(v_po.branch_id) then raise exception 'ليس لديك صلاحية لهذا الفرع'; end if;
 if v_po.status='approved' then return v_po.id; end if;
 if v_po.status<>'draft' then raise exception 'يمكن اعتماد المسودة فقط'; end if;
 v_emp:=public.current_employee_id();
 update public.purchases set status='approved',approved_by_employee_id=v_emp,approved_at=now(),updated_at=now() where id=v_po.id;
 insert into public.audit_logs(employee_id,branch_id,action,entity_type,entity_id,details)
 values(v_emp,v_po.branch_id,'food.purchasing.approve','purchase',v_po.id,null);
 return v_po.id;
end;$$;

create or replace function public.food_purchase_order_cancel_v1(p_purchase_id bigint,p_reason text) returns bigint
language plpgsql security definer set search_path=public as $$
declare v_po public.purchases%rowtype;v_emp bigint;
begin
 if auth.uid() is null then raise exception 'غير مصرح'; end if;
 if not public.has_action_permission_v2('food.purchasing.approve') then raise exception 'ليس لديك صلاحية إلغاء أمر الشراء'; end if;
 select * into v_po from public.purchases where id=p_purchase_id for update;
 if not found then raise exception 'أمر الشراء غير موجود'; end if;
 if not public.has_branch_access(v_po.branch_id) then raise exception 'ليس لديك صلاحية لهذا الفرع'; end if;
 if v_po.status='cancelled' then return v_po.id; end if;
 if exists(select 1 from public.purchase_items where purchase_id=v_po.id and received_quantity>0) then raise exception 'لا يمكن إلغاء أمر شراء تم استلام جزء منه'; end if;
 if v_po.status not in('draft','approved') then raise exception 'أمر الشراء غير قابل للإلغاء'; end if;
 v_emp:=public.current_employee_id();
 update public.purchases set status='cancelled',notes=concat_ws(E'\n',notes,nullif(trim(coalesce(p_reason,'')),'')),updated_at=now() where id=v_po.id;
 insert into public.audit_logs(employee_id,branch_id,action,entity_type,entity_id,details)
 values(v_emp,v_po.branch_id,'food.purchasing.cancel','purchase',v_po.id,jsonb_build_object('reason',p_reason));
 return v_po.id;
end;$$;

insert into public.permission_actions_v2(code,name_ar,domain,legacy_permission,active,sort_order)
values('food.purchasing.cancel','إلغاء أمر شراء خامات قبل الاستلام','food',null,true,745)
on conflict(code) do update set name_ar=excluded.name_ar,domain=excluded.domain,legacy_permission=null,active=true,sort_order=excluded.sort_order;

create or replace function public.food_purchase_receive_v1(
 p_purchase_id bigint,
 p_items jsonb,
 p_client_tx_id text
) returns bigint
language plpgsql security definer set search_path=public as $$
declare
 v_po public.purchases%rowtype;v_receipt bigint;v_emp bigint;v_key text:=nullif(trim(coalesce(p_client_tx_id,'')),'');v record;
 v_line public.purchase_items%rowtype;v_qty numeric(18,6);v_base_qty numeric(18,6);v_base_cost numeric(18,6);
begin
 if auth.uid() is null then raise exception 'غير مصرح'; end if;
 if not public.has_action_permission_v2('food.purchasing.receive') then raise exception 'ليس لديك صلاحية استلام مشتريات الخامات'; end if;
 if v_key is null then raise exception 'معرف الحركة مطلوب'; end if;
 perform pg_advisory_xact_lock(hashtextextended('food-receive:'||v_key,0));
 select id into v_receipt from public.food_purchase_receipts where client_tx_id=v_key;
 if v_receipt is not null then return v_receipt; end if;
 select * into v_po from public.purchases where id=p_purchase_id for update;
 if not found then raise exception 'أمر الشراء غير موجود'; end if;
 if not public.has_branch_access(v_po.branch_id) then raise exception 'ليس لديك صلاحية لهذا الفرع'; end if;
 if v_po.status not in('approved','partially_received') then raise exception 'أمر الشراء غير جاهز للاستلام'; end if;
 if jsonb_array_length(coalesce(p_items,'[]'::jsonb))=0 then raise exception 'لا توجد كميات للاستلام'; end if;
 v_emp:=public.current_employee_id();
 insert into public.food_purchase_receipts(purchase_id,branch_id,supplier_id,client_tx_id,created_by_employee_id)
 values(v_po.id,v_po.branch_id,v_po.supplier_id,v_key,v_emp) returning id into v_receipt;
 for v in select * from jsonb_to_recordset(p_items) as x(purchase_item_id bigint,quantity numeric) loop
   select * into v_line from public.purchase_items where id=v.purchase_item_id and purchase_id=v_po.id for update;
   if not found then raise exception 'سطر الاستلام غير موجود في أمر الشراء'; end if;
   v_qty:=round(coalesce(v.quantity,0)::numeric,6);
   if v_qty<=0 then raise exception 'كمية الاستلام يجب أن تكون أكبر من صفر'; end if;
   if v_line.received_quantity+v_qty>v_line.quantity then raise exception 'كمية الاستلام تتجاوز المتبقي للخامة %',v_line.ingredient_id; end if;
   v_base_qty:=round(v_qty*v_line.conversion_factor_to_base,6);
   v_base_cost:=case when v_line.conversion_factor_to_base>0 then round(v_line.unit_cost/v_line.conversion_factor_to_base,6) else 0 end;
   perform public.food_apply_ingredient_delta_internal_v1(v_po.branch_id,v_line.ingredient_id,v_base_qty,v_base_cost,'purchase','food_purchase_receipt',v_receipt,'استلام أمر شراء خامات');
   update public.purchase_items set received_quantity=round(received_quantity+v_qty,6),base_quantity_received=round(base_quantity_received+v_base_qty,6) where id=v_line.id;
   insert into public.food_purchase_receipt_items(receipt_id,purchase_item_id,ingredient_id,quantity,unit_code,conversion_factor_to_base,base_quantity,unit_cost,base_unit_cost)
   values(v_receipt,v_line.id,v_line.ingredient_id,v_qty,coalesce(v_line.unit_code,''),v_line.conversion_factor_to_base,v_base_qty,v_line.unit_cost,v_base_cost);
 end loop;
 update public.purchases p set
   status=case when not exists(select 1 from public.purchase_items i where i.purchase_id=p.id and i.received_quantity<i.quantity) then 'received' else 'partially_received' end,
   received_by_employee_id=v_emp,
   received_at=case when not exists(select 1 from public.purchase_items i where i.purchase_id=p.id and i.received_quantity<i.quantity) then now() else received_at end,
   updated_at=now()
 where p.id=v_po.id;
 insert into public.audit_logs(employee_id,branch_id,action,entity_type,entity_id,details)
 values(v_emp,v_po.branch_id,'food.purchasing.receive','food_purchase_receipt',v_receipt,jsonb_build_object('purchase_id',v_po.id,'client_tx_id',v_key));
 return v_receipt;
end;$$;

create or replace function public.food_supplier_return_create_v1(
 p_branch_id bigint,
 p_supplier_id bigint,
 p_notes text,
 p_items jsonb,
 p_client_tx_id text
) returns bigint
language plpgsql security definer set search_path=public as $$
declare
 v_ret bigint;v_emp bigint;v_key text:=nullif(trim(coalesce(p_client_tx_id,'')),'');v record;
 v_base text;v_unit text;v_factor numeric(18,6);v_qty numeric(18,6);v_base_qty numeric(18,6);v_stock public.ingredient_stock%rowtype;
begin
 if auth.uid() is null then raise exception 'غير مصرح'; end if;
 if not public.has_action_permission_v2('food.purchasing.return') then raise exception 'ليس لديك صلاحية مرتجع المورد'; end if;
 if not public.has_branch_access(p_branch_id) then raise exception 'ليس لديك صلاحية لهذا الفرع'; end if;
 if v_key is null then raise exception 'معرف الحركة مطلوب'; end if;
 if p_supplier_id is not null and not exists(select 1 from public.suppliers where id=p_supplier_id) then raise exception 'المورد غير موجود'; end if;
 if jsonb_array_length(coalesce(p_items,'[]'::jsonb))=0 then raise exception 'أضف خامة واحدة على الأقل'; end if;
 perform pg_advisory_xact_lock(hashtextextended('food-supplier-return:'||v_key,0));
 select id into v_ret from public.food_supplier_returns where client_tx_id=v_key;if v_ret is not null then return v_ret;end if;
 v_emp:=public.current_employee_id();
 insert into public.food_supplier_returns(branch_id,supplier_id,notes,client_tx_id,created_by_employee_id)
 values(p_branch_id,p_supplier_id,nullif(trim(coalesce(p_notes,'')),''),v_key,v_emp) returning id into v_ret;
 for v in select * from jsonb_to_recordset(p_items) as x(ingredient_id bigint,quantity numeric,unit_code text) loop
   select coalesce(base_unit_code,unit),coalesce(purchase_unit_code,base_unit_code,unit) into v_base,v_unit from public.ingredients where id=v.ingredient_id and active is distinct from false;
   if not found then raise exception 'خامة غير صالحة %',v.ingredient_id; end if;
   v_unit:=coalesce(nullif(trim(coalesce(v.unit_code,'')),''),v_unit,v_base);v_qty:=round(coalesce(v.quantity,0)::numeric,6);
   if v_qty<=0 then raise exception 'كمية المرتجع غير صحيحة'; end if;
   v_factor:=public.ingredient_unit_factor_v1(v.ingredient_id,v_unit,v_base);if v_factor is null or v_factor<=0 then raise exception 'تحويل الوحدة غير صالح';end if;
   v_base_qty:=round(v_qty*v_factor,6);
   select * into v_stock from public.ingredient_stock where branch_id=p_branch_id and ingredient_id=v.ingredient_id for update;
   if not found or v_stock.quantity<v_base_qty then raise exception 'مخزون الخامة غير كافٍ للمرتجع'; end if;
   perform public.food_apply_ingredient_delta_internal_v1(p_branch_id,v.ingredient_id,-v_base_qty,v_stock.average_unit_cost,'supplier_return','food_supplier_return',v_ret,'مرتجع مورد خامات');
   insert into public.food_supplier_return_items(supplier_return_id,ingredient_id,quantity,unit_code,conversion_factor_to_base,base_quantity,unit_cost_snapshot)
   values(v_ret,v.ingredient_id,v_qty,v_unit,v_factor,v_base_qty,v_stock.average_unit_cost);
 end loop;
 insert into public.audit_logs(employee_id,branch_id,action,entity_type,entity_id,details)
 values(v_emp,p_branch_id,'food.purchasing.return','food_supplier_return',v_ret,jsonb_build_object('supplier_id',p_supplier_id,'client_tx_id',v_key));
 return v_ret;
end;$$;

-- -----------------------------------------------------------------------------
-- 7) Ingredient Stock Count
-- -----------------------------------------------------------------------------
create or replace function public.food_stock_count_post_v1(
 p_branch_id bigint,
 p_notes text,
 p_items jsonb,
 p_client_tx_id text
) returns bigint
language plpgsql security definer set search_path=public as $$
declare v_id bigint;v_emp bigint;v_key text:=nullif(trim(coalesce(p_client_tx_id,'')),'');v record;v_stock public.ingredient_stock%rowtype;v_count numeric(18,6);v_var numeric(18,6);
begin
 if auth.uid() is null then raise exception 'غير مصرح'; end if;
 if not public.has_action_permission_v2('food.stock_count.post') then raise exception 'ليس لديك صلاحية ترحيل جرد الخامات'; end if;
 if not public.has_branch_access(p_branch_id) then raise exception 'ليس لديك صلاحية لهذا الفرع'; end if;
 if v_key is null then raise exception 'معرف الحركة مطلوب'; end if;
 if jsonb_array_length(coalesce(p_items,'[]'::jsonb))=0 then raise exception 'لا توجد خامات للجرد'; end if;
 perform pg_advisory_xact_lock(hashtextextended('food-count:'||v_key,0));
 select id into v_id from public.food_stock_counts where client_tx_id=v_key;if v_id is not null then return v_id;end if;
 v_emp:=public.current_employee_id();

 -- Production preflight: validate every count line before the stock-count
 -- header becomes the first durable posting write.
 for v in
   select x.ingredient_id,round(coalesce(x.counted_quantity,-1)::numeric,6) counted_quantity
   from jsonb_to_recordset(p_items) with ordinality as x(ingredient_id bigint,counted_quantity numeric,ord bigint)
   order by x.ord
 loop
   if not exists(select 1 from public.ingredients where id=v.ingredient_id and active is distinct from false and track_inventory=true) then raise exception 'الخامة غير موجودة أو غير متتبعة %',v.ingredient_id; end if;
   if v.counted_quantity<0 then raise exception 'كمية الجرد لا يمكن أن تكون سالبة';end if;
 end loop;

 insert into public.food_stock_counts(branch_id,notes,client_tx_id,created_by_employee_id) values(p_branch_id,nullif(trim(coalesce(p_notes,'')),''),v_key,v_emp) returning id into v_id;
 for v in
   select x.ingredient_id,round(coalesce(x.counted_quantity,-1)::numeric,6) counted_quantity
   from jsonb_to_recordset(p_items) with ordinality as x(ingredient_id bigint,counted_quantity numeric,ord bigint)
   order by x.ord
 loop
   insert into public.ingredient_stock(branch_id,ingredient_id,quantity) values(p_branch_id,v.ingredient_id,0) on conflict(branch_id,ingredient_id) do nothing;
   select * into v_stock from public.ingredient_stock where branch_id=p_branch_id and ingredient_id=v.ingredient_id for update;
   v_count:=v.counted_quantity;
   v_var:=round(v_count-v_stock.quantity,6);
   if v_var<>0 then perform public.food_apply_ingredient_delta_internal_v1(p_branch_id,v.ingredient_id,v_var,null,'stock_count','food_stock_count',v_id,'تسوية جرد خامات'); end if;
   insert into public.food_stock_count_items(stock_count_id,ingredient_id,system_quantity,counted_quantity,variance,unit_cost_snapshot)
   values(v_id,v.ingredient_id,v_stock.quantity,v_count,v_var,v_stock.average_unit_cost);
 end loop;
 insert into public.audit_logs(employee_id,branch_id,action,entity_type,entity_id,details)
 values(v_emp,p_branch_id,'food.stock_count.post','food_stock_count',v_id,jsonb_build_object('client_tx_id',v_key));
 return v_id;
end;$$;

-- -----------------------------------------------------------------------------
-- 8) Ingredient branch-to-branch transfer (source deducts on send, destination on receive)
-- -----------------------------------------------------------------------------
create or replace function public.food_stock_transfer_create_v1(
 p_from_branch_id bigint,
 p_to_branch_id bigint,
 p_items jsonb,
 p_notes text,
 p_client_tx_id text
) returns bigint
language plpgsql security definer set search_path=public as $$
declare v_id bigint;v_emp bigint;v_key text:=nullif(trim(coalesce(p_client_tx_id,'')),'');v record;v_stock public.ingredient_stock%rowtype;v_qty numeric(18,6);
begin
 if auth.uid() is null then raise exception 'غير مصرح'; end if;
 if not public.has_action_permission_v2('food.transfer.create') then raise exception 'ليس لديك صلاحية إنشاء تحويل خامات'; end if;
 if p_from_branch_id=p_to_branch_id then raise exception 'اختر فرعين مختلفين'; end if;
 if not public.has_branch_access(p_from_branch_id) then raise exception 'ليس لديك صلاحية الفرع المصدر'; end if;
 if v_key is null then raise exception 'معرف الحركة مطلوب'; end if;
 if jsonb_array_length(coalesce(p_items,'[]'::jsonb))=0 then raise exception 'أضف خامة واحدة على الأقل'; end if;
 perform pg_advisory_xact_lock(hashtextextended('food-transfer:'||v_key,0));
 select id into v_id from public.stock_transfers where client_tx_id=v_key;if v_id is not null then return v_id;end if;
 v_emp:=public.current_employee_id();
 insert into public.stock_transfers(from_branch_id,to_branch_id,status,notes,client_tx_id,created_by_employee_id)
 values(p_from_branch_id,p_to_branch_id,'sent',nullif(trim(coalesce(p_notes,'')),''),v_key,v_emp) returning id into v_id;
 for v in select * from jsonb_to_recordset(p_items) as x(ingredient_id bigint,quantity numeric) loop
   v_qty:=round(coalesce(v.quantity,0)::numeric,6);if v_qty<=0 then raise exception 'كمية التحويل غير صحيحة';end if;
   select * into v_stock from public.ingredient_stock where branch_id=p_from_branch_id and ingredient_id=v.ingredient_id for update;
   if not found or v_stock.quantity<v_qty then raise exception 'المخزون غير كافٍ للخامة %',v.ingredient_id; end if;
   perform public.food_apply_ingredient_delta_internal_v1(p_from_branch_id,v.ingredient_id,-v_qty,v_stock.average_unit_cost,'transfer_out','stock_transfer',v_id,'تحويل خامات صادر');
   insert into public.stock_transfer_items(transfer_id,ingredient_id,quantity,unit_code,conversion_factor_to_base,base_quantity,unit_cost_snapshot)
   select v_id,v.ingredient_id,v_qty,coalesce(i.base_unit_code,i.unit),1,v_qty,v_stock.average_unit_cost from public.ingredients i where i.id=v.ingredient_id;
 end loop;
 insert into public.audit_logs(employee_id,branch_id,action,entity_type,entity_id,details)
 values(v_emp,p_from_branch_id,'food.transfer.create','stock_transfer',v_id,jsonb_build_object('to_branch_id',p_to_branch_id,'client_tx_id',v_key));
 return v_id;
end;$$;

create or replace function public.food_stock_transfer_receive_v1(p_transfer_id bigint) returns bigint
language plpgsql security definer set search_path=public as $$
declare v_t public.stock_transfers%rowtype;v_emp bigint;v record;
begin
 if auth.uid() is null then raise exception 'غير مصرح'; end if;
 if not public.has_action_permission_v2('food.transfer.receive') then raise exception 'ليس لديك صلاحية استلام تحويل خامات'; end if;
 select * into v_t from public.stock_transfers where id=p_transfer_id for update;
 if not found then raise exception 'التحويل غير موجود'; end if;
 if not public.has_branch_access(v_t.to_branch_id) then raise exception 'ليس لديك صلاحية الفرع المستلم'; end if;
 if v_t.status='received' then return v_t.id; end if;
 if v_t.status<>'sent' then raise exception 'التحويل غير قابل للاستلام'; end if;
 v_emp:=public.current_employee_id();
 for v in select * from public.stock_transfer_items where transfer_id=v_t.id order by id loop
   perform public.food_apply_ingredient_delta_internal_v1(v_t.to_branch_id,v.ingredient_id,coalesce(v.base_quantity,v.quantity),v.unit_cost_snapshot,'transfer_in','stock_transfer',v_t.id,'استلام تحويل خامات');
 end loop;
 update public.stock_transfers set status='received',received_by_employee_id=v_emp,received_at=now(),completed_at=now() where id=v_t.id;
 insert into public.audit_logs(employee_id,branch_id,action,entity_type,entity_id,details)
 values(v_emp,v_t.to_branch_id,'food.transfer.receive','stock_transfer',v_t.id,jsonb_build_object('from_branch_id',v_t.from_branch_id));
 return v_t.id;
end;$$;

create or replace function public.food_stock_transfer_cancel_v1(p_transfer_id bigint,p_reason text) returns bigint
language plpgsql security definer set search_path=public as $$
declare v_t public.stock_transfers%rowtype;v_emp bigint;v record;
begin
 if auth.uid() is null then raise exception 'غير مصرح'; end if;
 if not public.has_action_permission_v2('food.transfer.cancel') then raise exception 'ليس لديك صلاحية إلغاء تحويل خامات'; end if;
 select * into v_t from public.stock_transfers where id=p_transfer_id for update;
 if not found then raise exception 'التحويل غير موجود'; end if;
 if not public.has_branch_access(v_t.from_branch_id) then raise exception 'ليس لديك صلاحية الفرع المصدر'; end if;
 if v_t.status='cancelled' then return v_t.id; end if;
 if v_t.status<>'sent' then raise exception 'لا يمكن إلغاء التحويل بعد الاستلام'; end if;
 v_emp:=public.current_employee_id();
 for v in select * from public.stock_transfer_items where transfer_id=v_t.id order by id loop
   perform public.food_apply_ingredient_delta_internal_v1(v_t.from_branch_id,v.ingredient_id,coalesce(v.base_quantity,v.quantity),v.unit_cost_snapshot,'transfer_cancel','stock_transfer',v_t.id,'إلغاء تحويل خامات');
 end loop;
 update public.stock_transfers set status='cancelled',cancelled_by_employee_id=v_emp,cancelled_at=now(),notes=concat_ws(E'\n',notes,nullif(trim(coalesce(p_reason,'')),'')) where id=v_t.id;
 insert into public.audit_logs(employee_id,branch_id,action,entity_type,entity_id,details)
 values(v_emp,v_t.from_branch_id,'food.transfer.cancel','stock_transfer',v_t.id,jsonb_build_object('reason',p_reason));
 return v_t.id;
end;$$;

-- -----------------------------------------------------------------------------
-- 10) Execute grants for public runtime RPC surface
-- -----------------------------------------------------------------------------
revoke all on function public.food_supplier_save_v1(bigint,text,text,text,text,text,text,boolean) from public;
revoke all on function public.food_purchase_order_create_v1(bigint,bigint,text,text,jsonb,text) from public;
revoke all on function public.food_purchase_order_approve_v1(bigint) from public;
revoke all on function public.food_purchase_order_cancel_v1(bigint,text) from public;
revoke all on function public.food_purchase_receive_v1(bigint,jsonb,text) from public;
revoke all on function public.food_supplier_return_create_v1(bigint,bigint,text,jsonb,text) from public;
revoke all on function public.food_stock_count_post_v1(bigint,text,jsonb,text) from public;
revoke all on function public.food_stock_transfer_create_v1(bigint,bigint,jsonb,text,text) from public;
revoke all on function public.food_stock_transfer_receive_v1(bigint) from public;
revoke all on function public.food_stock_transfer_cancel_v1(bigint,text) from public;

grant execute on function public.food_supplier_save_v1(bigint,text,text,text,text,text,text,boolean) to authenticated;
grant execute on function public.food_purchase_order_create_v1(bigint,bigint,text,text,jsonb,text) to authenticated;
grant execute on function public.food_purchase_order_approve_v1(bigint) to authenticated;
grant execute on function public.food_purchase_order_cancel_v1(bigint,text) to authenticated;
grant execute on function public.food_purchase_receive_v1(bigint,jsonb,text) to authenticated;
grant execute on function public.food_supplier_return_create_v1(bigint,bigint,text,jsonb,text) to authenticated;
grant execute on function public.food_stock_count_post_v1(bigint,text,jsonb,text) to authenticated;
grant execute on function public.food_stock_transfer_create_v1(bigint,bigint,jsonb,text,text) to authenticated;
grant execute on function public.food_stock_transfer_receive_v1(bigint) to authenticated;
grant execute on function public.food_stock_transfer_cancel_v1(bigint,text) to authenticated;

commit;
