-- Sharawla POS — Purchasing Attachments / Supplier Invoice Archive V1
-- Additive, private-storage design. Intended for isolated Beta backend first.
begin;

insert into public.permission_actions_v2(code,name_ar,domain,legacy_permission,sort_order) values
 ('purchasing.attachments.view','عرض مرفقات وفواتير المشتريات','purchasing','inventory',1260),
 ('purchasing.attachments.upload','رفع مرفق أو فاتورة شراء','purchasing','inventory',1261),
 ('purchasing.attachments.delete','حذف مرفق شراء','purchasing','inventory',1262)
on conflict(code) do update set
 name_ar=excluded.name_ar,
 domain=excluded.domain,
 legacy_permission=excluded.legacy_permission,
 sort_order=excluded.sort_order,
 active=true;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values(
 'purchase-documents','purchase-documents',false,15728640,
 array['image/jpeg','image/png','image/webp','image/heic','image/heif','application/pdf']::text[]
)
on conflict(id) do update set
 public=false,
 file_size_limit=excluded.file_size_limit,
 allowed_mime_types=excluded.allowed_mime_types;

create table if not exists public.purchase_attachments(
 id bigint generated by default as identity primary key,
 branch_id bigint not null references public.branches(id),
 supplier_id bigint not null references public.retail_suppliers(id),
 supplier_invoice_id bigint references public.retail_supplier_invoices(id) on delete set null,
 purchase_order_id bigint references public.retail_purchase_orders(id) on delete set null,
 goods_receipt_id bigint references public.retail_goods_receipts(id) on delete set null,
 document_type text not null default 'supplier_invoice' check(document_type in ('supplier_invoice','receipt','delivery_note','payment_receipt','credit_note','other')),
 document_date date not null default current_date,
 reference_number text,
 note text,
 original_file_name text not null,
 storage_bucket text not null default 'purchase-documents' check(storage_bucket='purchase-documents'),
 storage_path text unique,
 mime_type text not null,
 file_size bigint not null check(file_size > 0 and file_size <= 15728640),
 status text not null default 'pending' check(status in ('pending','ready','failed')),
 uploaded_by_employee_id bigint references public.employees(id),
 uploaded_at timestamptz not null default now(),
 ready_at timestamptz,
 deleted_at timestamptz,
 deleted_by_employee_id bigint references public.employees(id),
 delete_reason text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create index if not exists purchase_attachments_branch_date_idx on public.purchase_attachments(branch_id,document_date desc,id desc);
create index if not exists purchase_attachments_supplier_date_idx on public.purchase_attachments(supplier_id,document_date desc,id desc);
create index if not exists purchase_attachments_invoice_idx on public.purchase_attachments(supplier_invoice_id) where supplier_invoice_id is not null;
create index if not exists purchase_attachments_status_idx on public.purchase_attachments(status,deleted_at);

alter table public.purchase_attachments enable row level security;

drop policy if exists purchase_attachments_read_v1 on public.purchase_attachments;
create policy purchase_attachments_read_v1 on public.purchase_attachments
for select to authenticated using(
 deleted_at is null
 and status='ready'
 and public.has_action_permission_v2('purchasing.attachments.view')
 and public.has_branch_access(branch_id)
);

grant select on public.purchase_attachments to authenticated;

-- Storage objects are private. Object names begin with branch_id/supplier_id/attachment_id/...
drop policy if exists purchase_documents_read_v1 on storage.objects;
create policy purchase_documents_read_v1 on storage.objects
for select to authenticated using(
 bucket_id='purchase-documents'
 and (storage.foldername(name))[1] ~ '^[0-9]+$'
 and public.has_action_permission_v2('purchasing.attachments.view')
 and public.has_branch_access(((storage.foldername(name))[1])::bigint)
);

drop policy if exists purchase_documents_upload_v1 on storage.objects;
create policy purchase_documents_upload_v1 on storage.objects
for insert to authenticated with check(
 bucket_id='purchase-documents'
 and (storage.foldername(name))[1] ~ '^[0-9]+$'
 and public.has_action_permission_v2('purchasing.attachments.upload')
 and public.has_branch_access(((storage.foldername(name))[1])::bigint)
);

create or replace function public.purchase_attachment_prepare_v1(
 p_branch_id bigint,
 p_supplier_id bigint,
 p_supplier_invoice_id bigint,
 p_document_type text,
 p_document_date date,
 p_reference_number text,
 p_note text,
 p_original_file_name text,
 p_mime_type text,
 p_file_size bigint
)
returns jsonb language plpgsql security definer set search_path=public,storage
as $$
declare
 e bigint; idv bigint; inv public.retail_supplier_invoices%rowtype; safe_name text; pathv text;
 allowed text[]:=array['image/jpeg','image/png','image/webp','image/heic','image/heif','application/pdf'];
begin
 if auth.uid() is null then raise exception 'غير مصرح'; end if;
 if not public.has_action_permission_v2('purchasing.attachments.upload') then raise exception 'ليس لديك صلاحية رفع مرفقات المشتريات'; end if;
 if not public.has_branch_access(p_branch_id) then raise exception 'ليس لديك صلاحية لهذا الفرع'; end if;
 if not exists(select 1 from public.retail_suppliers s where s.id=p_supplier_id and s.active=true) then raise exception 'المورد غير موجود أو غير فعال'; end if;
 if coalesce(p_document_type,'') not in ('supplier_invoice','receipt','delivery_note','payment_receipt','credit_note','other') then raise exception 'نوع المستند غير صحيح'; end if;
 if lower(coalesce(p_mime_type,'')) <> all(allowed) then raise exception 'نوع الملف غير مسموح'; end if;
 if coalesce(p_file_size,0)<=0 or p_file_size>15728640 then raise exception 'حجم الملف يجب ألا يتجاوز 15MB'; end if;
 if nullif(trim(coalesce(p_original_file_name,'')),'') is null then raise exception 'اسم الملف مطلوب'; end if;

 if p_supplier_invoice_id is not null then
   select * into inv from public.retail_supplier_invoices where id=p_supplier_invoice_id;
   if not found then raise exception 'فاتورة المورد غير موجودة'; end if;
   if inv.branch_id<>p_branch_id or inv.supplier_id<>p_supplier_id then raise exception 'الفاتورة لا تتطابق مع الفرع أو المورد'; end if;
 end if;

 e:=public.current_employee_id();
 insert into public.purchase_attachments(
   branch_id,supplier_id,supplier_invoice_id,purchase_order_id,document_type,document_date,reference_number,note,
   original_file_name,mime_type,file_size,status,uploaded_by_employee_id
 ) values(
   p_branch_id,p_supplier_id,p_supplier_invoice_id,case when p_supplier_invoice_id is null then null else inv.purchase_order_id end,
   p_document_type,coalesce(p_document_date,case when p_supplier_invoice_id is null then current_date else inv.invoice_date end,current_date),
   coalesce(nullif(trim(coalesce(p_reference_number,'')),''),case when p_supplier_invoice_id is null then null else inv.invoice_number end),
   nullif(trim(coalesce(p_note,'')),''),trim(p_original_file_name),lower(p_mime_type),p_file_size,'pending',e
 ) returning id into idv;

 safe_name:=regexp_replace(trim(p_original_file_name),'[^A-Za-z0-9._-]+','_','g');
 if safe_name='' then safe_name:='document'; end if;
 pathv:=p_branch_id::text||'/'||p_supplier_id::text||'/'||idv::text||'/'||safe_name;
 update public.purchase_attachments set storage_path=pathv,updated_at=now() where id=idv;

 insert into public.audit_logs(employee_id,branch_id,action,entity_type,entity_id,details)
 values(e,p_branch_id,'purchase_attachment_prepare','purchase_attachment',idv,
   jsonb_build_object('supplier_id',p_supplier_id,'supplier_invoice_id',p_supplier_invoice_id,'document_type',p_document_type,'document_date',coalesce(p_document_date,current_date),'file_name',p_original_file_name,'file_size',p_file_size));
 return jsonb_build_object('attachment_id',idv,'bucket','purchase-documents','path',pathv);
end;$$;

create or replace function public.purchase_attachment_finalize_v1(p_attachment_id bigint)
returns boolean language plpgsql security definer set search_path=public,storage
as $$
declare a public.purchase_attachments%rowtype;e bigint;begin
 if auth.uid() is null then raise exception 'غير مصرح';end if;
 if not public.has_action_permission_v2('purchasing.attachments.upload') then raise exception 'ليس لديك صلاحية رفع مرفقات المشتريات';end if;
 select * into a from public.purchase_attachments where id=p_attachment_id for update;
 if not found or a.deleted_at is not null then raise exception 'المرفق غير موجود';end if;
 if not public.has_branch_access(a.branch_id) then raise exception 'ليس لديك صلاحية لهذا الفرع';end if;
 if a.status='ready' then return true;end if;
 if not exists(select 1 from storage.objects o where o.bucket_id=a.storage_bucket and o.name=a.storage_path) then raise exception 'لم يتم العثور على الملف المرفوع';end if;
 e:=public.current_employee_id();
 update public.purchase_attachments set status='ready',ready_at=now(),updated_at=now() where id=a.id;
 insert into public.audit_logs(employee_id,branch_id,action,entity_type,entity_id,details)
 values(e,a.branch_id,'purchase_attachment_finalize','purchase_attachment',a.id,jsonb_build_object('storage_path',a.storage_path,'supplier_id',a.supplier_id));
 return true;
end;$$;

create or replace function public.purchase_attachment_abort_v1(p_attachment_id bigint,p_reason text default null)
returns boolean language plpgsql security definer set search_path=public,storage
as $$
declare a public.purchase_attachments%rowtype;e bigint;begin
 if auth.uid() is null then raise exception 'غير مصرح';end if;
 e:=public.current_employee_id();
 select * into a from public.purchase_attachments where id=p_attachment_id for update;
 if not found then return true;end if;
 if a.status='ready' then raise exception 'لا يمكن إلغاء مرفق مكتمل';end if;
 if a.uploaded_by_employee_id is distinct from e and not public.has_action_permission_v2('purchasing.attachments.delete') then raise exception 'ليس لديك صلاحية إلغاء هذا المرفق';end if;
 if not public.has_branch_access(a.branch_id) then raise exception 'ليس لديك صلاحية لهذا الفرع';end if;
 delete from storage.objects where bucket_id=a.storage_bucket and name=a.storage_path;
 update public.purchase_attachments set status='failed',note=concat_ws(E'\n',note,nullif(trim(coalesce(p_reason,'')),'')),updated_at=now() where id=a.id;
 return true;
end;$$;

create or replace function public.purchase_attachment_soft_delete_v1(p_attachment_id bigint,p_reason text)
returns boolean language plpgsql security definer set search_path=public
as $$
declare a public.purchase_attachments%rowtype;e bigint;begin
 if auth.uid() is null then raise exception 'غير مصرح';end if;
 if not public.has_action_permission_v2('purchasing.attachments.delete') then raise exception 'ليس لديك صلاحية حذف مرفقات المشتريات';end if;
 select * into a from public.purchase_attachments where id=p_attachment_id for update;
 if not found then raise exception 'المرفق غير موجود';end if;
 if not public.has_branch_access(a.branch_id) then raise exception 'ليس لديك صلاحية لهذا الفرع';end if;
 if a.deleted_at is not null then return true;end if;
 e:=public.current_employee_id();
 update public.purchase_attachments set deleted_at=now(),deleted_by_employee_id=e,delete_reason=nullif(trim(coalesce(p_reason,'')),''),updated_at=now() where id=a.id;
 insert into public.audit_logs(employee_id,branch_id,action,entity_type,entity_id,details)
 values(e,a.branch_id,'purchase_attachment_soft_delete','purchase_attachment',a.id,jsonb_build_object('supplier_id',a.supplier_id,'reason',p_reason,'storage_path',a.storage_path));
 return true;
end;$$;

create or replace function public.purchase_attachment_list_v1(
 p_branch_id bigint,
 p_supplier_id bigint default null,
 p_from date default null,
 p_to date default null,
 p_search text default null
)
returns table(
 id bigint,branch_id bigint,supplier_id bigint,supplier_name text,supplier_invoice_id bigint,invoice_number text,
 document_type text,document_date date,reference_number text,note text,original_file_name text,mime_type text,file_size bigint,
 storage_bucket text,storage_path text,uploaded_at timestamptz,uploaded_by_employee_id bigint
) language plpgsql security definer set search_path=public
as $$
begin
 if auth.uid() is null then raise exception 'غير مصرح';end if;
 if not public.has_action_permission_v2('purchasing.attachments.view') then raise exception 'ليس لديك صلاحية عرض مرفقات المشتريات';end if;
 if not public.has_branch_access(p_branch_id) then raise exception 'ليس لديك صلاحية لهذا الفرع';end if;
 return query
 select a.id,a.branch_id,a.supplier_id,s.name,a.supplier_invoice_id,i.invoice_number,
        a.document_type,a.document_date,a.reference_number,a.note,a.original_file_name,a.mime_type,a.file_size,
        a.storage_bucket,a.storage_path,a.uploaded_at,a.uploaded_by_employee_id
 from public.purchase_attachments a
 join public.retail_suppliers s on s.id=a.supplier_id
 left join public.retail_supplier_invoices i on i.id=a.supplier_invoice_id
 where a.branch_id=p_branch_id
   and a.status='ready' and a.deleted_at is null
   and (p_supplier_id is null or a.supplier_id=p_supplier_id)
   and (p_from is null or a.document_date>=p_from)
   and (p_to is null or a.document_date<=p_to)
   and (nullif(trim(coalesce(p_search,'')),'') is null
        or coalesce(a.reference_number,'') ilike '%'||trim(p_search)||'%'
        or coalesce(i.invoice_number,'') ilike '%'||trim(p_search)||'%'
        or coalesce(a.original_file_name,'') ilike '%'||trim(p_search)||'%'
        or coalesce(s.name,'') ilike '%'||trim(p_search)||'%')
 order by a.document_date desc,a.id desc;
end;$$;

grant execute on function public.purchase_attachment_prepare_v1(bigint,bigint,bigint,text,date,text,text,text,text,bigint) to authenticated;
grant execute on function public.purchase_attachment_finalize_v1(bigint) to authenticated;
grant execute on function public.purchase_attachment_abort_v1(bigint,text) to authenticated;
grant execute on function public.purchase_attachment_soft_delete_v1(bigint,text) to authenticated;
grant execute on function public.purchase_attachment_list_v1(bigint,bigint,date,date,text) to authenticated;

commit;
