-- V9.4.0 - Numbering + dynamic payments + discount/tax/service
-- Run once after V9.3.2. Safe to re-run.

alter table public.orders add column if not exists invoice_number bigint;
alter table public.orders add column if not exists bon_number integer;
alter table public.orders add column if not exists discount_type text;
alter table public.orders add column if not exists discount_value numeric(12,2) not null default 0;
alter table public.orders add column if not exists tax_amount numeric(12,2) not null default 0;
alter table public.orders add column if not exists service_amount numeric(12,2) not null default 0;

-- Backfill old invoice numbers per branch in chronological order.
with ranked as (
  select id, row_number() over(partition by branch_id order by created_at,id) as rn
  from public.orders
  where invoice_number is null
)
update public.orders o set invoice_number=r.rn
from ranked r where r.id=o.id;

-- Backfill old bon numbers only for orders that already belong to a shift.
with ranked as (
  select id, row_number() over(partition by shift_id order by created_at,id) as rn
  from public.orders
  where shift_id is not null and bon_number is null
)
update public.orders o set bon_number=r.rn
from ranked r where r.id=o.id;

create unique index if not exists orders_branch_invoice_unique
on public.orders(branch_id,invoice_number) where invoice_number is not null;
create unique index if not exists orders_shift_bon_unique
on public.orders(shift_id,bon_number) where shift_id is not null and bon_number is not null;

create table if not exists public.branch_invoice_counters(
  branch_id bigint primary key references public.branches(id) on delete cascade,
  next_number bigint not null default 1 check(next_number>=1)
);
insert into public.branch_invoice_counters(branch_id,next_number)
select b.id,coalesce(max(o.invoice_number),0)+1
from public.branches b left join public.orders o on o.branch_id=b.id
group by b.id
on conflict(branch_id) do update set next_number=greatest(public.branch_invoice_counters.next_number,excluded.next_number);

create table if not exists public.shift_bon_counters(
  shift_id bigint primary key references public.shifts(id) on delete cascade,
  branch_id bigint not null references public.branches(id) on delete cascade,
  next_number integer not null default 1 check(next_number>=1)
);
insert into public.shift_bon_counters(shift_id,branch_id,next_number)
select s.id,s.branch_id,coalesce(max(o.bon_number),0)+1
from public.shifts s left join public.orders o on o.shift_id=s.id
group by s.id,s.branch_id
on conflict(shift_id) do update set next_number=greatest(public.shift_bon_counters.next_number,excluded.next_number);

create or replace function public.assign_order_numbers()
returns trigger language plpgsql security definer set search_path=public as $$
declare v bigint;
begin
  -- Website acceptance and any other branch sale: attach to the employee's open shift when possible.
  if new.shift_id is null and new.employee_id is not null then
    select s.id into new.shift_id
    from public.shifts s
    where s.branch_id=new.branch_id and s.employee_id=new.employee_id and s.status='open' and s.closed_at is null
    order by s.opened_at desc limit 1;
  end if;

  if new.invoice_number is null then
    insert into public.branch_invoice_counters(branch_id,next_number)
    values(new.branch_id,2)
    on conflict(branch_id) do update set next_number=public.branch_invoice_counters.next_number+1
    returning next_number-1 into v;
    new.invoice_number:=v;
  end if;

  if new.shift_id is not null and new.bon_number is null then
    insert into public.shift_bon_counters(shift_id,branch_id,next_number)
    values(new.shift_id,new.branch_id,2)
    on conflict(shift_id) do update set next_number=public.shift_bon_counters.next_number+1
    returning next_number-1 into v;
    new.bon_number:=v::integer;
  end if;
  return new;
end $$;

drop trigger if exists trg_assign_order_numbers on public.orders;
create trigger trg_assign_order_numbers before insert on public.orders
for each row execute function public.assign_order_numbers();

create table if not exists public.payment_methods(
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  kind text not null default 'other' check(kind in ('cash','card','wallet','other')),
  active boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now()
);
insert into public.payment_methods(code,name,kind,sort_order) values
('cash','كاش','cash',10),('wallet','محفظة','wallet',20),('instapay','InstaPay','wallet',30),('visa','Visa / Card','card',40)
on conflict(code) do nothing;

create table if not exists public.branch_payment_methods(
  branch_id bigint not null references public.branches(id) on delete cascade,
  payment_method_id bigint not null references public.payment_methods(id) on delete cascade,
  active boolean not null default true,
  is_default boolean not null default false,
  primary key(branch_id,payment_method_id)
);
insert into public.branch_payment_methods(branch_id,payment_method_id,active,is_default)
select b.id,p.id,true,(p.code='cash') from public.branches b cross join public.payment_methods p
on conflict(branch_id,payment_method_id) do nothing;

create table if not exists public.branch_financial_settings(
  branch_id bigint primary key references public.branches(id) on delete cascade,
  discount_enabled boolean not null default true,
  discount_mode text not null default 'both' check(discount_mode in ('amount','percent','both')),
  max_discount_percent numeric(6,2) not null default 100 check(max_discount_percent between 0 and 100),
  tax_enabled boolean not null default false,
  tax_rate numeric(6,3) not null default 0 check(tax_rate between 0 and 100),
  prices_include_tax boolean not null default true,
  service_enabled boolean not null default false,
  service_rate numeric(6,3) not null default 0 check(service_rate between 0 and 100),
  updated_at timestamptz not null default now()
);
insert into public.branch_financial_settings(branch_id)
select id from public.branches on conflict(branch_id) do nothing;

alter table public.payment_methods enable row level security;
alter table public.branch_payment_methods enable row level security;
alter table public.branch_financial_settings enable row level security;

grant select on public.payment_methods,public.branch_payment_methods,public.branch_financial_settings to authenticated;
grant select on public.branch_financial_settings to anon;
grant insert,update on public.payment_methods,public.branch_payment_methods,public.branch_financial_settings to authenticated;
grant usage,select on sequence public.payment_methods_id_seq to authenticated;

drop policy if exists payment_methods_staff_read on public.payment_methods;
create policy payment_methods_staff_read on public.payment_methods for select to authenticated using(true);
drop policy if exists payment_methods_staff_write on public.payment_methods;
create policy payment_methods_staff_write on public.payment_methods for all to authenticated
using(public.is_admin() or public.has_permission('financialSettings'))
with check(public.is_admin() or public.has_permission('financialSettings'));

drop policy if exists branch_payment_methods_read on public.branch_payment_methods;
create policy branch_payment_methods_read on public.branch_payment_methods for select to authenticated
using(public.is_admin() or public.has_branch_access(branch_id));
drop policy if exists branch_payment_methods_write on public.branch_payment_methods;
create policy branch_payment_methods_write on public.branch_payment_methods for all to authenticated
using((public.is_admin() or public.has_permission('financialSettings')) and public.has_branch_access(branch_id))
with check((public.is_admin() or public.has_permission('financialSettings')) and public.has_branch_access(branch_id));

drop policy if exists branch_financial_settings_read_staff on public.branch_financial_settings;
create policy branch_financial_settings_read_staff on public.branch_financial_settings for select to authenticated
using(public.is_admin() or public.has_branch_access(branch_id));
drop policy if exists branch_financial_settings_read_web on public.branch_financial_settings;
create policy branch_financial_settings_read_web on public.branch_financial_settings for select to anon using(true);
drop policy if exists branch_financial_settings_write on public.branch_financial_settings;
create policy branch_financial_settings_write on public.branch_financial_settings for all to authenticated
using((public.is_admin() or public.has_permission('financialSettings')) and public.has_branch_access(branch_id))
with check((public.is_admin() or public.has_permission('financialSettings')) and public.has_branch_access(branch_id));

notify pgrst,'reload schema';
