-- V10.5.6 Return Approval V1
-- Source-first. Designed to be applied to Beta before any Production rollout.
-- Cashier prepares the return on the cashier's open shift; an authorized manager
-- can approve/reject from another logged-in Sharawla session without opening a shift.

begin;

alter table public.returns
  add column if not exists approved_by_employee_id bigint references public.employees(id) on delete set null,
  add column if not exists approval_request_id bigint;

create table if not exists public.return_approval_requests(
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id) on delete restrict,
  order_id bigint not null references public.orders(id) on delete restrict,
  requester_employee_id bigint not null references public.employees(id) on delete restrict,
  requester_shift_id bigint not null references public.shifts(id) on delete restrict,
  requester_name text not null,
  order_bon_number bigint,
  order_invoice_number bigint,
  reason text not null,
  notes text,
  items jsonb not null,
  payments jsonb not null,
  expected_total numeric(12,2) not null check(expected_total >= 0),
  status text not null default 'pending' check(status in ('pending','approved','rejected','expired')),
  client_tx_id text not null,
  request_digest text not null,
  expires_at timestamptz not null,
  approver_employee_id bigint references public.employees(id) on delete set null,
  decision_at timestamptz,
  decision_note text,
  decision_client_tx_id text,
  decision_digest text,
  return_id bigint references public.returns(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(client_tx_id)
);

create unique index if not exists return_approval_requests_decision_tx_uidx
  on public.return_approval_requests(decision_client_tx_id)
  where decision_client_tx_id is not null;

create index if not exists return_approval_requests_pending_idx
  on public.return_approval_requests(branch_id,status,expires_at,created_at desc);

create index if not exists return_approval_requests_requester_idx
  on public.return_approval_requests(requester_employee_id,created_at desc);

-- One approval request can create at most one financial return.
create unique index if not exists returns_approval_request_uidx
  on public.returns(approval_request_id)
  where approval_request_id is not null;

do $constraint$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname='returns_approval_request_fk'
      and conrelid='public.returns'::regclass
  ) then
    alter table public.returns
      add constraint returns_approval_request_fk
      foreign key (approval_request_id)
      references public.return_approval_requests(id)
      on delete set null;
  end if;
end
$constraint$;

alter table public.return_approval_requests enable row level security;

grant select on public.return_approval_requests to authenticated;
grant usage,select on sequence public.return_approval_requests_id_seq to authenticated;

drop policy if exists return_approval_requests_read on public.return_approval_requests;
create policy return_approval_requests_read
on public.return_approval_requests
for select
to authenticated
using(
  requester_employee_id = public.current_employee_id()
  or (
    public.has_branch_access(branch_id)
    and (public.is_admin() or public.has_permission('returnApprovals'))
  )
);

-- Canonical server-side validation/calculation shared by request and approval.
create or replace function public.return_approval_validate_v1(
  p_order_id bigint,
  p_items jsonb,
  p_payments jsonb
) returns numeric
language plpgsql
security definer
set search_path=public
as $$
declare
  v_order public.orders%rowtype;
  v_item jsonb;
  v_oi public.order_items%rowtype;
  v_qty numeric(12,3);
  v_prev numeric(12,3);
  v_line numeric(12,2);
  v_sub numeric(12,2):=0;
  v_ratio numeric(18,8):=0;
  v_discount numeric(12,2):=0;
  v_tax numeric(12,2):=0;
  v_service numeric(12,2):=0;
  v_total numeric(12,2):=0;
  v_pay jsonb;
  v_method text;
  v_amount numeric(12,2);
  v_pay_total numeric(12,2):=0;
begin
  select * into v_order from public.orders where id=p_order_id for update;
  if not found then raise exception 'الفاتورة غير موجودة'; end if;
  if v_order.status='cancelled' then raise exception 'لا يمكن عمل مرتجع لفاتورة ملغية'; end if;
  if p_items is null or jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then
    raise exception 'اختر صنفًا واحدًا على الأقل';
  end if;

  for v_item in select * from jsonb_array_elements(p_items) loop
    select * into v_oi
    from public.order_items
    where id=(v_item->>'order_item_id')::bigint
      and order_id=v_order.id;
    if not found then raise exception 'صنف المرتجع غير موجود بالفاتورة'; end if;

    v_qty:=coalesce((v_item->>'quantity')::numeric,0);
    if v_qty<=0 then raise exception 'كمية المرتجع غير صحيحة'; end if;

    select coalesce(sum(ri.quantity),0) into v_prev
    from public.return_items ri
    join public.returns r on r.id=ri.return_id
    where r.order_id=v_order.id
      and ri.order_item_id=v_oi.id;

    if v_qty+v_prev>v_oi.quantity then
      raise exception 'كمية المرتجع أكبر من الكمية المتاحة للصنف %',v_oi.product_name;
    end if;

    v_line:=round((coalesce(v_oi.total,0)/nullif(v_oi.quantity,0))*v_qty,2);
    v_sub:=v_sub+v_line;
  end loop;

  if coalesce(v_order.subtotal,0)>0 then
    v_ratio:=least(1,v_sub/v_order.subtotal);
  end if;

  v_discount:=round(coalesce(v_order.discount,0)*v_ratio,2);
  v_tax:=round(coalesce(v_order.tax_amount,0)*v_ratio,2);
  v_service:=round(coalesce(v_order.service_amount,0)*v_ratio,2);
  v_total:=greatest(0,round(v_sub-v_discount+v_tax+v_service,2));

  if p_payments is null or jsonb_typeof(p_payments)<>'array' or jsonb_array_length(p_payments)=0 then
    raise exception 'حدد طريقة رد المبلغ';
  end if;

  for v_pay in select * from jsonb_array_elements(p_payments) loop
    v_method:=nullif(trim(v_pay->>'method'),'');
    v_amount:=coalesce((v_pay->>'amount')::numeric,0);
    if v_method is null or v_amount<=0 then
      raise exception 'بيانات رد المبلغ غير صحيحة';
    end if;

    if not exists(
      select 1
      from public.payment_methods pm
      join public.branch_payment_methods bpm on bpm.payment_method_id=pm.id
      where pm.code=v_method
        and pm.active=true
        and bpm.branch_id=v_order.branch_id
        and bpm.active=true
    ) then
      raise exception 'طريقة رد المبلغ غير متاحة للفرع';
    end if;

    v_pay_total:=v_pay_total+v_amount;
  end loop;

  if abs(v_pay_total-v_total)>0.01 then
    raise exception 'إجمالي رد المبلغ يجب أن يساوي %',v_total;
  end if;

  return v_total;
end;
$$;

revoke all on function public.return_approval_validate_v1(bigint,jsonb,jsonb) from public;

-- Internal writer. It records the return against the REQUESTER and REQUESTER SHIFT,
-- never against the approving manager.
create or replace function public.create_approved_order_return_v1(
  p_order_id bigint,
  p_reason text,
  p_notes text,
  p_items jsonb,
  p_payments jsonb,
  p_requester_employee_id bigint,
  p_requester_shift_id bigint,
  p_approver_employee_id bigint,
  p_approval_request_id bigint
) returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare
  v_order public.orders%rowtype;
  v_return_id bigint;
  v_return_no bigint;
  v_item jsonb;
  v_oi public.order_items%rowtype;
  v_qty numeric(12,3);
  v_line numeric(12,2);
  v_sub numeric(12,2):=0;
  v_ratio numeric(18,8):=0;
  v_discount numeric(12,2):=0;
  v_tax numeric(12,2):=0;
  v_service numeric(12,2):=0;
  v_total numeric(12,2):=0;
  v_pay jsonb;
begin
  if nullif(trim(coalesce(p_reason,'')),'') is null then
    raise exception 'سبب المرتجع مطلوب';
  end if;

  select * into v_order from public.orders where id=p_order_id for update;
  if not found then raise exception 'الفاتورة غير موجودة'; end if;
  if v_order.status='cancelled' then raise exception 'لا يمكن عمل مرتجع لفاتورة ملغية'; end if;

  if not exists(
    select 1
    from public.shifts s
    where s.id=p_requester_shift_id
      and s.employee_id=p_requester_employee_id
      and s.branch_id=v_order.branch_id
      and s.status='open'
      and s.closed_at is null
  ) then
    raise exception 'وردية الموظف لم تعد مفتوحة';
  end if;

  if not exists(
    select 1
    from public.employees e
    where e.id=p_requester_employee_id
      and coalesce(e.active,true)=true
      and (
        e.role='admin'
        or e.branch_id=v_order.branch_id
        or exists(
          select 1 from public.employee_branches eb
          where eb.employee_id=e.id and eb.branch_id=v_order.branch_id
        )
      )
  ) then
    raise exception 'الموظف لم يعد مصرحًا له على هذا الفرع';
  end if;

  v_total:=public.return_approval_validate_v1(p_order_id,p_items,p_payments);

  for v_item in select * from jsonb_array_elements(p_items) loop
    select * into v_oi
    from public.order_items
    where id=(v_item->>'order_item_id')::bigint
      and order_id=v_order.id;
    v_qty:=(v_item->>'quantity')::numeric;
    v_line:=round((coalesce(v_oi.total,0)/nullif(v_oi.quantity,0))*v_qty,2);
    v_sub:=v_sub+v_line;
  end loop;

  if coalesce(v_order.subtotal,0)>0 then
    v_ratio:=least(1,v_sub/v_order.subtotal);
  end if;
  v_discount:=round(coalesce(v_order.discount,0)*v_ratio,2);
  v_tax:=round(coalesce(v_order.tax_amount,0)*v_ratio,2);
  v_service:=round(coalesce(v_order.service_amount,0)*v_ratio,2);

  insert into public.branch_return_counters(branch_id,next_number)
  values(v_order.branch_id,2)
  on conflict(branch_id) do update
    set next_number=public.branch_return_counters.next_number+1
  returning next_number-1 into v_return_no;

  insert into public.returns(
    branch_id,return_number,order_id,original_invoice_number,original_bon_number,
    employee_id,shift_id,reason,notes,subtotal,discount_adjustment,tax_adjustment,
    service_adjustment,total,approved_by_employee_id,approval_request_id
  ) values(
    v_order.branch_id,v_return_no,v_order.id,v_order.invoice_number,v_order.bon_number,
    p_requester_employee_id,p_requester_shift_id,trim(p_reason),
    nullif(trim(coalesce(p_notes,'')),''),v_sub,v_discount,v_tax,v_service,v_total,
    p_approver_employee_id,p_approval_request_id
  )
  returning id into v_return_id;

  for v_item in select * from jsonb_array_elements(p_items) loop
    select * into v_oi
    from public.order_items
    where id=(v_item->>'order_item_id')::bigint
      and order_id=v_order.id;
    v_qty:=(v_item->>'quantity')::numeric;
    v_line:=round((coalesce(v_oi.total,0)/nullif(v_oi.quantity,0))*v_qty,2);

    insert into public.return_items(
      return_id,order_item_id,product_id,product_name,quantity,unit_refund,total
    ) values(
      v_return_id,v_oi.id,v_oi.product_id,v_oi.product_name,v_qty,
      round(v_line/v_qty,2),v_line
    );
  end loop;

  for v_pay in select * from jsonb_array_elements(p_payments) loop
    insert into public.return_payments(return_id,method,amount)
    values(v_return_id,trim(v_pay->>'method'),(v_pay->>'amount')::numeric);
  end loop;

  return v_return_id;
end;
$$;

revoke all on function public.create_approved_order_return_v1(bigint,text,text,jsonb,jsonb,bigint,bigint,bigint,bigint) from public;

create or replace function public.request_order_return_approval_v1(
  p_order_id bigint,
  p_reason text,
  p_notes text,
  p_items jsonb,
  p_payments jsonb,
  p_client_tx_id text
) returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_emp bigint;
  v_emp_name text;
  v_order public.orders%rowtype;
  v_shift bigint;
  v_total numeric(12,2);
  v_key text:=nullif(trim(coalesce(p_client_tx_id,'')),'');
  v_digest text;
  v_existing public.return_approval_requests%rowtype;
  v_id bigint;
  v_expires timestamptz:=now()+interval '5 minutes';
begin
  if auth.uid() is null then raise exception 'غير مصرح'; end if;
  if v_key is null then raise exception 'معرف الحركة مطلوب'; end if;
  if nullif(trim(coalesce(p_reason,'')),'') is null then raise exception 'سبب المرتجع مطلوب'; end if;

  v_emp:=public.current_employee_id();
  if v_emp is null then raise exception 'المستخدم غير مربوط بموظف'; end if;
  select name into v_emp_name from public.employees where id=v_emp;

  select * into v_order from public.orders where id=p_order_id for update;
  if not found then raise exception 'الفاتورة غير موجودة'; end if;
  if not public.has_branch_access(v_order.branch_id) then
    raise exception 'ليس لديك صلاحية لهذا الفرع';
  end if;

  select id into v_shift
  from public.shifts
  where branch_id=v_order.branch_id
    and employee_id=v_emp
    and status='open'
    and closed_at is null
  order by opened_at desc
  limit 1;
  if v_shift is null then raise exception 'افتح وردية أولًا قبل طلب المرتجع'; end if;

  v_digest:=md5(jsonb_build_object(
    'employee_id',v_emp,
    'shift_id',v_shift,
    'order_id',p_order_id,
    'reason',trim(p_reason),
    'notes',coalesce(nullif(trim(coalesce(p_notes,'')),''),''),
    'items',coalesce(p_items,'[]'::jsonb),
    'payments',coalesce(p_payments,'[]'::jsonb)
  )::text);

  perform pg_advisory_xact_lock(hashtextextended('return-approval-request:'||v_key,0));

  select * into v_existing
  from public.return_approval_requests
  where client_tx_id=v_key
  limit 1;

  if found then
    if v_existing.request_digest<>v_digest then
      raise exception 'تم استخدام معرف الطلب نفسه ببيانات مختلفة';
    end if;
    return jsonb_build_object(
      'request_id',v_existing.id,
      'status',v_existing.status,
      'expected_total',v_existing.expected_total,
      'expires_at',v_existing.expires_at,
      'return_id',v_existing.return_id
    );
  end if;

  v_total:=public.return_approval_validate_v1(p_order_id,p_items,p_payments);

  insert into public.return_approval_requests(
    branch_id,order_id,requester_employee_id,requester_shift_id,requester_name,
    order_bon_number,order_invoice_number,reason,notes,items,payments,expected_total,
    client_tx_id,request_digest,expires_at
  ) values(
    v_order.branch_id,v_order.id,v_emp,v_shift,coalesce(v_emp_name,'موظف'),
    v_order.bon_number,v_order.invoice_number,trim(p_reason),
    nullif(trim(coalesce(p_notes,'')),''),p_items,p_payments,v_total,
    v_key,v_digest,v_expires
  )
  returning id into v_id;

  insert into public.audit_logs(employee_id,branch_id,action,entity_type,entity_id,details)
  values(
    v_emp,v_order.branch_id,'return_approval_requested','return_approval_request',v_id,
    jsonb_build_object('order_id',v_order.id,'shift_id',v_shift,'expected_total',v_total)
  );

  return jsonb_build_object(
    'request_id',v_id,
    'status','pending',
    'expected_total',v_total,
    'expires_at',v_expires,
    'return_id',null
  );
end;
$$;

revoke all on function public.request_order_return_approval_v1(bigint,text,text,jsonb,jsonb,text) from public;
grant execute on function public.request_order_return_approval_v1(bigint,text,text,jsonb,jsonb,text) to authenticated;

create or replace function public.decide_order_return_approval_v1(
  p_request_id bigint,
  p_decision text,
  p_note text,
  p_client_tx_id text
) returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_emp bigint;
  v_req public.return_approval_requests%rowtype;
  v_decision text:=lower(trim(coalesce(p_decision,'')));
  v_key text:=nullif(trim(coalesce(p_client_tx_id,'')),'');
  v_digest text;
  v_return_id bigint;
  v_total numeric(12,2);
begin
  if auth.uid() is null then raise exception 'غير مصرح'; end if;
  if v_key is null then raise exception 'معرف القرار مطلوب'; end if;
  if v_decision not in ('approve','reject') then raise exception 'قرار غير صحيح'; end if;

  v_emp:=public.current_employee_id();
  if v_emp is null then raise exception 'المستخدم غير مربوط بموظف'; end if;

  perform pg_advisory_xact_lock(hashtextextended('return-approval-decision:'||p_request_id::text,0));
  perform pg_advisory_xact_lock(hashtextextended('return-approval-decision-tx:'||v_key,0));

  select * into v_req
  from public.return_approval_requests
  where id=p_request_id
  for update;
  if not found then raise exception 'طلب الاعتماد غير موجود'; end if;

  if not public.has_branch_access(v_req.branch_id)
     or not (public.is_admin() or public.has_permission('returnApprovals')) then
    raise exception 'ليس لديك صلاحية اعتماد المرتجعات لهذا الفرع';
  end if;

  v_digest:=md5(jsonb_build_object(
    'request_id',p_request_id,
    'decision',v_decision,
    'note',coalesce(nullif(trim(coalesce(p_note,'')),''),'')
  )::text);

  if v_req.decision_client_tx_id=v_key and v_req.decision_digest is distinct from v_digest then
    raise exception 'تم استخدام معرف القرار نفسه ببيانات مختلفة';
  end if;

  if v_req.status<>'pending' then
    return jsonb_build_object(
      'request_id',v_req.id,
      'status',v_req.status,
      'return_id',v_req.return_id,
      'approver_employee_id',v_req.approver_employee_id,
      'decision_at',v_req.decision_at
    );
  end if;

  if now()>v_req.expires_at then
    update public.return_approval_requests
      set status='expired',updated_at=now()
    where id=v_req.id;

    return jsonb_build_object(
      'request_id',v_req.id,
      'status','expired',
      'return_id',null
    );
  end if;

  if v_decision='reject' then
    update public.return_approval_requests
      set status='rejected',
          approver_employee_id=v_emp,
          decision_at=now(),
          decision_note=nullif(trim(coalesce(p_note,'')),''),
          decision_client_tx_id=v_key,
          decision_digest=v_digest,
          updated_at=now()
    where id=v_req.id;

    insert into public.audit_logs(employee_id,branch_id,action,entity_type,entity_id,details)
    values(
      v_emp,v_req.branch_id,'return_approval_rejected','return_approval_request',v_req.id,
      jsonb_build_object('order_id',v_req.order_id,'requester_employee_id',v_req.requester_employee_id)
    );

    return jsonb_build_object(
      'request_id',v_req.id,
      'status','rejected',
      'return_id',null,
      'approver_employee_id',v_emp
    );
  end if;

  if not exists(
    select 1
    from public.shifts s
    where s.id=v_req.requester_shift_id
      and s.employee_id=v_req.requester_employee_id
      and s.branch_id=v_req.branch_id
      and s.status='open'
      and s.closed_at is null
  ) then
    raise exception 'وردية الموظف لم تعد مفتوحة';
  end if;

  v_total:=public.return_approval_validate_v1(v_req.order_id,v_req.items,v_req.payments);
  if abs(v_total-v_req.expected_total)>0.01 then
    raise exception 'قيمة المرتجع تغيرت منذ إنشاء طلب الاعتماد';
  end if;

  v_return_id:=public.create_approved_order_return_v1(
    v_req.order_id,v_req.reason,v_req.notes,v_req.items,v_req.payments,
    v_req.requester_employee_id,v_req.requester_shift_id,v_emp,v_req.id
  );

  update public.return_approval_requests
    set status='approved',
        approver_employee_id=v_emp,
        decision_at=now(),
        decision_note=nullif(trim(coalesce(p_note,'')),''),
        decision_client_tx_id=v_key,
        decision_digest=v_digest,
        return_id=v_return_id,
        updated_at=now()
  where id=v_req.id;

  insert into public.audit_logs(employee_id,branch_id,action,entity_type,entity_id,details)
  values(
    v_emp,v_req.branch_id,'return_approval_approved','return_approval_request',v_req.id,
    jsonb_build_object(
      'order_id',v_req.order_id,
      'requester_employee_id',v_req.requester_employee_id,
      'requester_shift_id',v_req.requester_shift_id,
      'return_id',v_return_id,
      'total',v_total
    )
  );

  return jsonb_build_object(
    'request_id',v_req.id,
    'status','approved',
    'return_id',v_return_id,
    'approver_employee_id',v_emp
  );
end;
$$;

revoke all on function public.decide_order_return_approval_v1(bigint,text,text,text) from public;
grant execute on function public.decide_order_return_approval_v1(bigint,text,text,text) to authenticated;

notify pgrst,'reload schema';

commit;
