-- Sharawla POS — Point 4D-1 Purchasing/AP source-only contract.
-- Existing PR/PO/GRN/invoice runtime is unchanged and not connected here.
begin;
create table if not exists public.supplier_payables_v1(
 id bigint generated by default as identity primary key,
 branch_id bigint not null references public.branches(id) on delete restrict,
 supplier_id bigint not null references public.retail_suppliers(id) on delete restrict,
 supplier_invoice_id bigint not null unique references public.retail_supplier_invoices(id) on delete restrict,
 purchase_order_id bigint references public.retail_purchase_orders(id) on delete restrict,
 currency_code text not null,original_amount numeric(18,2) not null check(original_amount>=0),
 settled_amount numeric(18,2) not null default 0 check(settled_amount>=0),
 credited_amount numeric(18,2) not null default 0 check(credited_amount>=0),
 outstanding_amount numeric(18,2) generated always as(original_amount-settled_amount-credited_amount) stored,
 status text not null check(status in('APPROVED','PARTIALLY_SETTLED','SETTLED','DISPUTED','FORWARD_RECOVERY_REQUIRED')),
 source_digest text not null check(source_digest~'^[0-9a-f]{64}$'),client_tx_id text not null unique,
 approved_at timestamptz not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 check(settled_amount+credited_amount<=original_amount));
create table if not exists public.supplier_payable_credits_v1(
 id bigint generated by default as identity primary key,payable_id bigint not null references public.supplier_payables_v1(id) on delete restrict,
 supplier_return_id bigint not null unique references public.retail_supplier_returns(id) on delete restrict,
 credit_amount numeric(18,2) not null check(credit_amount>0),client_tx_id text not null unique,
 operation_digest text not null check(operation_digest~'^[0-9a-f]{64}$'),lineage jsonb not null check(jsonb_typeof(lineage)='object'),created_at timestamptz not null default now());
create table if not exists public.supplier_payments_v1(
 id bigint generated by default as identity primary key,branch_id bigint not null references public.branches(id) on delete restrict,
 supplier_id bigint not null references public.retail_suppliers(id) on delete restrict,currency_code text not null,
 payment_amount numeric(18,2) not null check(payment_amount>0),allocated_amount numeric(18,2) not null default 0 check(allocated_amount>=0),
 unallocated_amount numeric(18,2) generated always as(payment_amount-allocated_amount) stored,
 payment_method_id bigint references public.payment_methods(id) on delete restrict,
 treasury_movement_id bigint unique references public.treasury_movements(id) on delete restrict,
 client_tx_id text not null unique,operation_digest text not null check(operation_digest~'^[0-9a-f]{64}$'),
 status text not null check(status in('CAPTURED','PARTIALLY_ALLOCATED','ALLOCATED','REVERSED','FORWARD_RECOVERY_REQUIRED')),
 paid_at timestamptz not null,created_at timestamptz not null default now(),check(allocated_amount<=payment_amount));
create table if not exists public.supplier_payment_allocations_v1(
 id bigint generated by default as identity primary key,payment_id bigint not null references public.supplier_payments_v1(id) on delete restrict,
 payable_id bigint not null references public.supplier_payables_v1(id) on delete restrict,amount numeric(18,2) not null check(amount>0),
 line_key text not null,operation_digest text not null check(operation_digest~'^[0-9a-f]{64}$'),created_at timestamptz not null default now(),
 unique(payment_id,line_key),unique(payment_id,payable_id));
create table if not exists public.supplier_payable_landed_cost_links_v1(
 payable_id bigint not null references public.supplier_payables_v1(id) on delete restrict,
 landed_cost_id bigint not null references public.retail_landed_costs(id) on delete restrict,
 linked_amount numeric(18,2) not null check(linked_amount>0),lineage jsonb not null check(jsonb_typeof(lineage)='object'),
 primary key(payable_id,landed_cost_id));
create table if not exists public.supplier_ap_events_v1(
 id bigint generated by default as identity primary key,event_type text not null check(event_type in('PAYABLE_APPROVED','CREDIT_APPLIED','PAYMENT_CAPTURED','PAYMENT_ALLOCATED','PAYMENT_REVERSED','RECOVERY')),
 entity_type text not null check(entity_type in('payable','credit','payment','allocation')),entity_id bigint not null,
 client_tx_id text not null,operation_digest text not null check(operation_digest~'^[0-9a-f]{64}$'),payload jsonb not null check(jsonb_typeof(payload)='object'),
 recorded_at timestamptz not null default now(),unique(event_type,client_tx_id));
create or replace function public.supplier_ap_event_immutable_v1() returns trigger language plpgsql security definer set search_path='' as $$begin raise exception 'SUPPLIER_AP_EVENT_IMMUTABLE';end$$;
drop trigger if exists supplier_ap_events_v1_immutable on public.supplier_ap_events_v1;create trigger supplier_ap_events_v1_immutable before update or delete on public.supplier_ap_events_v1 for each row execute function public.supplier_ap_event_immutable_v1();
create or replace function public.supplier_ap_point4d_activation_allowed_v1() returns boolean language sql stable security definer set search_path='' as $$select false$$;
create or replace function public.supplier_ap_intent_digest_v1(p_operation_type text,p_client_tx_id text,p_source_type text,p_source_id bigint,p_amount numeric,p_currency_code text,p_lines jsonb) returns text language sql immutable security definer set search_path='' as $$
 select pg_catalog.encode(extensions.digest(pg_catalog.convert_to(jsonb_build_object('schema_version',1,'operation_type',p_operation_type,'client_tx_id',btrim(p_client_tx_id),'source_type',p_source_type,'source_id',p_source_id,'amount',round(p_amount,2),'currency_code',upper(btrim(p_currency_code)),'lines',coalesce(p_lines,'[]'::jsonb))::text,'UTF8'),'sha256'),'hex')$$;
create or replace function public.supplier_ap_assert_activation_v1() returns void language plpgsql stable security definer set search_path='' as $$begin if not public.supplier_ap_point4d_activation_allowed_v1() then raise exception 'SUPPLIER_AP_V1_ACTIVATION_BLOCKED';end if;end$$;
alter table public.supplier_payables_v1 enable row level security;alter table public.supplier_payable_credits_v1 enable row level security;alter table public.supplier_payments_v1 enable row level security;alter table public.supplier_payment_allocations_v1 enable row level security;alter table public.supplier_payable_landed_cost_links_v1 enable row level security;alter table public.supplier_ap_events_v1 enable row level security;
revoke all on public.supplier_payables_v1,public.supplier_payable_credits_v1,public.supplier_payments_v1,public.supplier_payment_allocations_v1,public.supplier_payable_landed_cost_links_v1,public.supplier_ap_events_v1 from public,anon,authenticated;
revoke all on function public.supplier_ap_event_immutable_v1() from public,anon,authenticated;revoke all on function public.supplier_ap_point4d_activation_allowed_v1() from public,anon,authenticated;revoke all on function public.supplier_ap_intent_digest_v1(text,text,text,bigint,numeric,text,jsonb) from public,anon,authenticated;revoke all on function public.supplier_ap_assert_activation_v1() from public,anon,authenticated;
comment on table public.supplier_payables_v1 is 'Point 4D source-only authoritative AP contract; no current purchasing or treasury workflow is connected.';
commit;
