-- Top Burger POS V9.1 — Menu + Single/Double/Triple variants
-- Run ONCE in Supabase SQL Editor BEFORE uploading V9.1 files.

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  name text not null,
  price numeric(12,2) not null default 0,
  sort_order integer not null default 0,
  active boolean not null default true,
  unique(product_id,name)
);
alter table public.product_variants enable row level security;
grant select,insert,update,delete on public.product_variants to authenticated;
grant select on public.product_variants to anon;
drop policy if exists product_variants_staff_read on public.product_variants;
create policy product_variants_staff_read on public.product_variants for select to authenticated using (true);
drop policy if exists product_variants_staff_write on public.product_variants;
create policy product_variants_staff_write on public.product_variants for all to authenticated
using (public.has_permission('products')) with check (public.has_permission('products'));
drop policy if exists website_public_product_variants_read on public.product_variants;
create policy website_public_product_variants_read on public.product_variants for select to anon using (active=true);

-- Categories in requested order
create temporary table _tb_cats(name text, sort_order int) on commit drop;
insert into _tb_cats values
('عروض',1),('برجر',2),('فرايد تشيكن',3),('برجر ميكس',4),('توب بوم',5),('اطباق بطاطس',6),('اضافات',7),('مشروبات',8);

do $$ declare r record; cid bigint; begin
 for r in select * from _tb_cats loop
   select id into cid from public.categories where name=r.name order by id limit 1;
   if cid is null then
     insert into public.categories(name,active,website_visible,website_sort_order) values(r.name,true,true,r.sort_order) returning id into cid;
   else
     update public.categories set active=true,website_visible=true,website_sort_order=r.sort_order where id=cid;
   end if;
 end loop;
end $$;

-- Helper used only by this migration
create or replace function public._tb_menu_product(p_cat text,p_name text,p_price numeric,p_sort int default 0)
returns bigint language plpgsql as $$
declare cid bigint; pid bigint;
begin
 select id into cid from public.categories where name=p_cat order by id limit 1;
 select id into pid from public.products where name=p_name order by id limit 1;
 if pid is null then
   insert into public.products(name,category_id,price,cost,active,website_visible,website_sort_order,allow_extras,allow_removals,allow_item_notes)
   values(p_name,cid,p_price,0,true,true,p_sort,true,true,true) returning id into pid;
 else
   update public.products set category_id=cid,price=p_price,active=true,website_visible=true,website_sort_order=p_sort where id=pid;
 end if;
 insert into public.branch_products(branch_id,product_id,active) select b.id,pid,true from public.branches b where b.id in (1,2)
 on conflict(branch_id,product_id) do update set active=true;
 return pid;
end $$;

-- Products
select public._tb_menu_product('عروض','عرض السنجل',150,1);
select public._tb_menu_product('عروض','عرض الدبل',225,2);
select public._tb_menu_product('عروض','عرض الملوك',399,3);

select public._tb_menu_product('برجر','أوريجنال لحم',90,1);
select public._tb_menu_product('برجر','رانش برجر',95,2);
select public._tb_menu_product('برجر','تيستي ستكس',100,3);
select public._tb_menu_product('برجر','توب برجر',110,4);
select public._tb_menu_product('برجر','مشروم بيف',110,5);
select public._tb_menu_product('برجر','أونيون رينج بيف',110,6);

select public._tb_menu_product('فرايد تشيكن','أوريجنال تشيكن',90,1);
select public._tb_menu_product('فرايد تشيكن','تشيكن رانش',95,2);
select public._tb_menu_product('فرايد تشيكن','تشيكن أند ستكس',95,3);
select public._tb_menu_product('فرايد تشيكن','تشيكن توب',110,4);
select public._tb_menu_product('فرايد تشيكن','مشروم تشيكن',110,5);
select public._tb_menu_product('فرايد تشيكن','أونيون رينج تشيكن',110,6);

select public._tb_menu_product('برجر ميكس','برجر ميكس',145,1);
select public._tb_menu_product('توب بوم','توب بوم',120,1);

select public._tb_menu_product('اطباق بطاطس','كريسبي',70,1);
select public._tb_menu_product('اطباق بطاطس','تركي مدخن',55,2);
select public._tb_menu_product('اطباق بطاطس','شيدر',50,3);
select public._tb_menu_product('اطباق بطاطس','بارميزان',45,4);

select public._tb_menu_product('اضافات','روست بيف',10,1);
select public._tb_menu_product('اضافات','تركي مدخن إضافي',10,2);
select public._tb_menu_product('اضافات','موزاريلا ستكس',10,3);
select public._tb_menu_product('اضافات','مشروم سوتيه',15,4);
select public._tb_menu_product('اضافات','قطعة برجر لحم',45,5);
select public._tb_menu_product('اضافات','قطعة دجاج كريسبي',45,6);
select public._tb_menu_product('اضافات','صوص إضافي',15,7);
select public._tb_menu_product('اضافات','صوص شيدر',20,8);
select public._tb_menu_product('اضافات','أونيون رينج',10,9);

select public._tb_menu_product('مشروبات','ماكس كولا',15,1);
select public._tb_menu_product('مشروبات','ماكس كولا لتر',30,2);

-- Variants: all sandwiches Single/Double, Top Boom also Triple
create temporary table _tb_vars(product_name text,variant_name text,price numeric,sort_order int) on commit drop;
insert into _tb_vars values
('أوريجنال لحم','سينجل',90,1),('أوريجنال لحم','دبل',130,2),
('رانش برجر','سينجل',95,1),('رانش برجر','دبل',135,2),
('تيستي ستكس','سينجل',100,1),('تيستي ستكس','دبل',140,2),
('توب برجر','سينجل',110,1),('توب برجر','دبل',145,2),
('مشروم بيف','سينجل',110,1),('مشروم بيف','دبل',145,2),
('أونيون رينج بيف','سينجل',110,1),('أونيون رينج بيف','دبل',145,2),
('أوريجنال تشيكن','سينجل',90,1),('أوريجنال تشيكن','دبل',130,2),
('تشيكن رانش','سينجل',95,1),('تشيكن رانش','دبل',135,2),
('تشيكن أند ستكس','سينجل',95,1),('تشيكن أند ستكس','دبل',140,2),
('تشيكن توب','سينجل',110,1),('تشيكن توب','دبل',145,2),
('مشروم تشيكن','سينجل',110,1),('مشروم تشيكن','دبل',145,2),
('أونيون رينج تشيكن','سينجل',110,1),('أونيون رينج تشيكن','دبل',145,2),
('برجر ميكس','سينجل',145,1),('برجر ميكس','دبل',160,2),
('توب بوم','سينجل',120,1),('توب بوم','دبل',160,2),('توب بوم','تريبل',190,3);
insert into public.product_variants(product_id,name,price,sort_order,active)
select p.id,v.variant_name,v.price,v.sort_order,true from _tb_vars v join public.products p on p.name=v.product_name
on conflict(product_id,name) do update set price=excluded.price,sort_order=excluded.sort_order,active=true;

-- Extras as modifiers too, so they can be attached to sandwich items
create temporary table _tb_mods(name text,price numeric) on commit drop;
insert into _tb_mods values
('روست بيف',10),('تركي مدخن',10),('موزاريلا ستكس',10),('مشروم سوتيه',15),('قطعة برجر لحم',45),('قطعة دجاج كريسبي',45),('صوص إضافي',15),('صوص شيدر',20),('أونيون رينج',10);
do $$ declare r record; mid bigint; begin
 for r in select * from _tb_mods loop
   select id into mid from public.modifiers where name=r.name order by id limit 1;
   if mid is null then insert into public.modifiers(name,price,active) values(r.name,r.price,true); else update public.modifiers set price=r.price,active=true where id=mid; end if;
 end loop;
end $$;

-- Attach all extras to sandwich products (can be refined later per product)
insert into public.product_modifiers(product_id,modifier_id)
select p.id,m.id from public.products p cross join public.modifiers m
where p.name in ('أوريجنال لحم','رانش برجر','تيستي ستكس','توب برجر','مشروم بيف','أونيون رينج بيف','أوريجنال تشيكن','تشيكن رانش','تشيكن أند ستكس','تشيكن توب','مشروم تشيكن','أونيون رينج تشيكن','برجر ميكس','توب بوم')
and m.name in ('روست بيف','تركي مدخن','موزاريلا ستكس','مشروم سوتيه','قطعة برجر لحم','قطعة دجاج كريسبي','صوص إضافي','صوص شيدر','أونيون رينج')
on conflict do nothing;

-- Inventory remains disabled as requested
insert into public.app_settings(key,value) values('enable_inventory','false')
on conflict(key) do update set value='false';

drop function if exists public._tb_menu_product(text,text,numeric,int);
notify pgrst, 'reload schema';
