-- Sharawla POS — Point 4E-1 Authoritative Financial Journal source contract.
-- SOURCE ONLY: no operational workflow is connected and activation is false.
-- TENANT BOUNDARY: one operational backend belongs to one Sharawla Business;
-- branch_id is the in-backend location identity and no synthetic business_id is stored here.
begin;
create table if not exists public.finance_journal_events_v1(
 id bigint generated by default as identity primary key,branch_id bigint references public.branches(id) on delete restrict,
 event_type text not null check(event_type in('SALE','PAYMENT','REFUND','EXPENSE','CASH_MOVEMENT','SHIFT_SETTLEMENT','RECEIVABLE','COLLECTION','PAYABLE','SUPPLIER_PAYMENT','INVENTORY_VALUE','COGS','WASTE','DAMAGE','TRANSFER_VALUE','TRANSFER_VARIANCE','REVERSAL')),
 source_document_type text not null,source_document_id text not null check(source_document_id~'^(uuid:[0-9a-f-]{36}|digest:sha256:[0-9a-f]{64}|db:[1-9][0-9]*)$'),client_tx_id text not null,line_key text not null check(line_key!~':v1:'),
 operation_digest text not null check(operation_digest~'^[0-9a-f]{64}$'),currency_code text not null,
 reversal_of_event_id bigint unique references public.finance_journal_events_v1(id) on delete restrict,
 lineage jsonb not null check(jsonb_typeof(lineage)='object'),occurred_at timestamptz not null,recorded_at timestamptz not null default now(),
 unique(client_tx_id,line_key),unique(source_document_type,source_document_id,event_type,line_key),
 check(event_type='REVERSAL' or reversal_of_event_id is null),check(event_type<>'REVERSAL' or reversal_of_event_id is not null));
create table if not exists public.finance_journal_lines_v1(
 id bigint generated by default as identity primary key,event_id bigint not null references public.finance_journal_events_v1(id) on delete restrict,
 evidence_line_uid uuid not null check(evidence_line_uid::text~'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
 posting_role text not null check(posting_role~'^[a-z][a-z0-9_]*$'),posting_component_uid uuid,
 line_key text not null check(line_key!~':v1:'),reversal_of_line_key text check(reversal_of_line_key is null or reversal_of_line_key!~':v1:'),line_number integer not null check(line_number>0),account_code text not null,location_id bigint references public.branches(id) on delete restrict,
 counterparty_type text,counterparty_id text,debit numeric(18,4) not null default 0 check(debit>=0),credit numeric(18,4) not null default 0 check(credit>=0),
 quantity numeric(18,3),unit_cost numeric(18,4),stock_movement_id bigint references public.inventory_stock_movements_v2(id) on delete restrict,
 transfer_operation_id bigint references public.inventory_transfer_operations_v2(id) on delete restrict,
 payable_id bigint references public.supplier_payables_v1(id) on delete restrict,lineage jsonb not null check(jsonb_typeof(lineage)='object'),
 unique(event_id,line_key),unique(event_id,reversal_of_line_key),unique(event_id,line_number),unique(event_id,evidence_line_uid,posting_role,posting_component_uid),check(line_key is distinct from reversal_of_line_key),check((debit>0 and credit=0) or (credit>0 and debit=0)));
create index if not exists finance_journal_events_source_v1 on public.finance_journal_events_v1(source_document_type,source_document_id);
create index if not exists finance_journal_lines_account_v1 on public.finance_journal_lines_v1(account_code,event_id);
create or replace function public.finance_journal_immutable_v1() returns trigger language plpgsql security definer set search_path='' as $$begin raise exception 'FINANCE_JOURNAL_V1_IMMUTABLE';end$$;
drop trigger if exists finance_journal_events_v1_immutable on public.finance_journal_events_v1;create trigger finance_journal_events_v1_immutable before update or delete on public.finance_journal_events_v1 for each row execute function public.finance_journal_immutable_v1();
drop trigger if exists finance_journal_lines_v1_immutable on public.finance_journal_lines_v1;create trigger finance_journal_lines_v1_immutable before update or delete on public.finance_journal_lines_v1 for each row execute function public.finance_journal_immutable_v1();
create or replace function public.finance_journal_assert_balanced_v1() returns trigger language plpgsql security definer set search_path='' as $$declare v_id bigint;v_debit numeric;v_credit numeric;v_original bigint;v_expected jsonb;v_actual jsonb;begin v_id:=coalesce(new.event_id,old.event_id);select coalesce(sum(debit),0),coalesce(sum(credit),0) into v_debit,v_credit from public.finance_journal_lines_v1 where event_id=v_id;if v_debit<=0 or v_debit<>v_credit then raise exception 'FINANCE_JOURNAL_V1_UNBALANCED';end if;select reversal_of_event_id into v_original from public.finance_journal_events_v1 where id=v_id;if v_original is not null then
 select jsonb_agg(jsonb_build_array(line_key,posting_role,posting_component_uid,account_code,location_id,counterparty_type,counterparty_id,credit,debit,case when quantity is null then null else -quantity end,unit_cost) order by line_key collate "C") into v_expected from public.finance_journal_lines_v1 where event_id=v_original;
 select jsonb_agg(jsonb_build_array(reversal_of_line_key,posting_role,posting_component_uid,account_code,location_id,counterparty_type,counterparty_id,debit,credit,quantity,unit_cost) order by reversal_of_line_key collate "C") into v_actual from public.finance_journal_lines_v1 where event_id=v_id;
 if v_actual is distinct from v_expected then raise exception 'FINANCE_JOURNAL_V1_REVERSAL_MISMATCH';end if;
end if;return null;end$$;
drop trigger if exists finance_journal_lines_v1_balanced on public.finance_journal_lines_v1;create constraint trigger finance_journal_lines_v1_balanced after insert or update or delete on public.finance_journal_lines_v1 deferrable initially deferred for each row execute function public.finance_journal_assert_balanced_v1();
create or replace function public.finance_journal_event_complete_v1() returns trigger language plpgsql security definer set search_path='' as $$declare v_debit numeric;v_credit numeric;v_lines bigint;v_bad bigint;v_original public.finance_journal_events_v1%rowtype;begin select count(*),coalesce(sum(debit),0),coalesce(sum(credit),0) into v_lines,v_debit,v_credit from public.finance_journal_lines_v1 where event_id=new.id;if v_lines<2 or v_debit<=0 or v_debit<>v_credit then raise exception 'FINANCE_JOURNAL_V1_EVENT_INCOMPLETE';end if;if new.reversal_of_event_id is not null then select * into strict v_original from public.finance_journal_events_v1 where id=new.reversal_of_event_id;if v_original.event_type='REVERSAL' or v_original.reversal_of_event_id is not null then raise exception 'FINANCE_JOURNAL_V1_REVERSAL_OF_REVERSAL';end if;if new.branch_id is distinct from v_original.branch_id or upper(new.currency_code)<>upper(v_original.currency_code) then raise exception 'FINANCE_JOURNAL_V1_REVERSAL_SCOPE_MISMATCH';end if;select count(*) into v_bad from public.finance_journal_lines_v1 where event_id=new.id and (reversal_of_line_key is null or reversal_of_line_key=line_key);if v_bad<>0 then raise exception 'FINANCE_JOURNAL_V1_REVERSAL_LINEAGE_REQUIRED';end if;else select count(*) into v_bad from public.finance_journal_lines_v1 where event_id=new.id and reversal_of_line_key is not null;if v_bad<>0 then raise exception 'FINANCE_JOURNAL_V1_UNEXPECTED_REVERSAL_LINEAGE';end if;end if;return null;end$$;
drop trigger if exists finance_journal_events_v1_complete on public.finance_journal_events_v1;create constraint trigger finance_journal_events_v1_complete after insert on public.finance_journal_events_v1 deferrable initially deferred for each row execute function public.finance_journal_event_complete_v1();
create or replace function public.finance_journal_point4e_activation_allowed_v1() returns boolean language sql stable security definer set search_path='' as $$select false$$;
create or replace function public.finance_journal_canonical_lines_v1(p_event_type text,p_lines jsonb) returns jsonb language plpgsql immutable set search_path='' as $$
declare l jsonb;v jsonb;v_result jsonb:='[]'::jsonb;v_uid text;v_role text;v_component text;v_key text;v_reversal_key text;v_event_type text:=upper(trim(coalesce(p_event_type,'')));
begin
 if p_lines is null or jsonb_typeof(p_lines)<>'array' then raise exception 'FINANCE_JOURNAL_V1_LINES_ARRAY_REQUIRED';end if;
 for l in select value from jsonb_array_elements(p_lines) loop
  perform public.point4_identity_assert_allowed_keys_v1(l,array['evidence_line_uid','posting_role','posting_component_uid','account_code','location_id','counterparty_type','counterparty_id','debit','credit','quantity','unit_cost','stock_effect_client_tx_id','stock_effect_line_key','stock_effect_operation_digest','transfer_source_document_id','payable_source_document_id','reversal_of_line_key']);
  v_uid:=public.point4_identity_uuid_v4_v1(l->>'evidence_line_uid');
  v_role:=lower(trim(coalesce(l->>'posting_role','')));
  if v_role!~'^[a-z][a-z0-9_]*$' then raise exception 'FINANCE_JOURNAL_V1_POSTING_ROLE_REQUIRED';end if;
  v_key:=public.point4_identity_effect_line_key_v1('journal','posting',v_uid,'role',v_role);
  v_component:=nullif(lower(trim(coalesce(l->>'posting_component_uid',''))),'');
  if v_component is not null then
   v_component:=public.point4_identity_uuid_v4_v1(v_component);
   v_key:=v_key||':component:'||v_component;
  end if;
  if (l?'stock_effect_client_tx_id' or l?'stock_effect_line_key' or l?'stock_effect_operation_digest') and (
    nullif(trim(l->>'stock_effect_client_tx_id'),'') is null
    or nullif(trim(l->>'stock_effect_line_key'),'') is null
    or coalesce(l->>'stock_effect_operation_digest','')!~'^[0-9a-f]{64}$'
  ) then raise exception 'FINANCE_JOURNAL_V1_CANONICAL_STOCK_LINEAGE_REQUIRED';end if;
  if l?'transfer_source_document_id' and l->'transfer_source_document_id'<>'null'::jsonb then
   perform public.point4_identity_source_document_id_v1('inventory_transfer',l->>'transfer_source_document_id',false);
  end if;
  if l?'payable_source_document_id' and l->'payable_source_document_id'<>'null'::jsonb then
   perform public.point4_identity_source_document_id_v1('supplier_payable',l->>'payable_source_document_id',false);
  end if;
  v_reversal_key:=nullif(trim(coalesce(l->>'reversal_of_line_key','')),'');
  if v_event_type='REVERSAL' and (v_reversal_key is null or v_reversal_key like '%:v1:%' or v_reversal_key=v_key) then raise exception 'FINANCE_JOURNAL_V1_REVERSAL_LINEAGE_REQUIRED';end if;
  if v_event_type<>'REVERSAL' and v_reversal_key is not null then raise exception 'FINANCE_JOURNAL_V1_UNEXPECTED_REVERSAL_LINEAGE';end if;
  v:=jsonb_build_object(
   'evidence_line_uid',v_uid,'posting_role',v_role,'posting_component_uid',v_component,'line_key',v_key,'reversal_of_line_key',v_reversal_key,
   'account_code',upper(trim(coalesce(l->>'account_code',''))),
   'location_id',case when not l?'location_id' or l->'location_id'='null'::jsonb then null else public.point4_identity_bigint_v1(l->'location_id',true) end,
   'counterparty_type',case when not l?'counterparty_type' or l->'counterparty_type'='null'::jsonb then null else lower(trim(l->>'counterparty_type')) end,
   'counterparty_id',case when not l?'counterparty_id' or l->'counterparty_id'='null'::jsonb then null else trim(l->>'counterparty_id') end,
   'debit',public.point4_identity_decimal_v1((l->>'debit')::numeric,4),'credit',public.point4_identity_decimal_v1((l->>'credit')::numeric,4),
   'quantity',case when not l?'quantity' or l->'quantity'='null'::jsonb then null else public.point4_identity_decimal_v1((l->>'quantity')::numeric,3) end,
   'unit_cost',case when not l?'unit_cost' or l->'unit_cost'='null'::jsonb then null else public.point4_identity_decimal_v1((l->>'unit_cost')::numeric,4) end,
   'stock_effect_client_tx_id',case when not l?'stock_effect_client_tx_id' then null else lower(trim(l->>'stock_effect_client_tx_id')) end,
   'stock_effect_line_key',case when not l?'stock_effect_line_key' then null else l->>'stock_effect_line_key' end,
   'stock_effect_operation_digest',case when not l?'stock_effect_operation_digest' then null else lower(trim(l->>'stock_effect_operation_digest')) end,
   'transfer_source_document_id',case when not l?'transfer_source_document_id' or l->'transfer_source_document_id'='null'::jsonb then null else public.point4_identity_source_document_id_v1('inventory_transfer',l->>'transfer_source_document_id',false) end,
   'payable_source_document_id',case when not l?'payable_source_document_id' or l->'payable_source_document_id'='null'::jsonb then null else public.point4_identity_source_document_id_v1('supplier_payable',l->>'payable_source_document_id',false) end
  );
  if v->>'account_code'!~'^[A-Z0-9][A-Z0-9_.-]*$' then raise exception 'FINANCE_JOURNAL_V1_ACCOUNT_CODE_INVALID';end if;
  if (v->>'counterparty_type') is not null and v->>'counterparty_type'!~'^[a-z][a-z0-9_]*$' then raise exception 'FINANCE_JOURNAL_V1_COUNTERPARTY_TYPE_INVALID';end if;
  if (v->>'stock_effect_line_key') is not null and v->>'stock_effect_line_key' like '%:v1:%' then raise exception 'POINT4_IDENTITY_NESTED_LINE_KEY_FORBIDDEN';end if;
  v_result:=v_result||jsonb_build_array(v);
 end loop;
 return public.point4_identity_canonical_lines_v1(v_result);
end$$;
create or replace function public.finance_journal_intent_digest_v1(p_event_type text,p_client_tx_id text,p_event_line_key text,p_source_type text,p_source_document_id text,p_offline_capable boolean,p_branch_id bigint,p_currency text,p_lines jsonb,p_reversal_of jsonb,p_effective_date date default null) returns text language sql immutable set search_path='' as $$select public.point4_identity_operation_digest_v1(
 lower(p_event_type),p_client_tx_id,p_source_type,p_source_document_id,p_offline_capable,p_branch_id,p_currency,
 jsonb_build_object('event_line_key',p_event_line_key),public.finance_journal_canonical_lines_v1(p_event_type,p_lines),p_reversal_of,p_effective_date
)$$;
create or replace function public.finance_journal_resolve_replay_v1(p_client_tx_id text,p_line_key text,p_digest text) returns bigint language plpgsql stable security definer set search_path='' as $$declare v public.finance_journal_events_v1%rowtype;begin select * into v from public.finance_journal_events_v1 where client_tx_id=p_client_tx_id and line_key=p_line_key;if not found then return null;end if;if v.operation_digest<>p_digest then raise exception 'FINANCE_JOURNAL_V1_IDEMPOTENCY_CONFLICT';end if;return v.id;end$$;
create or replace function public.finance_journal_assert_activation_v1() returns void language plpgsql stable security definer set search_path='' as $$begin if not public.finance_journal_point4e_activation_allowed_v1() then raise exception 'FINANCE_JOURNAL_V1_ACTIVATION_BLOCKED';end if;end$$;
alter table public.finance_journal_events_v1 enable row level security;alter table public.finance_journal_lines_v1 enable row level security;
revoke all on public.finance_journal_events_v1,public.finance_journal_lines_v1 from public,anon,authenticated;
revoke all on function public.finance_journal_immutable_v1() from public,anon,authenticated;revoke all on function public.finance_journal_assert_balanced_v1() from public,anon,authenticated;revoke all on function public.finance_journal_event_complete_v1() from public,anon,authenticated;revoke all on function public.finance_journal_point4e_activation_allowed_v1() from public,anon,authenticated;revoke all on function public.finance_journal_canonical_lines_v1(text,jsonb) from public,anon,authenticated;revoke all on function public.finance_journal_intent_digest_v1(text,text,text,text,text,boolean,bigint,text,jsonb,jsonb,date) from public,anon,authenticated;revoke all on function public.finance_journal_resolve_replay_v1(text,text,text) from public,anon,authenticated;revoke all on function public.finance_journal_assert_activation_v1() from public,anon,authenticated;
comment on table public.finance_journal_events_v1 is 'Append-only Point 4 financial event contract. Source-only; no posting workflow is connected.';
commit;
