-- RC1 Retail Suspend/Resume Offline V1 — SOURCE ONLY / NOT DEPLOYED
-- Dedicated event endpoints keep the historical generic transport definition untouched.
create or replace function public.sharawla_offline_v2_apply_retail_suspend_event_v1(p_event jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_tx text:=nullif(trim(p_event->>'client_tx_id'),''); v_digest text:=nullif(trim(p_event->>'payload_digest'),''); v_payload jsonb:=coalesce(p_event#>'{payload,rpc_payload}','{}'::jsonb); v_branch bigint:=coalesce(nullif(p_event->>'branch_id','')::bigint,0); v_employee bigint:=coalesce(nullif(p_event->>'employee_id','')::bigint,0); v_id bigint; v_r public.offline_v2_server_receipts%rowtype; v_event text;
begin
 if auth.uid() is null or v_tx is null or v_digest is null or p_event->>'operation_type'<>'retail_suspend_sale' or p_event#>>'{payload,rpc_name}'<>'offline_retail_suspend_sale_v1' then raise exception using errcode='22023',message='Retail suspend Offline V2 event invalid'; end if;
 if public.current_employee_id() is distinct from v_employee or coalesce(nullif(v_payload->>'p_branch_id','')::bigint,0) is distinct from v_branch or nullif(trim(v_payload->>'p_client_tx_id'),'') is distinct from v_tx or not public.has_branch_access(v_branch) then raise exception using errcode='42501',message='Retail suspend identity/branch mismatch'; end if;
 perform pg_advisory_xact_lock(hashtextextended('offline-v2:'||v_tx,0)); select * into v_r from public.offline_v2_server_receipts where client_tx_id=v_tx;
 if found then if v_r.payload_digest is distinct from v_digest or v_r.operation_type<>'retail_suspend_sale' then raise exception using errcode='22000',message='Offline V2 duplicate TX mismatch'; end if; return jsonb_build_object('ok',true,'acknowledged',false,'duplicate',true,'idempotent_replay',true,'client_tx_id',v_tx,'protocol_version',2,'payload_digest',v_digest,'server_event_id',v_r.server_event_id,'server_entity_id',v_r.server_entity_id,'server_version',v_r.server_version,'result',v_r.result_json); end if;
 insert into public.retail_suspended_sales(branch_id,employee_id,label,cart,customer,financial) values(v_branch,v_employee,nullif(trim(coalesce(v_payload->>'p_label','')),''),coalesce(v_payload->'p_cart','[]'::jsonb),coalesce(v_payload->'p_customer','{}'::jsonb),coalesce(v_payload->'p_financial','{}'::jsonb)) returning id into v_id;
 v_event:='ov2-'||md5(v_tx||':'||v_digest); insert into public.offline_v2_server_receipts(client_tx_id,server_event_id,protocol_version,payload_digest,operation_type,rpc_name,device_id,device_sequence,branch_id,employee_id,auth_user_id,server_entity_id,server_version,result_json) values(v_tx,v_event,2,v_digest,'retail_suspend_sale','offline_retail_suspend_sale_v1',p_event->>'device_id',(p_event->>'device_sequence')::bigint,v_branch,v_employee,auth.uid(),v_id::text,'retail-hold-v1',jsonb_build_object('suspended_sale_id',v_id));
 return jsonb_build_object('ok',true,'acknowledged',true,'duplicate',false,'idempotent_replay',false,'client_tx_id',v_tx,'protocol_version',2,'payload_digest',v_digest,'server_event_id',v_event,'server_entity_id',v_id::text,'server_version','retail-hold-v1','result',jsonb_build_object('suspended_sale_id',v_id));
end $$;

create or replace function public.sharawla_offline_v2_apply_retail_resume_event_v1(p_event jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_tx text:=nullif(trim(p_event->>'client_tx_id'),''); v_digest text:=nullif(trim(p_event->>'payload_digest'),''); v_payload jsonb:=coalesce(p_event#>'{payload,rpc_payload}','{}'::jsonb); v_branch bigint:=coalesce(nullif(p_event->>'branch_id','')::bigint,0); v_employee bigint:=coalesce(nullif(p_event->>'employee_id','')::bigint,0); v_id bigint:=coalesce(nullif(v_payload->>'p_suspend_id','')::bigint,nullif(p_event#>>'{dependency_mapping,server_id}','')::bigint); v_r public.offline_v2_server_receipts%rowtype; v_event text;
begin
 if auth.uid() is null or v_tx is null or v_digest is null or p_event->>'operation_type'<>'retail_resume_sale' or p_event#>>'{payload,rpc_name}'<>'offline_retail_resume_sale_v1' then raise exception using errcode='22023',message='Retail resume Offline V2 event invalid'; end if;
 if public.current_employee_id() is distinct from v_employee or coalesce(nullif(v_payload->>'p_branch_id','')::bigint,0) is distinct from v_branch or nullif(trim(v_payload->>'p_client_tx_id'),'') is distinct from v_tx or not public.has_branch_access(v_branch) or v_id is null then raise exception using errcode='42501',message='Retail resume identity/branch mismatch'; end if;
 perform pg_advisory_xact_lock(hashtextextended('offline-v2:'||v_tx,0)); select * into v_r from public.offline_v2_server_receipts where client_tx_id=v_tx;
 if found then if v_r.payload_digest is distinct from v_digest or v_r.operation_type<>'retail_resume_sale' then raise exception using errcode='22000',message='Offline V2 duplicate TX mismatch'; end if; return jsonb_build_object('ok',true,'acknowledged',false,'duplicate',true,'idempotent_replay',true,'client_tx_id',v_tx,'protocol_version',2,'payload_digest',v_digest,'server_event_id',v_r.server_event_id,'server_entity_id',v_r.server_entity_id,'server_version',v_r.server_version,'result',v_r.result_json); end if;
 if not exists(select 1 from public.retail_suspended_sales where id=v_id and branch_id=v_branch) then raise exception using errcode='P0001',message='الفاتورة المعلقة غير موجودة في هذا الفرع'; end if;
 delete from public.retail_suspended_sales where id=v_id and branch_id=v_branch;
 v_event:='ov2-'||md5(v_tx||':'||v_digest); insert into public.offline_v2_server_receipts(client_tx_id,server_event_id,protocol_version,payload_digest,operation_type,rpc_name,device_id,device_sequence,branch_id,employee_id,auth_user_id,server_entity_id,server_version,result_json) values(v_tx,v_event,2,v_digest,'retail_resume_sale','offline_retail_resume_sale_v1',p_event->>'device_id',(p_event->>'device_sequence')::bigint,v_branch,v_employee,auth.uid(),v_id::text,'retail-hold-v1',jsonb_build_object('suspended_sale_id',v_id,'resumed',true));
 return jsonb_build_object('ok',true,'acknowledged',true,'duplicate',false,'idempotent_replay',false,'client_tx_id',v_tx,'protocol_version',2,'payload_digest',v_digest,'server_event_id',v_event,'server_entity_id',v_id::text,'server_version','retail-hold-v1','result',jsonb_build_object('suspended_sale_id',v_id,'resumed',true));
end $$;
revoke all on function public.sharawla_offline_v2_apply_retail_suspend_event_v1(jsonb) from public,anon;
revoke all on function public.sharawla_offline_v2_apply_retail_resume_event_v1(jsonb) from public,anon;
grant execute on function public.sharawla_offline_v2_apply_retail_suspend_event_v1(jsonb) to authenticated;
grant execute on function public.sharawla_offline_v2_apply_retail_resume_event_v1(jsonb) to authenticated;
