-- Sharawla POS — Membership/Gym Engine V1
begin;
create table if not exists public.membership_members_v1(id bigserial primary key,customer_id bigint not null unique references public.customers(id) on delete cascade,member_code text unique,status text not null default 'active' check(status in('active','inactive','blocked')),joined_on date not null default current_date,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.membership_plans_v1(id bigserial primary key,code text unique,name text not null,duration_days integer not null check(duration_days>0),price numeric(14,2) not null default 0 check(price>=0),freeze_days_allowed integer not null default 0 check(freeze_days_allowed>=0),visits_limit integer,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.membership_subscriptions_v1(id bigserial primary key,member_id bigint not null references public.membership_members_v1(id) on delete restrict,plan_id bigint not null references public.membership_plans_v1(id) on delete restrict,starts_on date not null,ends_on date not null,status text not null default 'active' check(status in('active','frozen','expired','cancelled')),paid_amount numeric(14,2) not null default 0,visits_used integer not null default 0,freeze_days_used integer not null default 0,client_tx_id text not null unique,created_at timestamptz not null default now(),constraint membership_subscription_dates check(ends_on>=starts_on));
create index if not exists membership_subscription_member_status_idx on public.membership_subscriptions_v1(member_id,status,ends_on);
create table if not exists public.membership_freezes_v1(id bigserial primary key,subscription_id bigint not null references public.membership_subscriptions_v1(id) on delete restrict,starts_on date not null,ends_on date not null,days_count integer not null check(days_count>0),reason text,status text not null default 'active' check(status in('active','completed','cancelled')),employee_id bigint references public.employees(id),created_at timestamptz not null default now());
create table if not exists public.membership_checkins_v1(id bigserial primary key,branch_id bigint not null references public.branches(id),member_id bigint not null references public.membership_members_v1(id),subscription_id bigint not null references public.membership_subscriptions_v1(id),checked_in_at timestamptz not null default now(),checked_out_at timestamptz,employee_id bigint references public.employees(id),client_tx_id text not null unique);
create table if not exists public.membership_trainers_v1(id bigserial primary key,employee_id bigint not null unique references public.employees(id) on delete cascade,specialty text,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.membership_classes_v1(id bigserial primary key,branch_id bigint not null references public.branches(id),name text not null,trainer_id bigint references public.membership_trainers_v1(id) on delete set null,starts_at timestamptz not null,ends_at timestamptz not null,capacity integer not null default 1 check(capacity>0),status text not null default 'scheduled' check(status in('scheduled','open','completed','cancelled')),created_at timestamptz not null default now(),constraint membership_class_dates check(ends_at>starts_at));
create table if not exists public.membership_bookings_v1(id bigserial primary key,class_id bigint not null references public.membership_classes_v1(id) on delete cascade,member_id bigint not null references public.membership_members_v1(id),status text not null default 'booked' check(status in('booked','attended','no_show','cancelled')),client_tx_id text not null unique,created_at timestamptz not null default now(),unique(class_id,member_id));
create table if not exists public.membership_renewal_events_v1(id bigserial primary key,subscription_id bigint not null references public.membership_subscriptions_v1(id),previous_end_date date not null,new_end_date date not null,amount numeric(14,2) not null default 0,employee_id bigint references public.employees(id),client_tx_id text not null unique,created_at timestamptz not null default now());

create or replace function public.membership_member_create_v1(p_customer_id bigint,p_notes text)
returns bigint language plpgsql security definer set search_path=public as $$declare idv bigint;begin if auth.uid() is null then raise exception 'غير مصرح';end if;insert into public.membership_members_v1(customer_id,notes) values(p_customer_id,nullif(trim(coalesce(p_notes,'')),'')) on conflict(customer_id) do update set updated_at=now() returning id into idv;update public.membership_members_v1 set member_code=coalesce(member_code,'MEM-'||lpad(idv::text,6,'0')) where id=idv;return idv;end;$$;
create or replace function public.membership_plan_save_v1(p_id bigint,p_code text,p_name text,p_duration_days integer,p_price numeric,p_freeze_days integer,p_visits_limit integer,p_active boolean)
returns public.membership_plans_v1 language plpgsql security definer set search_path=public as $$declare r public.membership_plans_v1%rowtype;begin if auth.uid() is null or not public.is_admin() then raise exception 'إدارة الخطط للمدير فقط';end if;if nullif(trim(coalesce(p_name,'')),'') is null or coalesce(p_duration_days,0)<=0 then raise exception 'بيانات الخطة غير صحيحة';end if;if p_id is null then insert into public.membership_plans_v1(code,name,duration_days,price,freeze_days_allowed,visits_limit,active) values(nullif(lower(trim(coalesce(p_code,''))),''),trim(p_name),p_duration_days,greatest(coalesce(p_price,0),0),greatest(coalesce(p_freeze_days,0),0),p_visits_limit,coalesce(p_active,true)) returning * into r;else update public.membership_plans_v1 set code=nullif(lower(trim(coalesce(p_code,''))),''),name=trim(p_name),duration_days=p_duration_days,price=greatest(coalesce(p_price,0),0),freeze_days_allowed=greatest(coalesce(p_freeze_days,0),0),visits_limit=p_visits_limit,active=coalesce(p_active,true),updated_at=now() where id=p_id returning * into r;end if;return r;end;$$;
create or replace function public.membership_subscribe_v1(p_member_id bigint,p_plan_id bigint,p_starts_on date,p_paid_amount numeric,p_client_tx_id text)
returns bigint language plpgsql security definer set search_path=public as $$declare idv bigint;p public.membership_plans_v1%rowtype;k text:=nullif(trim(coalesce(p_client_tx_id,'')),'');begin if auth.uid() is null then raise exception 'غير مصرح';end if;if k is null then raise exception 'معرف الحركة مطلوب';end if;perform pg_advisory_xact_lock(hashtextextended('membership-sub:'||k,0));select id into idv from public.membership_subscriptions_v1 where client_tx_id=k;if idv is not null then return idv;end if;select * into p from public.membership_plans_v1 where id=p_plan_id and active=true;if not found then raise exception 'الخطة غير موجودة';end if;insert into public.membership_subscriptions_v1(member_id,plan_id,starts_on,ends_on,paid_amount,client_tx_id) values(p_member_id,p.id,coalesce(p_starts_on,current_date),coalesce(p_starts_on,current_date)+p.duration_days-1,greatest(coalesce(p_paid_amount,0),0),k) returning id into idv;return idv;end;$$;
create or replace function public.membership_renew_v1(p_subscription_id bigint,p_amount numeric,p_client_tx_id text)
returns date language plpgsql security definer set search_path=public as $$declare s public.membership_subscriptions_v1%rowtype;p public.membership_plans_v1%rowtype;old date;nw date;e bigint;k text:=nullif(trim(coalesce(p_client_tx_id,'')),'');begin if auth.uid() is null then raise exception 'غير مصرح';end if;if k is null then raise exception 'معرف الحركة مطلوب';end if;perform pg_advisory_xact_lock(hashtextextended('membership-renew:'||k,0));if exists(select 1 from public.membership_renewal_events_v1 where client_tx_id=k) then select new_end_date into nw from public.membership_renewal_events_v1 where client_tx_id=k;return nw;end if;select * into s from public.membership_subscriptions_v1 where id=p_subscription_id for update;select * into p from public.membership_plans_v1 where id=s.plan_id;old:=s.ends_on;nw:=greatest(s.ends_on,current_date)+p.duration_days;update public.membership_subscriptions_v1 set ends_on=nw,status='active' where id=s.id;e:=public.current_employee_id();insert into public.membership_renewal_events_v1(subscription_id,previous_end_date,new_end_date,amount,employee_id,client_tx_id) values(s.id,old,nw,greatest(coalesce(p_amount,0),0),e,k);return nw;end;$$;
create or replace function public.membership_freeze_v1(p_subscription_id bigint,p_starts_on date,p_days integer,p_reason text)
returns bigint language plpgsql security definer set search_path=public as $$declare s public.membership_subscriptions_v1%rowtype;p public.membership_plans_v1%rowtype;idv bigint;e bigint;begin if auth.uid() is null then raise exception 'غير مصرح';end if;select * into s from public.membership_subscriptions_v1 where id=p_subscription_id for update;select * into p from public.membership_plans_v1 where id=s.plan_id;if coalesce(p_days,0)<=0 or s.freeze_days_used+p_days>p.freeze_days_allowed then raise exception 'رصيد التجميد غير كافٍ';end if;e:=public.current_employee_id();insert into public.membership_freezes_v1(subscription_id,starts_on,ends_on,days_count,reason,employee_id) values(s.id,coalesce(p_starts_on,current_date),coalesce(p_starts_on,current_date)+p_days-1,p_days,nullif(trim(coalesce(p_reason,'')),''),e) returning id into idv;update public.membership_subscriptions_v1 set status='frozen',freeze_days_used=freeze_days_used+p_days,ends_on=ends_on+p_days where id=s.id;return idv;end;$$;
create or replace function public.membership_checkin_v1(p_branch_id bigint,p_member_id bigint,p_client_tx_id text)
returns bigint language plpgsql security definer set search_path=public as $$declare s public.membership_subscriptions_v1%rowtype;p public.membership_plans_v1%rowtype;idv bigint;e bigint;k text:=nullif(trim(coalesce(p_client_tx_id,'')),'');begin if auth.uid() is null then raise exception 'غير مصرح';end if;if not public.has_branch_access(p_branch_id) then raise exception 'ليس لديك صلاحية لهذا الفرع';end if;if k is null then raise exception 'معرف الحركة مطلوب';end if;perform pg_advisory_xact_lock(hashtextextended('membership-checkin:'||k,0));select id into idv from public.membership_checkins_v1 where client_tx_id=k;if idv is not null then return idv;end if;select * into s from public.membership_subscriptions_v1 where member_id=p_member_id and status='active' and current_date between starts_on and ends_on order by ends_on desc limit 1 for update;if not found then raise exception 'لا يوجد اشتراك فعال';end if;select * into p from public.membership_plans_v1 where id=s.plan_id;if p.visits_limit is not null and s.visits_used>=p.visits_limit then raise exception 'تم استهلاك عدد الزيارات';end if;e:=public.current_employee_id();insert into public.membership_checkins_v1(branch_id,member_id,subscription_id,employee_id,client_tx_id) values(p_branch_id,p_member_id,s.id,e,k) returning id into idv;update public.membership_subscriptions_v1 set visits_used=visits_used+1 where id=s.id;return idv;end;$$;
create or replace function public.membership_class_save_v1(p_id bigint,p_branch_id bigint,p_name text,p_trainer_id bigint,p_starts_at timestamptz,p_ends_at timestamptz,p_capacity integer)
returns public.membership_classes_v1 language plpgsql security definer set search_path=public as $$declare r public.membership_classes_v1%rowtype;begin if auth.uid() is null then raise exception 'غير مصرح';end if;if not public.has_branch_access(p_branch_id) then raise exception 'ليس لديك صلاحية لهذا الفرع';end if;if p_ends_at<=p_starts_at or coalesce(p_capacity,0)<=0 then raise exception 'بيانات الحصة غير صحيحة';end if;if p_id is null then insert into public.membership_classes_v1(branch_id,name,trainer_id,starts_at,ends_at,capacity) values(p_branch_id,trim(p_name),p_trainer_id,p_starts_at,p_ends_at,p_capacity) returning * into r;else update public.membership_classes_v1 set name=trim(p_name),trainer_id=p_trainer_id,starts_at=p_starts_at,ends_at=p_ends_at,capacity=p_capacity where id=p_id returning * into r;end if;return r;end;$$;
create or replace function public.membership_book_class_v1(p_class_id bigint,p_member_id bigint,p_client_tx_id text)
returns bigint language plpgsql security definer set search_path=public as $$declare idv bigint;c public.membership_classes_v1%rowtype;k text:=nullif(trim(coalesce(p_client_tx_id,'')),'');cnt integer;begin if auth.uid() is null then raise exception 'غير مصرح';end if;if k is null then raise exception 'معرف الحركة مطلوب';end if;perform pg_advisory_xact_lock(hashtextextended('membership-book:'||k,0));select id into idv from public.membership_bookings_v1 where client_tx_id=k;if idv is not null then return idv;end if;select * into c from public.membership_classes_v1 where id=p_class_id for update;if c.status not in('scheduled','open') then raise exception 'الحصة غير متاحة';end if;select count(*) into cnt from public.membership_bookings_v1 where class_id=c.id and status='booked';if cnt>=c.capacity then raise exception 'الحصة مكتملة';end if;insert into public.membership_bookings_v1(class_id,member_id,client_tx_id) values(c.id,p_member_id,k) returning id into idv;return idv;end;$$;

alter table public.membership_members_v1 enable row level security;alter table public.membership_plans_v1 enable row level security;alter table public.membership_subscriptions_v1 enable row level security;alter table public.membership_freezes_v1 enable row level security;alter table public.membership_checkins_v1 enable row level security;alter table public.membership_trainers_v1 enable row level security;alter table public.membership_classes_v1 enable row level security;alter table public.membership_bookings_v1 enable row level security;alter table public.membership_renewal_events_v1 enable row level security;
create policy membership_members_read_v1 on public.membership_members_v1 for select to authenticated using(true);create policy membership_plans_read_v1 on public.membership_plans_v1 for select to authenticated using(active=true);create policy membership_subscriptions_read_v1 on public.membership_subscriptions_v1 for select to authenticated using(true);create policy membership_freezes_read_v1 on public.membership_freezes_v1 for select to authenticated using(true);create policy membership_checkins_read_v1 on public.membership_checkins_v1 for select to authenticated using(public.has_branch_access(branch_id));create policy membership_trainers_read_v1 on public.membership_trainers_v1 for select to authenticated using(active=true);create policy membership_classes_read_v1 on public.membership_classes_v1 for select to authenticated using(public.has_branch_access(branch_id));create policy membership_bookings_read_v1 on public.membership_bookings_v1 for select to authenticated using(true);create policy membership_renewals_read_v1 on public.membership_renewal_events_v1 for select to authenticated using(true);
grant select on public.membership_members_v1,public.membership_plans_v1,public.membership_subscriptions_v1,public.membership_freezes_v1,public.membership_checkins_v1,public.membership_trainers_v1,public.membership_classes_v1,public.membership_bookings_v1,public.membership_renewal_events_v1 to authenticated;
grant execute on function public.membership_member_create_v1(bigint,text) to authenticated;grant execute on function public.membership_plan_save_v1(bigint,text,text,integer,numeric,integer,integer,boolean) to authenticated;grant execute on function public.membership_subscribe_v1(bigint,bigint,date,numeric,text) to authenticated;grant execute on function public.membership_renew_v1(bigint,numeric,text) to authenticated;grant execute on function public.membership_freeze_v1(bigint,date,integer,text) to authenticated;grant execute on function public.membership_checkin_v1(bigint,bigint,text) to authenticated;grant execute on function public.membership_class_save_v1(bigint,bigint,text,bigint,timestamptz,timestamptz,integer) to authenticated;grant execute on function public.membership_book_class_v1(bigint,bigint,text) to authenticated;
commit;
