-- Sharawla POS — Point 4B-1 Canonical Location + Stock V2 Foundation
-- Additive schema only. branches.id remains the physical location identity and
-- branches.location_type remains constrained to branch | central_warehouse.
-- No existing inventory writer is routed to these tables by this migration.

begin;

-- -----------------------------------------------------------------------------
-- 1) Canonical balance: one row per physical location and stock item.
--    quantity_available is a projection, never an independently writable value.
-- -----------------------------------------------------------------------------
create table if not exists public.inventory_stock_balances_v2 (
  location_id bigint not null references public.branches(id) on delete restrict,
  item_kind text not null check (item_kind in ('product','variant','ingredient')),
  item_id bigint not null check (item_id > 0),
  quantity_on_hand numeric(18,3) not null default 0,
  quantity_reserved numeric(18,3) not null default 0 check (quantity_reserved >= 0),
  quantity_available numeric(18,3)
    generated always as (quantity_on_hand - quantity_reserved) stored,
  tracking_state text not null default 'tracked'
    check (tracking_state in ('tracked','untracked','blocked')),
  average_unit_cost numeric(18,4) not null default 0 check (average_unit_cost >= 0),
  last_unit_cost numeric(18,4) not null default 0 check (last_unit_cost >= 0),
  allow_negative_stock boolean not null default false,
  policy_code text not null default 'fail_closed'
    check (trim(policy_code) <> ''),
  policy_version integer not null default 1 check (policy_version > 0),
  balance_version bigint not null default 1 check (balance_version > 0),
  metadata jsonb not null default '{}'::jsonb
    check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (location_id,item_kind,item_id),
  constraint inventory_stock_balances_v2_negative_policy_check
    check (allow_negative_stock or quantity_on_hand - quantity_reserved >= 0)
);

create index if not exists inventory_stock_balances_v2_item_idx
  on public.inventory_stock_balances_v2(item_kind,item_id,location_id);
create index if not exists inventory_stock_balances_v2_location_tracking_idx
  on public.inventory_stock_balances_v2(location_id,tracking_state,item_kind,item_id);

-- -----------------------------------------------------------------------------
-- 2) Immutable movement ledger. A reservation changes reserved_quantity_delta;
--    a physical stock effect changes quantity_delta. Reversals are new rows.
-- -----------------------------------------------------------------------------
create table if not exists public.inventory_stock_movements_v2 (
  id bigint generated by default as identity primary key,
  client_tx_id text not null
    check (trim(client_tx_id) <> '' and client_tx_id=trim(client_tx_id)),
  line_key text not null
    check (trim(line_key) <> '' and line_key=trim(line_key)),
  operation_digest text not null
    check (operation_digest ~ '^[0-9a-f]{64}$' and operation_digest=lower(trim(operation_digest))),
  location_id bigint not null references public.branches(id) on delete restrict,
  item_kind text not null check (item_kind in ('product','variant','ingredient')),
  item_id bigint not null check (item_id > 0),
  movement_type text not null check (movement_type in (
    'opening','adjustment','waste','damage','stocktake',
    'reservation','reservation_release',
    'sale','sale_return','purchase_receive','purchase_return',
    'transfer_out','transfer_in','reversal'
  )),
  quantity_delta numeric(18,3) not null default 0,
  reserved_quantity_delta numeric(18,3) not null default 0,
  unit_cost numeric(18,4) check (unit_cost is null or unit_cost >= 0),
  value_delta numeric(18,4),
  quantity_on_hand_after numeric(18,3) not null,
  quantity_reserved_after numeric(18,3) not null
    check (quantity_reserved_after >= 0),
  quantity_available_after numeric(18,3)
    generated always as (quantity_on_hand_after - quantity_reserved_after) stored,
  allow_negative_stock_applied boolean not null default false,
  policy_code text not null default 'fail_closed' check (trim(policy_code) <> ''),
  policy_version integer not null default 1 check (policy_version > 0),
  source_document_type text not null
    check (trim(source_document_type) <> '' and source_document_type=trim(source_document_type)),
  source_document_id text not null
    check (trim(source_document_id) <> '' and source_document_id=trim(source_document_id)),
  counterparty_location_id bigint references public.branches(id) on delete restrict,
  employee_id bigint references public.employees(id) on delete set null,
  device_id text,
  occurred_at timestamptz not null,
  recorded_at timestamptz not null default now(),
  reversal_of_movement_id bigint
    references public.inventory_stock_movements_v2(id) on delete restrict,
  metadata jsonb not null default '{}'::jsonb
    check (jsonb_typeof(metadata) = 'object'),
  constraint inventory_stock_movements_v2_effect_check
    check (quantity_delta <> 0 or reserved_quantity_delta <> 0),
  constraint inventory_stock_movements_v2_reversal_check
    check (
      (movement_type = 'reversal' and reversal_of_movement_id is not null)
      or
      (movement_type <> 'reversal' and reversal_of_movement_id is null)
  ),
  constraint inventory_stock_movements_v2_negative_policy_check
    check (allow_negative_stock_applied or quantity_on_hand_after >= quantity_reserved_after),
  unique (client_tx_id,line_key)
);

create index if not exists inventory_stock_movements_v2_location_item_time_idx
  on public.inventory_stock_movements_v2
    (location_id,item_kind,item_id,occurred_at desc,id desc);
create index if not exists inventory_stock_movements_v2_source_document_idx
  on public.inventory_stock_movements_v2
    (source_document_type,source_document_id,id);
create unique index if not exists inventory_stock_movements_v2_reversal_uidx
  on public.inventory_stock_movements_v2(reversal_of_movement_id)
  where reversal_of_movement_id is not null;

-- -----------------------------------------------------------------------------
-- 3) Polymorphic item integrity. This trigger is internal schema enforcement;
--    it is not an operational writer and is not directly executable by clients.
-- -----------------------------------------------------------------------------
create or replace function public.inventory_stock_validate_item_v2()
returns trigger
language plpgsql
security invoker
set search_path=public
as $$
declare
  v_parent_product_id bigint;
begin
  if new.item_kind='product' then
    if not exists(select 1 from public.products where id=new.item_id) then
      raise exception 'INVENTORY_STOCK_V2_ITEM_NOT_FOUND';
    end if;
    if exists(
      select 1 from public.product_variants pv
      where pv.product_id=new.item_id and pv.is_stock_unit=true
    ) then
      raise exception 'INVENTORY_STOCK_V2_PRODUCT_HAS_STOCK_VARIANTS';
    end if;
  elsif new.item_kind='variant' then
    select pv.product_id into v_parent_product_id
    from public.product_variants pv
    join public.products p on p.id=pv.product_id
    where pv.id=new.item_id and pv.is_stock_unit=true;
    if not found or v_parent_product_id is null then
      raise exception 'INVENTORY_STOCK_V2_VARIANT_NOT_STOCK_UNIT';
    end if;
    if exists(
      select 1 from public.inventory_stock_balances_v2 b
      where b.location_id=new.location_id
        and b.item_kind='product'
        and b.item_id=v_parent_product_id
    ) or exists(
      select 1 from public.inventory_stock_movements_v2 m
      where m.location_id=new.location_id
        and m.item_kind='product'
        and m.item_id=v_parent_product_id
    ) then
      raise exception 'INVENTORY_STOCK_V2_COMPETING_PRODUCT_OWNERSHIP';
    end if;
  elsif new.item_kind='ingredient' then
    if not exists(select 1 from public.ingredients where id=new.item_id) then
      raise exception 'INVENTORY_STOCK_V2_ITEM_NOT_FOUND';
    end if;
  else
    raise exception 'INVENTORY_STOCK_V2_INVALID_ITEM_KIND';
  end if;
  return new;
end;
$$;

drop trigger if exists inventory_stock_balances_v2_validate_item
  on public.inventory_stock_balances_v2;
create trigger inventory_stock_balances_v2_validate_item
before insert or update of item_kind,item_id
on public.inventory_stock_balances_v2
for each row execute function public.inventory_stock_validate_item_v2();

drop trigger if exists inventory_stock_movements_v2_validate_item
  on public.inventory_stock_movements_v2;
create trigger inventory_stock_movements_v2_validate_item
before insert
on public.inventory_stock_movements_v2
for each row execute function public.inventory_stock_validate_item_v2();

-- Source identities may not be deleted while canonical V2 balance/history
-- references exist. With no V2 reference, existing delete behavior is unchanged.
create or replace function public.inventory_stock_source_delete_guard_v2()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare
  v_kind text;
begin
  v_kind:=case tg_table_name
    when 'products' then 'product'
    when 'product_variants' then 'variant'
    when 'ingredients' then 'ingredient'
    else null
  end;
  if v_kind is null then
    raise exception 'INVENTORY_STOCK_V2_INVALID_SOURCE_GUARD';
  end if;

  if exists(
    select 1 from public.inventory_stock_balances_v2 b
    where b.item_kind=v_kind and b.item_id=old.id
  ) or exists(
    select 1 from public.inventory_stock_movements_v2 m
    where m.item_kind=v_kind and m.item_id=old.id
  ) then
    raise exception 'INVENTORY_STOCK_V2_SOURCE_IDENTITY_REFERENCED';
  end if;

  -- Product deletion cascades to product_variants in the existing schema. Check
  -- dependent canonical variant identities explicitly before that cascade.
  if v_kind='product' and exists(
    select 1
    from public.product_variants pv
    where pv.product_id=old.id
      and (
        exists(
          select 1 from public.inventory_stock_balances_v2 b
          where b.item_kind='variant' and b.item_id=pv.id
        )
        or exists(
          select 1 from public.inventory_stock_movements_v2 m
          where m.item_kind='variant' and m.item_id=pv.id
        )
      )
  ) then
    raise exception 'INVENTORY_STOCK_V2_SOURCE_IDENTITY_REFERENCED';
  end if;

  return old;
end;
$$;

drop trigger if exists inventory_stock_products_delete_guard_v2 on public.products;
create trigger inventory_stock_products_delete_guard_v2
before delete on public.products
for each row execute function public.inventory_stock_source_delete_guard_v2();

drop trigger if exists inventory_stock_variants_delete_guard_v2 on public.product_variants;
create trigger inventory_stock_variants_delete_guard_v2
before delete on public.product_variants
for each row execute function public.inventory_stock_source_delete_guard_v2();

drop trigger if exists inventory_stock_ingredients_delete_guard_v2 on public.ingredients;
create trigger inventory_stock_ingredients_delete_guard_v2
before delete on public.ingredients
for each row execute function public.inventory_stock_source_delete_guard_v2();

-- is_stock_unit is the deployed variant ownership switch. Prevent changing that
-- identity contract around canonical V2 rows, and prevent enabling variant stock
-- ownership while a parent-product V2 identity already exists.
create or replace function public.inventory_stock_variant_identity_guard_v2()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  if tg_op='UPDATE' and (
    new.product_id is distinct from old.product_id
    or new.is_stock_unit is distinct from old.is_stock_unit
  ) and (
    exists(
      select 1 from public.inventory_stock_balances_v2 b
      where b.item_kind='variant' and b.item_id=old.id
    )
    or exists(
      select 1 from public.inventory_stock_movements_v2 m
      where m.item_kind='variant' and m.item_id=old.id
    )
  ) then
    raise exception 'INVENTORY_STOCK_V2_VARIANT_IDENTITY_REFERENCED';
  end if;

  if new.is_stock_unit=true and (
    exists(
      select 1 from public.inventory_stock_balances_v2 b
      where b.item_kind='product' and b.item_id=new.product_id
    )
    or exists(
      select 1 from public.inventory_stock_movements_v2 m
      where m.item_kind='product' and m.item_id=new.product_id
    )
  ) then
    raise exception 'INVENTORY_STOCK_V2_COMPETING_PRODUCT_OWNERSHIP';
  end if;

  return new;
end;
$$;

drop trigger if exists inventory_stock_variant_identity_guard_v2 on public.product_variants;
create trigger inventory_stock_variant_identity_guard_v2
before insert or update on public.product_variants
for each row execute function public.inventory_stock_variant_identity_guard_v2();

-- The canonical ledger is append-only. Corrections must use a reversal row.
create or replace function public.inventory_stock_movement_immutable_v2()
returns trigger
language plpgsql
set search_path=public
as $$
begin
  raise exception 'INVENTORY_STOCK_V2_LEDGER_IMMUTABLE';
end;
$$;

drop trigger if exists inventory_stock_movements_v2_immutable
  on public.inventory_stock_movements_v2;
create trigger inventory_stock_movements_v2_immutable
before update or delete
on public.inventory_stock_movements_v2
for each row execute function public.inventory_stock_movement_immutable_v2();

-- A reversal is a new, exact inverse of one original movement. It cannot change
-- the stock identity or reverse another reversal.
create or replace function public.inventory_stock_reversal_validate_v2()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare
  v_original public.inventory_stock_movements_v2%rowtype;
begin
  if new.reversal_of_movement_id is null then
    return new;
  end if;

  select * into v_original
  from public.inventory_stock_movements_v2 m
  where m.id=new.reversal_of_movement_id
  for update;
  if not found then
    raise exception 'INVENTORY_STOCK_V2_REVERSAL_SOURCE_NOT_FOUND';
  end if;
  if v_original.movement_type='reversal' or v_original.reversal_of_movement_id is not null then
    raise exception 'INVENTORY_STOCK_V2_REVERSAL_OF_REVERSAL';
  end if;
  if new.location_id<>v_original.location_id
    or new.item_kind<>v_original.item_kind
    or new.item_id<>v_original.item_id then
    raise exception 'INVENTORY_STOCK_V2_REVERSAL_IDENTITY_MISMATCH';
  end if;
  if new.quantity_delta<>-v_original.quantity_delta then
    raise exception 'INVENTORY_STOCK_V2_REVERSAL_QUANTITY_MISMATCH';
  end if;
  if new.reserved_quantity_delta<>-v_original.reserved_quantity_delta then
    raise exception 'INVENTORY_STOCK_V2_REVERSAL_RESERVATION_MISMATCH';
  end if;
  if (new.value_delta is null)<>(v_original.value_delta is null)
    or (
      new.value_delta is not null
      and v_original.value_delta is not null
      and new.value_delta<>-v_original.value_delta
    ) then
    raise exception 'INVENTORY_STOCK_V2_REVERSAL_VALUE_MISMATCH';
  end if;

  return new;
end;
$$;

drop trigger if exists inventory_stock_movements_v2_reversal_validate
  on public.inventory_stock_movements_v2;
create trigger inventory_stock_movements_v2_reversal_validate
before insert
on public.inventory_stock_movements_v2
for each row execute function public.inventory_stock_reversal_validate_v2();

-- -----------------------------------------------------------------------------
-- 4) Future-writer contracts. These functions are intentionally internal only.
--    No current application path is granted execution or routed through them.
-- -----------------------------------------------------------------------------
create or replace function public.inventory_stock_resolve_policy_v2(
  p_location_id bigint,
  p_item_kind text,
  p_item_id bigint
) returns table(
  allow_negative_stock boolean,
  policy_code text,
  policy_version integer,
  policy_source text
)
language plpgsql
stable
security invoker
set search_path=public
as $$
begin
  if not exists(select 1 from public.branches where id=p_location_id) then
    raise exception 'INVENTORY_STOCK_V2_LOCATION_REQUIRED';
  end if;
  if p_item_kind is null or p_item_kind not in ('product','variant','ingredient') or coalesce(p_item_id,0)<=0 then
    raise exception 'INVENTORY_STOCK_V2_ITEM_REQUIRED';
  end if;

  return query
  select b.allow_negative_stock,b.policy_code,b.policy_version,'balance'::text
  from public.inventory_stock_balances_v2 b
  where b.location_id=p_location_id
    and b.item_kind=p_item_kind
    and b.item_id=p_item_id;

  if not found then
    return query select false,'fail_closed'::text,1,'default_fail_closed'::text;
  end if;
end;
$$;

create or replace function public.inventory_stock_resolve_idempotency_v2(
  p_client_tx_id text,
  p_line_key text,
  p_operation_digest text
) returns table(
  movement_id bigint,
  reuse_existing boolean
)
language plpgsql
security invoker
set search_path=public
as $$
declare
  v_existing public.inventory_stock_movements_v2%rowtype;
  v_client_tx_id text:=trim(coalesce(p_client_tx_id,''));
  v_line_key text:=trim(coalesce(p_line_key,''));
  v_digest text:=lower(trim(coalesce(p_operation_digest,'')));
begin
  if v_client_tx_id='' or v_line_key='' or v_digest !~ '^[0-9a-f]{64}$' then
    raise exception 'INVENTORY_STOCK_V2_IDEMPOTENCY_KEY_REQUIRED';
  end if;

  -- The future canonical writer calls this inside its transaction. The lock
  -- serializes a key through the following insert, while the unique constraint
  -- remains the final database-level duplicate guard.
  perform pg_advisory_xact_lock(
    hashtextextended('inventory-stock-v2:'||v_client_tx_id||':'||v_line_key,0)
  );

  select * into v_existing
  from public.inventory_stock_movements_v2 m
  where m.client_tx_id=v_client_tx_id and m.line_key=v_line_key;

  if not found then
    return query select null::bigint,false;
    return;
  end if;

  if v_existing.operation_digest<>v_digest then
    raise exception 'INVENTORY_STOCK_V2_IDEMPOTENCY_CONFLICT';
  end if;

  return query select v_existing.id,true;
end;
$$;

-- -----------------------------------------------------------------------------
-- 5) Read boundary. Clients may inspect only locations they can access. Direct
--    writes and internal helper execution stay closed until a future writer gate.
-- -----------------------------------------------------------------------------
alter table public.inventory_stock_balances_v2 enable row level security;
alter table public.inventory_stock_movements_v2 enable row level security;

drop policy if exists inventory_stock_balances_v2_read on public.inventory_stock_balances_v2;
create policy inventory_stock_balances_v2_read
on public.inventory_stock_balances_v2
for select to authenticated
using (public.has_branch_access(location_id));

drop policy if exists inventory_stock_movements_v2_read on public.inventory_stock_movements_v2;
create policy inventory_stock_movements_v2_read
on public.inventory_stock_movements_v2
for select to authenticated
using (public.has_branch_access(location_id));

revoke all on public.inventory_stock_balances_v2 from anon,authenticated;
revoke all on public.inventory_stock_movements_v2 from anon,authenticated;
revoke all on function public.inventory_stock_validate_item_v2() from public,anon,authenticated;
revoke all on function public.inventory_stock_source_delete_guard_v2() from public,anon,authenticated;
revoke all on function public.inventory_stock_variant_identity_guard_v2() from public,anon,authenticated;
revoke all on function public.inventory_stock_movement_immutable_v2() from public,anon,authenticated;
revoke all on function public.inventory_stock_reversal_validate_v2() from public,anon,authenticated;
revoke all on function public.inventory_stock_resolve_policy_v2(bigint,text,bigint) from public,anon,authenticated;
revoke all on function public.inventory_stock_resolve_idempotency_v2(text,text,text) from public,anon,authenticated;

grant select on public.inventory_stock_balances_v2 to authenticated;
grant select on public.inventory_stock_movements_v2 to authenticated;

comment on table public.inventory_stock_balances_v2 is
  'Point 4 canonical stock balance foundation. Not populated or operationally owned until a later cutover gate.';
comment on table public.inventory_stock_movements_v2 is
  'Point 4 immutable canonical stock ledger foundation. Existing inventory writers do not write here.';
comment on column public.inventory_stock_movements_v2.operation_digest is
  'Lowercase SHA-256 of the future writer canonical operation; used to reject conflicting idempotency replays.';
comment on function public.inventory_stock_resolve_policy_v2(bigint,text,bigint) is
  'Internal future-writer policy contract. Missing balance policy resolves to allow_negative_stock=false.';
comment on function public.inventory_stock_resolve_idempotency_v2(text,text,text) is
  'Internal replay contract: matching key+digest reuses the movement id; conflicting digest fails closed.';

commit;
