-- SOURCE ONLY. Do not deploy without explicit authorization.
-- Central Warehouse state-only lifecycle replay owners.
create or replace function public.offline_inventory_supply_request_submit_v1(p_request_id bigint,p_client_tx_id text,p_payload_digest text) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare t text:=nullif(trim(coalesce(p_client_tx_id,'')),'');d text:=nullif(trim(coalesce(p_payload_digest,'')),'');r public.offline_restaurant_reference_receipts_v1%rowtype;i bigint;j jsonb;begin
 if auth.uid() is null or t is null or d is null then raise exception 'OFFLINE_SUPPLY_SUBMIT_IDENTITY_REQUIRED';end if;perform pg_advisory_xact_lock(hashtextextended('offline-supply:'||t,0));select * into r from public.offline_restaurant_reference_receipts_v1 where client_tx_id=t;if found then if r.operation_type<>'inventory_supply_request_submit' or r.payload_digest<>d then raise exception 'OFFLINE_RESTAURANT_REFERENCE_REPLAY_MISMATCH';end if;return r.result_json||jsonb_build_object('idempotent_replay',true);end if;
 i:=public.inventory_supply_request_submit_v1(p_request_id);j:=jsonb_build_object('ok',true,'request_id',i,'client_tx_id',t);insert into public.offline_restaurant_reference_receipts_v1(client_tx_id,operation_type,payload_digest,entity_id,result_json)values(t,'inventory_supply_request_submit',d,i,j);return j;end;$$;
create or replace function public.offline_inventory_supply_request_decide_v1(p_request_id bigint,p_approve boolean,p_approved_items jsonb,p_note text,p_client_tx_id text,p_payload_digest text) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare t text:=nullif(trim(coalesce(p_client_tx_id,'')),'');d text:=nullif(trim(coalesce(p_payload_digest,'')),'');r public.offline_restaurant_reference_receipts_v1%rowtype;i bigint;j jsonb;begin
 if auth.uid() is null or t is null or d is null then raise exception 'OFFLINE_SUPPLY_DECIDE_IDENTITY_REQUIRED';end if;perform pg_advisory_xact_lock(hashtextextended('offline-supply:'||t,0));select * into r from public.offline_restaurant_reference_receipts_v1 where client_tx_id=t;if found then if r.operation_type<>'inventory_supply_request_decide' or r.payload_digest<>d then raise exception 'OFFLINE_RESTAURANT_REFERENCE_REPLAY_MISMATCH';end if;return r.result_json||jsonb_build_object('idempotent_replay',true);end if;
 i:=public.inventory_supply_request_decide_v1(p_request_id,p_approve,p_approved_items,p_note);j:=jsonb_build_object('ok',true,'request_id',i,'client_tx_id',t);insert into public.offline_restaurant_reference_receipts_v1(client_tx_id,operation_type,payload_digest,entity_id,result_json)values(t,'inventory_supply_request_decide',d,i,j);return j;end;$$;
create or replace function public.offline_inventory_supply_request_prepare_v1(p_request_id bigint,p_note text,p_client_tx_id text,p_payload_digest text) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare t text:=nullif(trim(coalesce(p_client_tx_id,'')),'');d text:=nullif(trim(coalesce(p_payload_digest,'')),'');r public.offline_restaurant_reference_receipts_v1%rowtype;i bigint;j jsonb;begin
 if auth.uid() is null or t is null or d is null then raise exception 'OFFLINE_SUPPLY_PREPARE_IDENTITY_REQUIRED';end if;perform pg_advisory_xact_lock(hashtextextended('offline-supply:'||t,0));select * into r from public.offline_restaurant_reference_receipts_v1 where client_tx_id=t;if found then if r.operation_type<>'inventory_supply_request_prepare' or r.payload_digest<>d then raise exception 'OFFLINE_RESTAURANT_REFERENCE_REPLAY_MISMATCH';end if;return r.result_json||jsonb_build_object('idempotent_replay',true);end if;
 i:=public.inventory_supply_request_prepare_v1(p_request_id,p_note);j:=jsonb_build_object('ok',true,'request_id',i,'client_tx_id',t);insert into public.offline_restaurant_reference_receipts_v1(client_tx_id,operation_type,payload_digest,entity_id,result_json)values(t,'inventory_supply_request_prepare',d,i,j);return j;end;$$;
revoke all on function public.offline_inventory_supply_request_submit_v1(bigint,text,text) from public,anon;grant execute on function public.offline_inventory_supply_request_submit_v1(bigint,text,text) to authenticated;
revoke all on function public.offline_inventory_supply_request_decide_v1(bigint,boolean,jsonb,text,text,text) from public,anon;grant execute on function public.offline_inventory_supply_request_decide_v1(bigint,boolean,jsonb,text,text,text) to authenticated;
revoke all on function public.offline_inventory_supply_request_prepare_v1(bigint,text,text,text) from public,anon;grant execute on function public.offline_inventory_supply_request_prepare_v1(bigint,text,text,text) to authenticated;