-- Sharawla POS — Point 4D-1 Purchasing/AP source-only contract.
-- Existing PR/PO/GRN/invoice runtime is unchanged and not connected here.
begin;
create table if not exists public.supplier_payables_v1(
 id bigint generated by default as identity primary key,
 document_uid uuid not null unique check(document_uid::text~'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
 source_document_type text not null check(source_document_type='supplier_payable'),
 source_document_id text not null unique check(source_document_id='uuid:'||document_uid::text),
 branch_id bigint not null references public.branches(id) on delete restrict,
 supplier_id bigint not null references public.retail_suppliers(id) on delete restrict,
 supplier_invoice_id bigint not null unique references public.retail_supplier_invoices(id) on delete restrict,
 purchase_order_id bigint references public.retail_purchase_orders(id) on delete restrict,
 currency_code text not null,original_amount numeric(18,2) not null check(original_amount>=0),
 settled_amount numeric(18,2) not null default 0 check(settled_amount>=0),
 credited_amount numeric(18,2) not null default 0 check(credited_amount>=0),
 outstanding_amount numeric(18,2) generated always as(original_amount-settled_amount-credited_amount) stored,
 status text not null check(status in('APPROVED','PARTIALLY_SETTLED','SETTLED','DISPUTED','FORWARD_RECOVERY_REQUIRED')),
 source_digest text not null check(source_digest~'^[0-9a-f]{64}$'),client_tx_id text not null unique,
 approved_at timestamptz not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 check(settled_amount+credited_amount<=original_amount));
create table if not exists public.supplier_payable_credits_v1(
 id bigint generated by default as identity primary key,document_uid uuid not null unique check(document_uid::text~'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
 source_document_type text not null check(source_document_type='purchase_return'),source_document_id text not null unique check(source_document_id='uuid:'||document_uid::text),
 payable_id bigint not null references public.supplier_payables_v1(id) on delete restrict,
 supplier_return_id bigint not null unique references public.retail_supplier_returns(id) on delete restrict,
 credit_amount numeric(18,2) not null check(credit_amount>0),client_tx_id text not null unique,
 operation_digest text not null check(operation_digest~'^[0-9a-f]{64}$'),lineage jsonb not null check(jsonb_typeof(lineage)='object'),created_at timestamptz not null default now());
create table if not exists public.supplier_payments_v1(
 id bigint generated by default as identity primary key,document_uid uuid not null unique check(document_uid::text~'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
 source_document_type text not null check(source_document_type='supplier_payment'),source_document_id text not null unique check(source_document_id='uuid:'||document_uid::text),
 branch_id bigint not null references public.branches(id) on delete restrict,
 supplier_id bigint not null references public.retail_suppliers(id) on delete restrict,currency_code text not null,
 payment_amount numeric(18,2) not null check(payment_amount>0),allocated_amount numeric(18,2) not null default 0 check(allocated_amount>=0),
 unallocated_amount numeric(18,2) generated always as(payment_amount-allocated_amount) stored,
 payment_method_id bigint references public.payment_methods(id) on delete restrict,
 treasury_movement_id bigint unique references public.treasury_movements(id) on delete restrict,
 client_tx_id text not null unique,operation_digest text not null check(operation_digest~'^[0-9a-f]{64}$'),
 status text not null check(status in('CAPTURED','PARTIALLY_ALLOCATED','ALLOCATED','REVERSED','FORWARD_RECOVERY_REQUIRED')),
 paid_at timestamptz not null,created_at timestamptz not null default now(),check(allocated_amount<=payment_amount));
create table if not exists public.supplier_payment_allocations_v1(
 id bigint generated by default as identity primary key,payment_id bigint not null references public.supplier_payments_v1(id) on delete restrict,
 payable_id bigint not null references public.supplier_payables_v1(id) on delete restrict,amount numeric(18,2) not null check(amount>0),
 line_uid uuid not null check(line_uid::text~'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
 target_source_document_type text not null check(target_source_document_type='supplier_payable'),
 target_source_document_id text not null check(target_source_document_id~'^(uuid:[0-9a-f-]{36}|db:[1-9][0-9]*)$'),
 line_key text not null check(line_key!~':v1:'),operation_digest text not null check(operation_digest~'^[0-9a-f]{64}$'),created_at timestamptz not null default now(),
 unique(payment_id,line_uid),unique(payment_id,line_key));
create table if not exists public.supplier_payable_landed_cost_links_v1(
 payable_id bigint not null references public.supplier_payables_v1(id) on delete restrict,
 landed_cost_id bigint not null references public.retail_landed_costs(id) on delete restrict,
 linked_amount numeric(18,2) not null check(linked_amount>0),lineage jsonb not null check(jsonb_typeof(lineage)='object'),
 primary key(payable_id,landed_cost_id));
create table if not exists public.supplier_ap_events_v1(
 id bigint generated by default as identity primary key,event_type text not null check(event_type in('PAYABLE_APPROVED','CREDIT_APPLIED','PAYMENT_CAPTURED','PAYMENT_ALLOCATED','PAYMENT_REVERSED','RECOVERY')),
 entity_type text not null check(entity_type in('payable','credit','payment','allocation')),entity_id bigint not null,
 client_tx_id text not null,operation_digest text not null check(operation_digest~'^[0-9a-f]{64}$'),payload jsonb not null check(jsonb_typeof(payload)='object'),
 recorded_at timestamptz not null default now(),unique(event_type,client_tx_id));
create or replace function public.supplier_ap_event_immutable_v1() returns trigger language plpgsql security definer set search_path='' as $$begin raise exception 'SUPPLIER_AP_EVENT_IMMUTABLE';end$$;
drop trigger if exists supplier_ap_events_v1_immutable on public.supplier_ap_events_v1;create trigger supplier_ap_events_v1_immutable before update or delete on public.supplier_ap_events_v1 for each row execute function public.supplier_ap_event_immutable_v1();
create or replace function public.supplier_ap_identity_guard_v1() returns trigger language plpgsql security definer set search_path='' as $$declare v_type text;v_id text;begin
 if tg_op='UPDATE' then
  if tg_table_name='supplier_payables_v1' and (new.document_uid is distinct from old.document_uid or new.source_document_type is distinct from old.source_document_type or new.source_document_id is distinct from old.source_document_id or new.supplier_invoice_id is distinct from old.supplier_invoice_id or new.client_tx_id is distinct from old.client_tx_id or new.source_digest is distinct from old.source_digest) then raise exception 'SUPPLIER_AP_V1_IDENTITY_IMMUTABLE';end if;
  if tg_table_name='supplier_payable_credits_v1' and (new.document_uid is distinct from old.document_uid or new.source_document_type is distinct from old.source_document_type or new.source_document_id is distinct from old.source_document_id or new.payable_id is distinct from old.payable_id or new.supplier_return_id is distinct from old.supplier_return_id or new.client_tx_id is distinct from old.client_tx_id or new.operation_digest is distinct from old.operation_digest) then raise exception 'SUPPLIER_AP_V1_IDENTITY_IMMUTABLE';end if;
  if tg_table_name='supplier_payments_v1' and (new.document_uid is distinct from old.document_uid or new.source_document_type is distinct from old.source_document_type or new.source_document_id is distinct from old.source_document_id or new.client_tx_id is distinct from old.client_tx_id or new.operation_digest is distinct from old.operation_digest) then raise exception 'SUPPLIER_AP_V1_IDENTITY_IMMUTABLE';end if;
  if tg_table_name='supplier_payment_allocations_v1' and (new.payment_id is distinct from old.payment_id or new.payable_id is distinct from old.payable_id or new.line_uid is distinct from old.line_uid or new.line_key is distinct from old.line_key or new.target_source_document_type is distinct from old.target_source_document_type or new.target_source_document_id is distinct from old.target_source_document_id) then raise exception 'SUPPLIER_AP_V1_IDENTITY_IMMUTABLE';end if;
 end if;
 if tg_table_name='supplier_payment_allocations_v1' then select source_document_type,source_document_id into strict v_type,v_id from public.supplier_payables_v1 where id=new.payable_id;if new.target_source_document_type<>v_type or new.target_source_document_id<>v_id then raise exception 'SUPPLIER_AP_V1_CANONICAL_TARGET_MISMATCH';end if;end if;
 return new;end$$;
drop trigger if exists supplier_payables_v1_identity_guard on public.supplier_payables_v1;create trigger supplier_payables_v1_identity_guard before update on public.supplier_payables_v1 for each row execute function public.supplier_ap_identity_guard_v1();
drop trigger if exists supplier_payable_credits_v1_identity_guard on public.supplier_payable_credits_v1;create trigger supplier_payable_credits_v1_identity_guard before update on public.supplier_payable_credits_v1 for each row execute function public.supplier_ap_identity_guard_v1();
drop trigger if exists supplier_payments_v1_identity_guard on public.supplier_payments_v1;create trigger supplier_payments_v1_identity_guard before update on public.supplier_payments_v1 for each row execute function public.supplier_ap_identity_guard_v1();
drop trigger if exists supplier_payment_allocations_v1_identity_guard on public.supplier_payment_allocations_v1;create trigger supplier_payment_allocations_v1_identity_guard before insert or update on public.supplier_payment_allocations_v1 for each row execute function public.supplier_ap_identity_guard_v1();
create or replace function public.supplier_ap_point4d_activation_allowed_v1() returns boolean language sql stable security definer set search_path='' as $$select false$$;
create or replace function public.supplier_ap_canonical_lines_v1(p_operation_type text,p_lines jsonb) returns jsonb language plpgsql immutable set search_path='' as $$
declare l jsonb;v jsonb;v_result jsonb:='[]'::jsonb;v_uid text;v_target_type text;v_target_id text;
begin
 if p_lines is null or jsonb_typeof(p_lines)<>'array' then raise exception 'SUPPLIER_AP_V1_LINES_ARRAY_REQUIRED';end if;
 for l in select value from jsonb_array_elements(p_lines) loop
  perform public.point4_identity_assert_allowed_keys_v1(l,array['line_uid','target_source_document_type','target_source_document_id','item_kind','item_id','quantity','unit_cost','amount','currency_code']);
  v_uid:=public.point4_identity_uuid_v4_v1(l->>'line_uid');
  v_target_type:=lower(trim(coalesce(l->>'target_source_document_type','')));
  v_target_id:=lower(trim(coalesce(l->>'target_source_document_id','')));
  if lower(trim(p_operation_type)) in('payment_allocate','payment_allocated','allocation')
    and (v_target_type<>'supplier_payable' or v_target_id='')
  then raise exception 'SUPPLIER_AP_V1_ALLOCATION_CANONICAL_TARGET_REQUIRED';end if;
  if (v_target_type='')<>(v_target_id='') then raise exception 'SUPPLIER_AP_V1_CANONICAL_TARGET_INCOMPLETE';end if;
  if v_target_id<>'' then
   v_target_id:=public.point4_identity_source_document_id_v1(v_target_type,v_target_id,false);
  end if;
  v:=jsonb_build_object(
    'line_uid',v_uid,
    'line_key',public.point4_identity_effect_line_key_v1('ap',lower(trim(p_operation_type)),v_uid,null,null),
    'target_source_document_type',case when v_target_id='' then null else v_target_type end,
    'target_source_document_id',case when v_target_id='' then null else v_target_id end,
    'item_kind',case when not l?'item_kind' or l->'item_kind'='null'::jsonb then null else lower(trim(l->>'item_kind')) end,
    'item_id',case when not l?'item_id' or l->'item_id'='null'::jsonb then null else public.point4_identity_bigint_v1(l->'item_id',true) end,
    'quantity',case when not l?'quantity' or l->'quantity'='null'::jsonb then null else public.point4_identity_decimal_v1((l->>'quantity')::numeric,3) end,
    'unit_cost',case when not l?'unit_cost' or l->'unit_cost'='null'::jsonb then null else public.point4_identity_decimal_v1((l->>'unit_cost')::numeric,4) end,
    'amount',case when not l?'amount' or l->'amount'='null'::jsonb then null else public.point4_identity_decimal_v1((l->>'amount')::numeric,2) end,
    'currency_code',case when not l?'currency_code' or l->'currency_code'='null'::jsonb then null else upper(trim(l->>'currency_code')) end
  );
  if (v->>'item_kind') is not null and v->>'item_kind' not in('product','variant','ingredient') then raise exception 'SUPPLIER_AP_V1_ITEM_KIND_INVALID';end if;
  if (v->>'currency_code') is not null and v->>'currency_code'!~'^[A-Z]{3}$' then raise exception 'SUPPLIER_AP_V1_CURRENCY_INVALID';end if;
  v_result:=v_result||jsonb_build_array(v);
 end loop;
 return public.point4_identity_canonical_lines_v1(v_result);
end$$;
create or replace function public.supplier_ap_intent_digest_v1(p_operation_type text,p_client_tx_id text,p_source_type text,p_source_document_id text,p_offline_capable boolean,p_branch_id bigint,p_amount numeric,p_currency_code text,p_lines jsonb,p_effective_date date default null) returns text language sql immutable set search_path='' as $$
 select public.point4_identity_operation_digest_v1(
  p_operation_type,p_client_tx_id,p_source_type,p_source_document_id,p_offline_capable,
  p_branch_id,p_currency_code,jsonb_build_object('amount',public.point4_identity_decimal_v1(p_amount,2)),
  public.supplier_ap_canonical_lines_v1(p_operation_type,p_lines),null,p_effective_date
 )$$;
create or replace function public.supplier_ap_assert_activation_v1() returns void language plpgsql stable security definer set search_path='' as $$begin if not public.supplier_ap_point4d_activation_allowed_v1() then raise exception 'SUPPLIER_AP_V1_ACTIVATION_BLOCKED';end if;end$$;
alter table public.supplier_payables_v1 enable row level security;alter table public.supplier_payable_credits_v1 enable row level security;alter table public.supplier_payments_v1 enable row level security;alter table public.supplier_payment_allocations_v1 enable row level security;alter table public.supplier_payable_landed_cost_links_v1 enable row level security;alter table public.supplier_ap_events_v1 enable row level security;
revoke all on public.supplier_payables_v1,public.supplier_payable_credits_v1,public.supplier_payments_v1,public.supplier_payment_allocations_v1,public.supplier_payable_landed_cost_links_v1,public.supplier_ap_events_v1 from public,anon,authenticated;
revoke all on function public.supplier_ap_event_immutable_v1() from public,anon,authenticated;revoke all on function public.supplier_ap_identity_guard_v1() from public,anon,authenticated;revoke all on function public.supplier_ap_point4d_activation_allowed_v1() from public,anon,authenticated;revoke all on function public.supplier_ap_canonical_lines_v1(text,jsonb) from public,anon,authenticated;revoke all on function public.supplier_ap_intent_digest_v1(text,text,text,text,boolean,bigint,numeric,text,jsonb,date) from public,anon,authenticated;revoke all on function public.supplier_ap_assert_activation_v1() from public,anon,authenticated;
comment on table public.supplier_payables_v1 is 'Point 4D source-only authoritative AP contract; no current purchasing or treasury workflow is connected.';
commit;
