-- Sharawla POS — Point 4C-1 Canonical Transfer source-only contract.
begin;
create table if not exists public.inventory_transfer_operations_v2(
 id bigint generated by default as identity primary key,
 document_uid uuid not null unique check(document_uid::text~'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
 source_document_id text not null unique check(source_document_id='uuid:'||document_uid::text),
 supply_request_id bigint not null unique references public.inventory_supply_requests(id) on delete restrict,
 source_location_id bigint not null references public.branches(id) on delete restrict,
 destination_location_id bigint not null references public.branches(id) on delete restrict,
 lifecycle_state text not null check(lifecycle_state in('REQUESTED','APPROVED','RESERVED','PREPARING','IN_TRANSIT','PARTIALLY_RECEIVED','RECEIVED','CANCELLED','FORWARD_RECOVERY_REQUIRED')),
 ownership_state text not null default 'SOURCE_CONTRACT_ONLY' check(ownership_state in('SOURCE_CONTRACT_ONLY','CANONICAL_ACTIVE','FORWARD_RECOVERY_REQUIRED')),
 operation_digest text not null check(operation_digest~'^[0-9a-f]{64}$'),
 source_document_digest text not null check(source_document_digest~'^[0-9a-f]{64}$'),
 cutover_plan_digest text check(cutover_plan_digest is null or cutover_plan_digest~'^[0-9a-f]{64}$'),
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 check(source_location_id<>destination_location_id),
 check(ownership_state<>'CANONICAL_ACTIVE' or cutover_plan_digest is not null));
create table if not exists public.inventory_transfer_lines_v2(
 transfer_operation_id bigint not null references public.inventory_transfer_operations_v2(id) on delete restrict,
 supply_request_item_id bigint not null unique references public.inventory_supply_request_items(id) on delete restrict,
 line_uid uuid not null check(line_uid::text~'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
 line_key text not null check(line_key!~':v1:'),item_kind text not null check(item_kind in('product','ingredient')),item_id bigint not null check(item_id>0),
 quantity_requested numeric(18,3) not null check(quantity_requested>0),quantity_approved numeric(18,3) not null check(quantity_approved>=0),
 quantity_reserved numeric(18,3) not null default 0 check(quantity_reserved>=0),quantity_dispatched numeric(18,3) not null default 0 check(quantity_dispatched>=0),
 quantity_received numeric(18,3) not null default 0 check(quantity_received>=0),quantity_damaged numeric(18,3) not null default 0 check(quantity_damaged>=0),
 quantity_shortage numeric(18,3) not null default 0 check(quantity_shortage>=0),
 quantity_in_transit numeric(18,3) generated always as(quantity_dispatched-quantity_received-quantity_damaged-quantity_shortage) stored,
 unit_cost_snapshot numeric(18,4) not null check(unit_cost_snapshot>=0),
 dispatched_value numeric(18,4) generated always as(round(quantity_dispatched*unit_cost_snapshot,4)) stored,
 received_value numeric(18,4) generated always as(round(quantity_received*unit_cost_snapshot,4)) stored,
 damaged_value numeric(18,4) generated always as(round(quantity_damaged*unit_cost_snapshot,4)) stored,
 shortage_value numeric(18,4) generated always as(round(quantity_shortage*unit_cost_snapshot,4)) stored,
 in_transit_value numeric(18,4) generated always as(round((quantity_dispatched-quantity_received-quantity_damaged-quantity_shortage)*unit_cost_snapshot,4)) stored,
 lineage jsonb not null check(jsonb_typeof(lineage)='object'),primary key(transfer_operation_id,line_key),unique(transfer_operation_id,line_uid),
 check(quantity_approved<=quantity_requested and quantity_reserved<=quantity_approved and quantity_dispatched<=quantity_approved and quantity_received+quantity_damaged+quantity_shortage<=quantity_dispatched),
 constraint inventory_transfer_value_conservation_v2 check(dispatched_value=received_value+damaged_value+shortage_value+in_transit_value));
create table if not exists public.inventory_transfer_events_v2(
 id bigint generated by default as identity primary key,transfer_operation_id bigint not null references public.inventory_transfer_operations_v2(id) on delete restrict,
 operation_type text not null check(operation_type in('REQUEST','APPROVE','RESERVE','PREPARE','DISPATCH','RECEIVE','FINALIZE','CANCEL','RECOVERY')),
 client_tx_id text not null check(btrim(client_tx_id)<>''),operation_digest text not null check(operation_digest~'^[0-9a-f]{64}$'),
 from_state text,to_state text not null,payload jsonb not null check(jsonb_typeof(payload)='object'),employee_id bigint references public.employees(id) on delete restrict,
 recorded_at timestamptz not null default now(),unique(operation_type,client_tx_id),unique(id,transfer_operation_id,operation_type));
create table if not exists public.inventory_transfer_event_lines_v2(
 event_id bigint not null references public.inventory_transfer_events_v2(id) on delete restrict,
 transfer_operation_id bigint not null,line_uid uuid not null check(line_uid::text~'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
 transfer_line_uid uuid not null,operation_type text not null,
 line_key text not null check(line_key!~':v1:'),stock_effect_line_key text check(stock_effect_line_key is null or stock_effect_line_key!~':v1:'),
 quantity numeric(18,3) not null check(quantity>=0),quantity_damaged numeric(18,3) not null default 0 check(quantity_damaged>=0),
 quantity_shortage numeric(18,3) not null default 0 check(quantity_shortage>=0),lineage jsonb not null check(jsonb_typeof(lineage)='object'),
 primary key(event_id,line_uid),unique(event_id,line_key),unique(event_id,stock_effect_line_key),
 unique(transfer_operation_id,operation_type,line_uid),unique(transfer_operation_id,stock_effect_line_key),
 foreign key(event_id,transfer_operation_id,operation_type) references public.inventory_transfer_events_v2(id,transfer_operation_id,operation_type) on delete restrict,
 foreign key(transfer_operation_id,transfer_line_uid) references public.inventory_transfer_lines_v2(transfer_operation_id,line_uid) on delete restrict,
 check((operation_type in('DISPATCH','RECEIVE') and stock_effect_line_key is not null) or (operation_type not in('DISPATCH','RECEIVE') and stock_effect_line_key is null)));
create or replace function public.inventory_transfer_event_immutable_v2() returns trigger language plpgsql security definer set search_path='' as $$begin raise exception 'INVENTORY_TRANSFER_V2_EVENT_IMMUTABLE';end$$;
drop trigger if exists inventory_transfer_events_v2_immutable on public.inventory_transfer_events_v2;
create trigger inventory_transfer_events_v2_immutable before update or delete on public.inventory_transfer_events_v2 for each row execute function public.inventory_transfer_event_immutable_v2();
drop trigger if exists inventory_transfer_event_lines_v2_immutable on public.inventory_transfer_event_lines_v2;
create trigger inventory_transfer_event_lines_v2_immutable before update or delete on public.inventory_transfer_event_lines_v2 for each row execute function public.inventory_transfer_event_immutable_v2();
create or replace function public.inventory_transfer_identity_immutable_v2() returns trigger language plpgsql security definer set search_path='' as $$begin
 if tg_table_name='inventory_transfer_operations_v2' and (new.document_uid is distinct from old.document_uid or new.source_document_id is distinct from old.source_document_id or new.supply_request_id is distinct from old.supply_request_id or new.source_location_id is distinct from old.source_location_id or new.destination_location_id is distinct from old.destination_location_id or new.operation_digest is distinct from old.operation_digest or new.source_document_digest is distinct from old.source_document_digest) then raise exception 'INVENTORY_TRANSFER_V2_IDENTITY_IMMUTABLE';end if;
 if tg_table_name='inventory_transfer_lines_v2' and (new.transfer_operation_id is distinct from old.transfer_operation_id or new.supply_request_item_id is distinct from old.supply_request_item_id or new.line_uid is distinct from old.line_uid or new.line_key is distinct from old.line_key or new.item_kind is distinct from old.item_kind or new.item_id is distinct from old.item_id) then raise exception 'INVENTORY_TRANSFER_V2_IDENTITY_IMMUTABLE';end if;
 return new;end$$;
drop trigger if exists inventory_transfer_operations_v2_identity_immutable on public.inventory_transfer_operations_v2;
create trigger inventory_transfer_operations_v2_identity_immutable before update on public.inventory_transfer_operations_v2 for each row execute function public.inventory_transfer_identity_immutable_v2();
drop trigger if exists inventory_transfer_lines_v2_identity_immutable on public.inventory_transfer_lines_v2;
create trigger inventory_transfer_lines_v2_identity_immutable before update on public.inventory_transfer_lines_v2 for each row execute function public.inventory_transfer_identity_immutable_v2();
create or replace function public.inventory_transfer_point4c_activation_allowed_v2() returns boolean language sql stable security definer set search_path='' as $$select false$$;
create or replace function public.inventory_transfer_canonical_lines_v2(p_operation_type text,p_lines jsonb) returns jsonb language plpgsql immutable set search_path='' as $$
declare l jsonb;v jsonb;v_result jsonb:='[]'::jsonb;v_uid text;v_transfer_uid text;v_kind text;v_operation text:=upper(trim(coalesce(p_operation_type,'')));
begin
 if p_lines is null or jsonb_typeof(p_lines)<>'array' then raise exception 'INVENTORY_TRANSFER_V2_LINES_ARRAY_REQUIRED';end if;
 for l in select value from jsonb_array_elements(p_lines) loop
  perform public.point4_identity_assert_allowed_keys_v1(l,array['line_uid','transfer_line_uid','item_kind','item_id','quantity','quantity_damaged','quantity_shortage','unit_cost']);
  v_uid:=public.point4_identity_uuid_v4_v1(l->>'line_uid');
  v_transfer_uid:=public.point4_identity_uuid_v4_v1(l->>'transfer_line_uid');
  v_kind:=lower(trim(coalesce(l->>'item_kind','')));
  if v_kind not in('product','ingredient') then raise exception 'INVENTORY_TRANSFER_V2_ITEM_KIND_INVALID';end if;
  v:=jsonb_build_object(
    'line_uid',v_uid,'transfer_line_uid',v_transfer_uid,'item_kind',v_kind,
    'item_id',public.point4_identity_bigint_v1(l->'item_id',true),
    'quantity',public.point4_identity_decimal_v1((l->>'quantity')::numeric,3),
    'quantity_damaged',public.point4_identity_decimal_v1(coalesce((l->>'quantity_damaged')::numeric,0),3),
    'quantity_shortage',public.point4_identity_decimal_v1(coalesce((l->>'quantity_shortage')::numeric,0),3),
    'unit_cost',case when l?'unit_cost' and l->'unit_cost'<>'null'::jsonb then public.point4_identity_decimal_v1((l->>'unit_cost')::numeric,4) else null end,
    'line_key',public.point4_identity_effect_line_key_v1('transfer',lower(v_operation),v_uid,null,null)
  );
  if v_operation='DISPATCH' then
   v:=v||jsonb_build_object('stock_effect_line_key',public.point4_identity_effect_line_key_v1('stock','transfer_out',v_uid,null,null));
  elsif v_operation='RECEIVE' then
   v:=v||jsonb_build_object('stock_effect_line_key',public.point4_identity_effect_line_key_v1('stock','transfer_in',v_uid,null,null));
  end if;
  v_result:=v_result||jsonb_build_array(v);
 end loop;
 return public.point4_identity_canonical_lines_v1(v_result);
end$$;
create or replace function public.inventory_transfer_intent_digest_v2(p_document_uid uuid,p_operation_type text,p_client_tx_id text,p_source_location_id bigint,p_destination_location_id bigint,p_lines jsonb,p_final boolean) returns text language sql immutable set search_path='' as $$
 select public.point4_identity_operation_digest_v1(
  p_operation_type,p_client_tx_id,'inventory_transfer','uuid:'||p_document_uid::text,true,
  null,null,jsonb_build_object('source_location_id',p_source_location_id,'destination_location_id',p_destination_location_id,'final',coalesce(p_final,false)),
  public.inventory_transfer_canonical_lines_v2(p_operation_type,p_lines),null,null
 )$$;
create or replace function public.inventory_transfer_resolve_event_v2(p_operation_type text,p_client_tx_id text,p_operation_digest text) returns bigint language plpgsql stable security definer set search_path='' as $$declare v public.inventory_transfer_events_v2%rowtype;begin select * into v from public.inventory_transfer_events_v2 where operation_type=p_operation_type and client_tx_id=p_client_tx_id;if not found then return null;end if;if v.operation_digest<>p_operation_digest then raise exception 'INVENTORY_TRANSFER_V2_IDEMPOTENCY_CONFLICT';end if;return v.id;end$$;
create or replace function public.inventory_transfer_assert_activation_v2(p_source_location_id bigint,p_destination_location_id bigint,p_lines jsonb) returns void language plpgsql stable security definer set search_path='' as $$declare l jsonb;r text;begin
 if not public.inventory_stock_point4b2_concurrency_closed_v2() or not public.inventory_transfer_point4c_activation_allowed_v2() then raise exception 'INVENTORY_TRANSFER_V2_ACTIVATION_BLOCKED';end if;
 if p_source_location_id=p_destination_location_id then raise exception 'INVENTORY_TRANSFER_V2_LOCATION_CONFLICT';end if;
 for l in select value from jsonb_array_elements(coalesce(p_lines,'[]'::jsonb)) loop
  r:=public.inventory_stock_resolve_cutover_route_v2(p_source_location_id,l->>'item_kind',(l->>'item_id')::bigint);if r<>'CANONICAL_ONLY' then raise exception 'INVENTORY_TRANSFER_V2_SOURCE_NOT_CANONICAL';end if;
  r:=public.inventory_stock_resolve_cutover_route_v2(p_destination_location_id,l->>'item_kind',(l->>'item_id')::bigint);if r<>'CANONICAL_ONLY' then raise exception 'INVENTORY_TRANSFER_V2_DESTINATION_NOT_CANONICAL';end if;
 end loop;end$$;
alter table public.inventory_transfer_operations_v2 enable row level security;alter table public.inventory_transfer_lines_v2 enable row level security;alter table public.inventory_transfer_events_v2 enable row level security;alter table public.inventory_transfer_event_lines_v2 enable row level security;
revoke all on public.inventory_transfer_operations_v2,public.inventory_transfer_lines_v2,public.inventory_transfer_events_v2,public.inventory_transfer_event_lines_v2 from public,anon,authenticated;
revoke all on function public.inventory_transfer_event_immutable_v2() from public,anon,authenticated;
revoke all on function public.inventory_transfer_identity_immutable_v2() from public,anon,authenticated;
revoke all on function public.inventory_transfer_point4c_activation_allowed_v2() from public,anon,authenticated;
revoke all on function public.inventory_transfer_canonical_lines_v2(text,jsonb) from public,anon,authenticated;
revoke all on function public.inventory_transfer_intent_digest_v2(uuid,text,text,bigint,bigint,jsonb,boolean) from public,anon,authenticated;
revoke all on function public.inventory_transfer_resolve_event_v2(text,text,text) from public,anon,authenticated;
revoke all on function public.inventory_transfer_assert_activation_v2(bigint,bigint,jsonb) from public,anon,authenticated;
comment on table public.inventory_transfer_operations_v2 is 'Source-only companion contract: Central Supply is canonical; no operational workflow is connected.';
commit;
