-- Sharawla POS — Point 4C-1 Canonical Transfer source-only contract.
begin;
create table if not exists public.inventory_transfer_operations_v2(
 id bigint generated by default as identity primary key,
 supply_request_id bigint not null unique references public.inventory_supply_requests(id) on delete restrict,
 source_location_id bigint not null references public.branches(id) on delete restrict,
 destination_location_id bigint not null references public.branches(id) on delete restrict,
 lifecycle_state text not null check(lifecycle_state in('REQUESTED','APPROVED','RESERVED','PREPARING','IN_TRANSIT','PARTIALLY_RECEIVED','RECEIVED','CANCELLED','FORWARD_RECOVERY_REQUIRED')),
 ownership_state text not null default 'SOURCE_CONTRACT_ONLY' check(ownership_state in('SOURCE_CONTRACT_ONLY','CANONICAL_ACTIVE','FORWARD_RECOVERY_REQUIRED')),
 operation_digest text not null check(operation_digest~'^[0-9a-f]{64}$'),
 source_document_digest text not null check(source_document_digest~'^[0-9a-f]{64}$'),
 cutover_plan_digest text check(cutover_plan_digest is null or cutover_plan_digest~'^[0-9a-f]{64}$'),
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 check(source_location_id<>destination_location_id),
 check(ownership_state<>'CANONICAL_ACTIVE' or cutover_plan_digest is not null));
create table if not exists public.inventory_transfer_lines_v2(
 transfer_operation_id bigint not null references public.inventory_transfer_operations_v2(id) on delete restrict,
 supply_request_item_id bigint not null unique references public.inventory_supply_request_items(id) on delete restrict,
 line_key text not null,item_kind text not null check(item_kind in('product','ingredient')),item_id bigint not null check(item_id>0),
 quantity_requested numeric(18,3) not null check(quantity_requested>0),quantity_approved numeric(18,3) not null check(quantity_approved>=0),
 quantity_reserved numeric(18,3) not null default 0 check(quantity_reserved>=0),quantity_dispatched numeric(18,3) not null default 0 check(quantity_dispatched>=0),
 quantity_received numeric(18,3) not null default 0 check(quantity_received>=0),quantity_damaged numeric(18,3) not null default 0 check(quantity_damaged>=0),
 quantity_shortage numeric(18,3) not null default 0 check(quantity_shortage>=0),
 quantity_in_transit numeric(18,3) generated always as(quantity_dispatched-quantity_received-quantity_damaged-quantity_shortage) stored,
 unit_cost_snapshot numeric(18,4) not null check(unit_cost_snapshot>=0),
 dispatched_value numeric(18,4) generated always as(round(quantity_dispatched*unit_cost_snapshot,4)) stored,
 received_value numeric(18,4) generated always as(round(quantity_received*unit_cost_snapshot,4)) stored,
 damaged_value numeric(18,4) generated always as(round(quantity_damaged*unit_cost_snapshot,4)) stored,
 shortage_value numeric(18,4) generated always as(round(quantity_shortage*unit_cost_snapshot,4)) stored,
 in_transit_value numeric(18,4) generated always as(round((quantity_dispatched-quantity_received-quantity_damaged-quantity_shortage)*unit_cost_snapshot,4)) stored,
 lineage jsonb not null check(jsonb_typeof(lineage)='object'),primary key(transfer_operation_id,line_key),unique(transfer_operation_id,item_kind,item_id),
 check(quantity_approved<=quantity_requested and quantity_reserved<=quantity_approved and quantity_dispatched<=quantity_approved and quantity_received+quantity_damaged+quantity_shortage<=quantity_dispatched),
 constraint inventory_transfer_value_conservation_v2 check(dispatched_value=received_value+damaged_value+shortage_value+in_transit_value));
create table if not exists public.inventory_transfer_events_v2(
 id bigint generated by default as identity primary key,transfer_operation_id bigint not null references public.inventory_transfer_operations_v2(id) on delete restrict,
 operation_type text not null check(operation_type in('REQUEST','APPROVE','RESERVE','PREPARE','DISPATCH','RECEIVE','FINALIZE','CANCEL','RECOVERY')),
 client_tx_id text not null check(btrim(client_tx_id)<>''),operation_digest text not null check(operation_digest~'^[0-9a-f]{64}$'),
 from_state text,to_state text not null,payload jsonb not null check(jsonb_typeof(payload)='object'),employee_id bigint references public.employees(id) on delete restrict,
 recorded_at timestamptz not null default now(),unique(operation_type,client_tx_id));
create or replace function public.inventory_transfer_event_immutable_v2() returns trigger language plpgsql security definer set search_path='' as $$begin raise exception 'INVENTORY_TRANSFER_V2_EVENT_IMMUTABLE';end$$;
drop trigger if exists inventory_transfer_events_v2_immutable on public.inventory_transfer_events_v2;
create trigger inventory_transfer_events_v2_immutable before update or delete on public.inventory_transfer_events_v2 for each row execute function public.inventory_transfer_event_immutable_v2();
create or replace function public.inventory_transfer_point4c_activation_allowed_v2() returns boolean language sql stable security definer set search_path='' as $$select false$$;
create or replace function public.inventory_transfer_intent_digest_v2(p_supply_request_id bigint,p_operation_type text,p_client_tx_id text,p_lines jsonb,p_final boolean) returns text language sql immutable security definer set search_path='' as $$
 select pg_catalog.encode(extensions.digest(pg_catalog.convert_to(jsonb_build_object('schema_version',1,'supply_request_id',p_supply_request_id,'operation_type',p_operation_type,'client_tx_id',btrim(p_client_tx_id),'lines',coalesce(p_lines,'[]'::jsonb),'final',coalesce(p_final,false))::text,'UTF8'),'sha256'),'hex')$$;
create or replace function public.inventory_transfer_resolve_event_v2(p_operation_type text,p_client_tx_id text,p_operation_digest text) returns bigint language plpgsql stable security definer set search_path='' as $$declare v public.inventory_transfer_events_v2%rowtype;begin select * into v from public.inventory_transfer_events_v2 where operation_type=p_operation_type and client_tx_id=p_client_tx_id;if not found then return null;end if;if v.operation_digest<>p_operation_digest then raise exception 'INVENTORY_TRANSFER_V2_IDEMPOTENCY_CONFLICT';end if;return v.id;end$$;
create or replace function public.inventory_transfer_assert_activation_v2(p_source_location_id bigint,p_destination_location_id bigint,p_lines jsonb) returns void language plpgsql stable security definer set search_path='' as $$declare l jsonb;r text;begin
 if not public.inventory_stock_point4b2_concurrency_closed_v2() or not public.inventory_transfer_point4c_activation_allowed_v2() then raise exception 'INVENTORY_TRANSFER_V2_ACTIVATION_BLOCKED';end if;
 if p_source_location_id=p_destination_location_id then raise exception 'INVENTORY_TRANSFER_V2_LOCATION_CONFLICT';end if;
 for l in select value from jsonb_array_elements(coalesce(p_lines,'[]'::jsonb)) loop
  r:=public.inventory_stock_resolve_cutover_route_v2(p_source_location_id,l->>'item_kind',(l->>'item_id')::bigint);if r<>'CANONICAL_ONLY' then raise exception 'INVENTORY_TRANSFER_V2_SOURCE_NOT_CANONICAL';end if;
  r:=public.inventory_stock_resolve_cutover_route_v2(p_destination_location_id,l->>'item_kind',(l->>'item_id')::bigint);if r<>'CANONICAL_ONLY' then raise exception 'INVENTORY_TRANSFER_V2_DESTINATION_NOT_CANONICAL';end if;
 end loop;end$$;
alter table public.inventory_transfer_operations_v2 enable row level security;alter table public.inventory_transfer_lines_v2 enable row level security;alter table public.inventory_transfer_events_v2 enable row level security;
revoke all on public.inventory_transfer_operations_v2,public.inventory_transfer_lines_v2,public.inventory_transfer_events_v2 from public,anon,authenticated;
revoke all on function public.inventory_transfer_event_immutable_v2() from public,anon,authenticated;
revoke all on function public.inventory_transfer_point4c_activation_allowed_v2() from public,anon,authenticated;
revoke all on function public.inventory_transfer_intent_digest_v2(bigint,text,text,jsonb,boolean) from public,anon,authenticated;
revoke all on function public.inventory_transfer_resolve_event_v2(text,text,text) from public,anon,authenticated;
revoke all on function public.inventory_transfer_assert_activation_v2(bigint,bigint,jsonb) from public,anon,authenticated;
comment on table public.inventory_transfer_operations_v2 is 'Source-only companion contract: Central Supply is canonical; no operational workflow is connected.';
commit;
