-- V9.6.0 - Returns / Refunds
-- Run after V9.5.0. Safe to re-run.

create table if not exists public.branch_return_counters(
  branch_id bigint primary key references public.branches(id) on delete cascade,
  next_number bigint not null default 1 check(next_number>=1)
);

create table if not exists public.returns(
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  return_number bigint not null,
  order_id bigint not null references public.orders(id),
  original_invoice_number bigint,
  original_bon_number integer,
  employee_id bigint not null references public.employees(id),
  shift_id bigint references public.shifts(id),
  reason text not null,
  notes text,
  subtotal numeric(12,2) not null default 0,
  discount_adjustment numeric(12,2) not null default 0,
  tax_adjustment numeric(12,2) not null default 0,
  service_adjustment numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  unique(branch_id,return_number)
);

create table if not exists public.return_items(
  id bigint generated by default as identity primary key,
  return_id bigint not null references public.returns(id) on delete cascade,
  order_item_id bigint not null references public.order_items(id),
  product_id bigint,
  product_name text not null,
  quantity numeric(12,3) not null check(quantity>0),
  unit_refund numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0
);

create table if not exists public.return_payments(
  id bigint generated by default as identity primary key,
  return_id bigint not null references public.returns(id) on delete cascade,
  method text not null,
  amount numeric(12,2) not null check(amount>0)
);

insert into public.branch_return_counters(branch_id,next_number)
select b.id,coalesce(max(r.return_number),0)+1
from public.branches b
left join public.returns r on r.branch_id=b.id
group by b.id
on conflict(branch_id) do update set next_number=greatest(public.branch_return_counters.next_number,excluded.next_number);

alter table public.returns enable row level security;
alter table public.return_items enable row level security;
alter table public.return_payments enable row level security;
alter table public.branch_return_counters enable row level security;

grant select on public.returns,public.return_items,public.return_payments,public.branch_return_counters to authenticated;
grant usage,select on sequence public.returns_id_seq,public.return_items_id_seq,public.return_payments_id_seq to authenticated;

drop policy if exists returns_staff_read on public.returns;
create policy returns_staff_read on public.returns for select to authenticated
using(public.is_admin() or public.has_branch_access(branch_id));

drop policy if exists return_items_staff_read on public.return_items;
create policy return_items_staff_read on public.return_items for select to authenticated
using(exists(select 1 from public.returns r where r.id=return_id and (public.is_admin() or public.has_branch_access(r.branch_id))));

drop policy if exists return_payments_staff_read on public.return_payments;
create policy return_payments_staff_read on public.return_payments for select to authenticated
using(exists(select 1 from public.returns r where r.id=return_id and (public.is_admin() or public.has_branch_access(r.branch_id))));

drop policy if exists branch_return_counters_staff_read on public.branch_return_counters;
create policy branch_return_counters_staff_read on public.branch_return_counters for select to authenticated
using(public.is_admin() or public.has_branch_access(branch_id));

create or replace function public.create_order_return(
  p_order_id bigint,
  p_reason text,
  p_notes text,
  p_items jsonb,
  p_payments jsonb
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare
  v_order public.orders%rowtype;
  v_emp bigint;
  v_shift bigint;
  v_return_id bigint;
  v_return_no bigint;
  v_item jsonb;
  v_oi public.order_items%rowtype;
  v_qty numeric(12,3);
  v_prev numeric(12,3);
  v_line numeric(12,2);
  v_sub numeric(12,2):=0;
  v_ratio numeric(18,8):=0;
  v_discount numeric(12,2):=0;
  v_tax numeric(12,2):=0;
  v_service numeric(12,2):=0;
  v_total numeric(12,2):=0;
  v_pay jsonb;
  v_pay_total numeric(12,2):=0;
  v_method text;
  v_amount numeric(12,2);
begin
  if not (public.is_admin() or public.has_permission('returns')) then
    raise exception 'ليس لديك صلاحية عمل مرتجع';
  end if;

  v_emp:=public.current_employee_id();
  if v_emp is null then raise exception 'المستخدم غير مربوط بموظف'; end if;

  select * into v_order from public.orders where id=p_order_id for update;
  if not found then raise exception 'الفاتورة غير موجودة'; end if;
  if not public.has_branch_access(v_order.branch_id) then raise exception 'ليس لديك صلاحية لهذا الفرع'; end if;
  if v_order.status='cancelled' then raise exception 'لا يمكن عمل مرتجع لفاتورة ملغية'; end if;
  if nullif(trim(coalesce(p_reason,'')),'') is null then raise exception 'سبب المرتجع مطلوب'; end if;
  if p_items is null or jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'اختر صنفًا واحدًا على الأقل'; end if;

  select id into v_shift from public.shifts
  where branch_id=v_order.branch_id and employee_id=v_emp and status='open' and closed_at is null
  order by opened_at desc limit 1;
  if v_shift is null then raise exception 'افتح وردية أولًا قبل عمل المرتجع'; end if;

  for v_item in select * from jsonb_array_elements(p_items) loop
    select * into v_oi from public.order_items
    where id=(v_item->>'order_item_id')::bigint and order_id=v_order.id;
    if not found then raise exception 'صنف المرتجع غير موجود بالفاتورة'; end if;
    v_qty:=coalesce((v_item->>'quantity')::numeric,0);
    if v_qty<=0 then raise exception 'كمية المرتجع غير صحيحة'; end if;
    select coalesce(sum(ri.quantity),0) into v_prev
    from public.return_items ri join public.returns r on r.id=ri.return_id
    where r.order_id=v_order.id and ri.order_item_id=v_oi.id;
    if v_qty+v_prev>v_oi.quantity then raise exception 'كمية المرتجع أكبر من الكمية المتاحة للصنف %',v_oi.product_name; end if;
    v_line:=round((coalesce(v_oi.total,0)/nullif(v_oi.quantity,0))*v_qty,2);
    v_sub:=v_sub+v_line;
  end loop;

  if coalesce(v_order.subtotal,0)>0 then v_ratio:=least(1,v_sub/v_order.subtotal); end if;
  v_discount:=round(coalesce(v_order.discount,0)*v_ratio,2);
  v_tax:=round(coalesce(v_order.tax_amount,0)*v_ratio,2);
  v_service:=round(coalesce(v_order.service_amount,0)*v_ratio,2);
  -- رسوم الدليفري لا تُرد تلقائيًا؛ المرتجع هنا خاص بالأصناف.
  v_total:=greatest(0,round(v_sub-v_discount+v_tax+v_service,2));

  if p_payments is null or jsonb_typeof(p_payments)<>'array' or jsonb_array_length(p_payments)=0 then
    raise exception 'حدد طريقة رد المبلغ';
  end if;
  for v_pay in select * from jsonb_array_elements(p_payments) loop
    v_method:=nullif(trim(v_pay->>'method'),'');
    v_amount:=coalesce((v_pay->>'amount')::numeric,0);
    if v_method is null or v_amount<=0 then raise exception 'بيانات رد المبلغ غير صحيحة'; end if;
    if not exists(
      select 1 from public.payment_methods pm
      join public.branch_payment_methods bpm on bpm.payment_method_id=pm.id
      where pm.code=v_method and pm.active=true and bpm.branch_id=v_order.branch_id and bpm.active=true
    ) then raise exception 'طريقة رد المبلغ غير متاحة للفرع'; end if;
    v_pay_total:=v_pay_total+v_amount;
  end loop;
  if abs(v_pay_total-v_total)>0.01 then raise exception 'إجمالي رد المبلغ يجب أن يساوي %',v_total; end if;

  insert into public.branch_return_counters(branch_id,next_number)
  values(v_order.branch_id,2)
  on conflict(branch_id) do update set next_number=public.branch_return_counters.next_number+1
  returning next_number-1 into v_return_no;

  insert into public.returns(branch_id,return_number,order_id,original_invoice_number,original_bon_number,employee_id,shift_id,reason,notes,subtotal,discount_adjustment,tax_adjustment,service_adjustment,total)
  values(v_order.branch_id,v_return_no,v_order.id,v_order.invoice_number,v_order.bon_number,v_emp,v_shift,trim(p_reason),nullif(trim(coalesce(p_notes,'')),''),v_sub,v_discount,v_tax,v_service,v_total)
  returning id into v_return_id;

  for v_item in select * from jsonb_array_elements(p_items) loop
    select * into v_oi from public.order_items where id=(v_item->>'order_item_id')::bigint and order_id=v_order.id;
    v_qty:=(v_item->>'quantity')::numeric;
    v_line:=round((coalesce(v_oi.total,0)/nullif(v_oi.quantity,0))*v_qty,2);
    insert into public.return_items(return_id,order_item_id,product_id,product_name,quantity,unit_refund,total)
    values(v_return_id,v_oi.id,v_oi.product_id,v_oi.product_name,v_qty,round(v_line/v_qty,2),v_line);
  end loop;

  for v_pay in select * from jsonb_array_elements(p_payments) loop
    insert into public.return_payments(return_id,method,amount)
    values(v_return_id,trim(v_pay->>'method'),(v_pay->>'amount')::numeric);
  end loop;

  return v_return_id;
end;
$$;

revoke all on function public.create_order_return(bigint,text,text,jsonb,jsonb) from public;
grant execute on function public.create_order_return(bigint,text,text,jsonb,jsonb) to authenticated;

notify pgrst,'reload schema';
