-- Sharawla POS 10.5.4-beta.55
-- Delivery Settlement + Shift Cash Fix (Beta / additive / backward-compatible)
-- New clients use the V2 RPCs below. Legacy columns and RPCs remain intact.

begin;

-- ---------------------------------------------------------------------------
-- 1) Additive accounting metadata
-- ---------------------------------------------------------------------------
alter table public.orders
  add column if not exists delivery_cash_custody_amount numeric(12,2) not null default 0,
  add column if not exists delivery_payment_finalized_at timestamptz,
  add column if not exists delivery_payment_finalized_by bigint references public.employees(id) on delete set null;

alter table public.driver_settlements
  add column if not exists receiving_shift_id bigint references public.shifts(id) on delete restrict,
  add column if not exists client_tx_id text,
  add column if not exists status text not null default 'posted',
  add column if not exists reversed_at timestamptz;

alter table public.driver_settlements drop constraint if exists driver_settlements_status_check;
alter table public.driver_settlements
  add constraint driver_settlements_status_check check(status in ('posted','reversed'));

create unique index if not exists driver_settlements_client_tx_uidx
  on public.driver_settlements(client_tx_id) where client_tx_id is not null;
create index if not exists driver_settlements_receiving_shift_idx
  on public.driver_settlements(receiving_shift_id,created_at desc);

create table if not exists public.driver_settlement_items(
  id bigint generated by default as identity primary key,
  settlement_id bigint not null references public.driver_settlements(id) on delete restrict,
  order_id bigint not null references public.orders(id) on delete restrict,
  source_shift_id bigint references public.shifts(id) on delete restrict,
  amount numeric(12,2) not null check(amount>0),
  created_at timestamptz not null default now(),
  reversed_at timestamptz
);
create unique index if not exists driver_settlement_items_active_order_uidx
  on public.driver_settlement_items(order_id) where reversed_at is null;
create index if not exists driver_settlement_items_settlement_idx
  on public.driver_settlement_items(settlement_id,order_id);

create table if not exists public.delivery_payment_events(
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete restrict,
  branch_id bigint not null references public.branches(id) on delete restrict,
  driver_id bigint references public.delivery_drivers(id) on delete restrict,
  employee_id bigint references public.employees(id) on delete set null,
  client_tx_id text not null unique,
  event_type text not null check(event_type in ('delivered','payment_changed')),
  old_method text,
  new_method text not null,
  custody_before numeric(12,2) not null default 0,
  custody_after numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists delivery_payment_events_order_idx
  on public.delivery_payment_events(order_id,created_at desc);

-- Closed-shift snapshots. Existing columns remain the compatibility contract.
alter table public.shifts
  add column if not exists cash_sales_gross numeric(12,2) not null default 0,
  add column if not exists cash_returns_total numeric(12,2) not null default 0,
  add column if not exists delivery_cash_originated numeric(12,2) not null default 0,
  add column if not exists driver_custody_unsettled numeric(12,2) not null default 0,
  add column if not exists driver_settlements_received numeric(12,2) not null default 0;

-- Legacy pending delivered-cash orders become visible as custody. Historical
-- orders already marked settled are intentionally not rewritten because old
-- settlements did not record a receiving shift.
update public.orders o
set delivery_cash_custody_amount = round(coalesce(
  case when exists(select 1 from public.order_payments op0 where op0.order_id=o.id)
       then (select sum(op.amount) from public.order_payments op where op.order_id=o.id and lower(op.method)='cash')
       else o.total end,0),2),
    delivery_payment_finalized_at = coalesce(o.delivery_payment_finalized_at,o.delivered_at)
where o.order_type='delivery'
  and o.status in ('delivered','completed')
  and o.driver_id is not null
  and o.driver_settled_at is null
  and lower(coalesce(o.payment_method,''))='cash'
  and coalesce(o.delivery_cash_custody_amount,0)=0;

-- ---------------------------------------------------------------------------
-- 2) Granular Action Permissions V2
-- ---------------------------------------------------------------------------
insert into public.permission_actions_v2(code,name_ar,domain,legacy_permission,active,sort_order) values
 ('delivery.mark_delivered','تأكيد تسليم طلب الدليفري','delivery','deliveryOrders',true,610),
 ('delivery.payment.change_at_delivery','تغيير طريقة الدفع عند التسليم','delivery','deliveryOrders',true,620),
 ('delivery.settlement.view','عرض عهد وتسويات المناديب','delivery','deliverySettings',true,630),
 ('delivery.settlement.create','استلام وتسوية عهدة مندوب','delivery','deliverySettings',true,640)
on conflict(code) do update set
 name_ar=excluded.name_ar,domain=excluded.domain,legacy_permission=excluded.legacy_permission,
 active=excluded.active,sort_order=excluded.sort_order;

-- ---------------------------------------------------------------------------
-- 3) Read policies for the additive ledger tables. Writes are RPC-only.
-- ---------------------------------------------------------------------------
alter table public.driver_settlement_items enable row level security;
alter table public.delivery_payment_events enable row level security;

grant select on public.driver_settlement_items,public.delivery_payment_events to authenticated;
revoke insert,update,delete on public.driver_settlement_items,public.delivery_payment_events from authenticated;

drop policy if exists driver_settlement_items_branch_read on public.driver_settlement_items;
create policy driver_settlement_items_branch_read on public.driver_settlement_items
for select to authenticated
using(exists(
  select 1 from public.driver_settlements ds
  where ds.id=settlement_id and public.has_branch_access(ds.branch_id)
));

drop policy if exists delivery_payment_events_branch_read on public.delivery_payment_events;
create policy delivery_payment_events_branch_read on public.delivery_payment_events
for select to authenticated using(public.has_branch_access(branch_id));

-- ---------------------------------------------------------------------------
-- 4) Delivery finalization / payment correction.
--    Every invocation is idempotent by client_tx_id and atomic.
-- ---------------------------------------------------------------------------
create or replace function public.delivery_mark_delivered_v2(
  p_order_id bigint,
  p_payment_method text,
  p_client_tx_id text
) returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_emp bigint;
  v_key text:=nullif(trim(coalesce(p_client_tx_id,'')),'');
  v_method text:=lower(nullif(trim(coalesce(p_payment_method,'')),''));
  v_old text;
  v_order public.orders%rowtype;
  v_existing public.delivery_payment_events%rowtype;
  v_before numeric(12,2):=0;
  v_after numeric(12,2):=0;
  v_pay_count integer:=0;
  v_distinct_pay integer:=0;
  v_event text;
begin
  if auth.uid() is null then raise exception 'غير مصرح'; end if;
  v_emp:=public.current_employee_id();
  if v_emp is null then raise exception 'تعذر تحديد الموظف الحالي'; end if;
  if v_key is null then raise exception 'معرف الحركة مطلوب'; end if;
  if v_method is null or v_method='mixed' then raise exception 'حدد طريقة دفع نهائية واحدة عند التسليم'; end if;
  if not public.has_action_permission_v2('delivery.mark_delivered') then raise exception 'ليس لديك صلاحية تأكيد تسليم الدليفري'; end if;

  perform pg_advisory_xact_lock(hashtextextended(v_key,0));
  select * into v_existing from public.delivery_payment_events where client_tx_id=v_key limit 1;
  if found then
    if v_existing.order_id<>p_order_id then raise exception 'معرف الحركة مستخدم لطلب آخر'; end if;
    select * into v_order from public.orders where id=p_order_id;
    return jsonb_build_object('ok',true,'idempotent',true,'order',to_jsonb(v_order),'custody_amount',v_existing.custody_after);
  end if;

  select * into v_order from public.orders where id=p_order_id for update;
  if not found then raise exception 'طلب الدليفري غير موجود'; end if;
  if v_order.order_type<>'delivery' then raise exception 'الطلب ليس دليفري'; end if;
  if not public.has_branch_access(v_order.branch_id) then raise exception 'ليس لديك صلاحية على هذا الفرع'; end if;
  if v_order.status not in ('out_for_delivery','delivered','completed') then raise exception 'الطلب غير جاهز لتأكيد التسليم'; end if;
  if v_order.driver_id is null then raise exception 'حدد المندوب قبل تأكيد التسليم'; end if;

  if not exists(
    select 1 from public.payment_methods pm
    where lower(pm.code)=v_method and pm.active=true
      and (
        not exists(select 1 from public.branch_payment_methods bpm0 where bpm0.branch_id=v_order.branch_id)
        or exists(select 1 from public.branch_payment_methods bpm join public.payment_methods pm2 on pm2.id=bpm.payment_method_id
                  where bpm.branch_id=v_order.branch_id and bpm.active=true and lower(pm2.code)=v_method)
      )
  ) then raise exception 'طريقة الدفع غير متاحة لهذا الفرع'; end if;

  v_old:=lower(coalesce(v_order.payment_method,''));
  v_before:=coalesce(v_order.delivery_cash_custody_amount,0);

  if v_old is distinct from v_method then
    if not public.has_action_permission_v2('delivery.payment.change_at_delivery') then raise exception 'ليس لديك صلاحية تغيير طريقة الدفع عند التسليم'; end if;
    if v_order.driver_settled_at is not null
       or exists(select 1 from public.driver_settlement_items dsi where dsi.order_id=v_order.id and dsi.reversed_at is null)
    then raise exception 'لا يمكن تغيير طريقة الدفع بعد تسوية عهدة هذا الطلب'; end if;
  end if;

  select count(*),count(distinct lower(method)) into v_pay_count,v_distinct_pay
  from public.order_payments where order_id=v_order.id;
  if v_order.payment_method='mixed' or v_distinct_pay>1 then
    raise exception 'الدفع المختلط يحتاج تسوية مكونات مستقلة ولا يمكن تغييره من شاشة التسليم الحالية';
  end if;

  -- The final method is a collection fact, so keep orders + payment ledger aligned.
  delete from public.order_payments where order_id=v_order.id;
  insert into public.order_payments(order_id,method,amount)
  values(v_order.id,v_method,coalesce(v_order.total,0));

  v_after:=case when v_method='cash' then round(coalesce(v_order.total,0),2) else 0 end;
  v_event:=case when v_order.status in ('delivered','completed') then 'payment_changed' else 'delivered' end;

  update public.orders
  set payment_method=v_method,
      payment_status='confirmed',
      status='delivered',
      delivered_at=coalesce(delivered_at,now()),
      delivery_cash_custody_amount=v_after,
      delivery_payment_finalized_at=now(),
      delivery_payment_finalized_by=v_emp,
      driver_settled_at=case when v_after>0 then null else driver_settled_at end
  where id=v_order.id
  returning * into v_order;

  insert into public.delivery_payment_events(
    order_id,branch_id,driver_id,employee_id,client_tx_id,event_type,
    old_method,new_method,custody_before,custody_after
  ) values(
    v_order.id,v_order.branch_id,v_order.driver_id,v_emp,v_key,v_event,
    nullif(v_old,''),v_method,v_before,v_after
  );

  insert into public.audit_logs(employee_id,branch_id,action,entity_type,entity_id,details)
  values(v_emp,v_order.branch_id,
         case when v_event='delivered' then 'delivery_mark_delivered_v2' else 'delivery_payment_change_v2' end,
         'order',v_order.id,
         jsonb_build_object('old_method',v_old,'new_method',v_method,'custody_before',v_before,'custody_after',v_after,'client_tx_id',v_key));

  return jsonb_build_object('ok',true,'idempotent',false,'order',to_jsonb(v_order),'custody_amount',v_after);
end;
$$;

-- ---------------------------------------------------------------------------
-- 5) Atomic driver settlement: one order or many orders, same RPC.
--    p_order_ids NULL/empty means "all currently eligible orders" for driver.
-- ---------------------------------------------------------------------------
create or replace function public.delivery_driver_settle_v2(
  p_driver_id bigint,
  p_order_ids bigint[],
  p_client_tx_id text
) returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_emp bigint;
  v_key text:=nullif(trim(coalesce(p_client_tx_id,'')),'');
  v_driver public.delivery_drivers%rowtype;
  v_shift bigint;
  v_existing public.driver_settlements%rowtype;
  v_requested bigint[];
  v_ids bigint[];
  v_count integer:=0;
  v_amount numeric(12,2):=0;
  v_settlement bigint;
begin
  if auth.uid() is null then raise exception 'غير مصرح'; end if;
  v_emp:=public.current_employee_id();
  if v_emp is null then raise exception 'تعذر تحديد الموظف الحالي'; end if;
  if v_key is null then raise exception 'معرف الحركة مطلوب'; end if;
  if not public.has_action_permission_v2('delivery.settlement.create') then raise exception 'ليس لديك صلاحية تسوية عهدة المناديب'; end if;

  perform pg_advisory_xact_lock(hashtextextended(v_key,0));
  select * into v_existing from public.driver_settlements where client_tx_id=v_key limit 1;
  if found then
    return jsonb_build_object('ok',true,'idempotent',true,'settlement_id',v_existing.id,
      'orders_count',v_existing.orders_count,'amount',v_existing.amount,'receiving_shift_id',v_existing.receiving_shift_id);
  end if;

  select * into v_driver from public.delivery_drivers where id=p_driver_id for share;
  if not found then raise exception 'المندوب غير موجود'; end if;
  if not public.has_branch_access(v_driver.branch_id) then raise exception 'ليس لديك صلاحية على فرع المندوب'; end if;

  select s.id into v_shift from public.shifts s
  where s.branch_id=v_driver.branch_id and s.employee_id=v_emp and s.status='open' and s.closed_at is null
  order by s.opened_at desc limit 1;
  if v_shift is null then raise exception 'افتح وردية على فرع المندوب قبل استلام التسوية'; end if;

  if p_order_ids is not null and cardinality(p_order_ids)>0 then
    select array_agg(distinct x order by x) into v_requested from unnest(p_order_ids) x where x is not null;
  else
    v_requested:=null;
  end if;

  select array_agg(q.id order by q.id),count(*)::int,coalesce(sum(q.delivery_cash_custody_amount),0)
  into v_ids,v_count,v_amount
  from (
    select o.id,o.delivery_cash_custody_amount
    from public.orders o
    where o.driver_id=p_driver_id
      and o.branch_id=v_driver.branch_id
      and o.order_type='delivery'
      and o.status in ('delivered','completed')
      and coalesce(o.delivery_cash_custody_amount,0)>0
      and o.driver_settled_at is null
      and not exists(select 1 from public.driver_settlement_items dsi where dsi.order_id=o.id and dsi.reversed_at is null)
      and (v_requested is null or o.id=any(v_requested))
    order by o.id
    for update
  ) q;

  if v_requested is not null and v_count<>cardinality(v_requested) then
    raise exception 'واحد أو أكثر من الطلبات المحددة غير صالح للتسوية أو تمت تسويته بالفعل';
  end if;
  if v_count=0 or coalesce(v_amount,0)<=0 then raise exception 'لا توجد عهدة كاش غير مسواة لهذا المندوب'; end if;

  insert into public.driver_settlements(
    driver_id,branch_id,employee_id,orders_count,amount,notes,created_at,
    receiving_shift_id,client_tx_id,status
  ) values(
    p_driver_id,v_driver.branch_id,v_emp,v_count,round(v_amount,2),'Delivery Settlement V2',now(),
    v_shift,v_key,'posted'
  ) returning id into v_settlement;

  insert into public.driver_settlement_items(settlement_id,order_id,source_shift_id,amount)
  select v_settlement,o.id,o.shift_id,o.delivery_cash_custody_amount
  from public.orders o where o.id=any(v_ids);

  update public.orders set driver_settled_at=now() where id=any(v_ids);

  insert into public.audit_logs(employee_id,branch_id,action,entity_type,entity_id,details)
  values(v_emp,v_driver.branch_id,'delivery_driver_settlement_v2','delivery_driver',p_driver_id,
    jsonb_build_object('settlement_id',v_settlement,'receiving_shift_id',v_shift,'orders',to_jsonb(v_ids),'orders_count',v_count,'amount',round(v_amount,2),'client_tx_id',v_key));

  return jsonb_build_object('ok',true,'idempotent',false,'settlement_id',v_settlement,
    'orders_count',v_count,'amount',round(v_amount,2),'receiving_shift_id',v_shift,'order_ids',to_jsonb(v_ids));
end;
$$;

-- ---------------------------------------------------------------------------
-- 6) Read models used by UI and final shift close.
-- ---------------------------------------------------------------------------
create or replace function public.delivery_driver_pending_v2(p_branch_id bigint)
returns table(
  order_id bigint,
  driver_id bigint,
  source_shift_id bigint,
  bon_number integer,
  invoice_number bigint,
  total numeric,
  custody_amount numeric,
  delivered_at timestamptz,
  customer_name text,
  customer_phone text
)
language sql
stable
security definer
set search_path=public
as $$
  select o.id,o.driver_id,o.shift_id,o.bon_number,o.invoice_number,o.total,
         o.delivery_cash_custody_amount,o.delivered_at,o.customer_name,o.customer_phone
  from public.orders o
  where public.has_action_permission_v2('delivery.settlement.view')
    and public.has_branch_access(p_branch_id)
    and o.branch_id=p_branch_id
    and o.order_type='delivery'
    and o.status in ('delivered','completed')
    and coalesce(o.delivery_cash_custody_amount,0)>0
    and o.driver_settled_at is null
    and not exists(select 1 from public.driver_settlement_items dsi where dsi.order_id=o.id and dsi.reversed_at is null)
  order by o.driver_id,o.delivered_at,o.id
$$;

create or replace function public.shift_cash_metrics_v2(p_shift_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
declare
  v_shift public.shifts%rowtype;
  v_cash_sales_gross numeric(12,2):=0;
  v_cash_returns numeric(12,2):=0;
  v_delivery_cash_originated numeric(12,2):=0;
  v_unsettled numeric(12,2):=0;
  v_settlements numeric(12,2):=0;
  v_expenses numeric(12,2):=0;
  v_expected numeric(12,2):=0;
begin
  if auth.uid() is null then raise exception 'غير مصرح'; end if;
  select * into v_shift from public.shifts where id=p_shift_id;
  if not found then raise exception 'الوردية غير موجودة'; end if;
  if not public.has_branch_access(v_shift.branch_id) then raise exception 'ليس لديك صلاحية على هذا الفرع'; end if;

  with valid_orders as (
    select o.*,
      case
        when exists(select 1 from public.order_payments op0 where op0.order_id=o.id)
          then coalesce((select sum(op.amount) from public.order_payments op where op.order_id=o.id and lower(op.method)='cash'),0)
        when lower(coalesce(o.payment_method,''))='cash' then coalesce(o.total,0)
        else 0
      end as cash_component
    from public.orders o
    where o.shift_id=p_shift_id
      and o.status<>'cancelled'
      and (
        coalesce(o.source,'pos')<>'website'
        or o.payment_status='confirmed'
        or (lower(coalesce(o.payment_method,''))='cash' and o.status in ('delivered','completed'))
      )
  )
  select
    coalesce(sum(cash_component),0),
    coalesce(sum(case when order_type='delivery'
                           and cash_component>0
                           and (coalesce(delivery_cash_custody_amount,0)>0 or driver_settled_at is null)
                      then cash_component else 0 end),0),
    coalesce(sum(case when order_type='delivery'
                           and coalesce(delivery_cash_custody_amount,0)>0
                           and driver_settled_at is null
                           and not exists(select 1 from public.driver_settlement_items dsi where dsi.order_id=valid_orders.id and dsi.reversed_at is null)
                      then delivery_cash_custody_amount else 0 end),0)
  into v_cash_sales_gross,v_delivery_cash_originated,v_unsettled
  from valid_orders;

  select coalesce(sum(rp.amount),0) into v_cash_returns
  from public.returns r join public.return_payments rp on rp.return_id=r.id
  where r.shift_id=p_shift_id and lower(rp.method)='cash';

  select coalesce(sum(e.amount),0) into v_expenses
  from public.expenses e where e.shift_id=p_shift_id;

  select coalesce(sum(ds.amount),0) into v_settlements
  from public.driver_settlements ds
  where ds.receiving_shift_id=p_shift_id and ds.status='posted' and ds.reversed_at is null;

  v_expected:=round(coalesce(v_shift.opening_cash,0)
                    +v_cash_sales_gross
                    -v_delivery_cash_originated
                    +v_settlements
                    -v_cash_returns
                    -v_expenses,2);

  return jsonb_build_object(
    'shift_id',v_shift.id,
    'branch_id',v_shift.branch_id,
    'opening_cash',coalesce(v_shift.opening_cash,0),
    'cash_sales_gross',round(v_cash_sales_gross,2),
    'cash_returns',round(v_cash_returns,2),
    'cash_sales_net',round(v_cash_sales_gross-v_cash_returns,2),
    'delivery_cash_originated',round(v_delivery_cash_originated,2),
    'driver_custody_unsettled',round(v_unsettled,2),
    'driver_settlements_received',round(v_settlements,2),
    'expenses',round(v_expenses,2),
    'expected_drawer_cash',v_expected
  );
end;
$$;

-- New close RPC keeps the old signature/function untouched for 10.5.3 clients.
-- Beta55 uses this V2 RPC so expected cash and variance are server-derived.
create or replace function public.close_pos_shift_v2(
  p_shift_id bigint,
  p_closing_cash numeric,
  p_metrics jsonb,
  p_client_tx_id text
) returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_emp bigint;
  v_key text:=nullif(trim(coalesce(p_client_tx_id,'')),'');
  v_row public.shifts%rowtype;
  v_cash jsonb;
  v_expected numeric(12,2);
  v_diff numeric(12,2);
begin
  if auth.uid() is null then raise exception 'غير مصرح'; end if;
  v_emp:=public.current_employee_id(); if v_emp is null then raise exception 'تعذر تحديد الموظف الحالي'; end if;
  if v_key is null then raise exception 'معرف الحركة مطلوب'; end if;
  if coalesce(p_closing_cash,-1)<0 then raise exception 'الكاش الفعلي غير صحيح'; end if;

  perform pg_advisory_xact_lock(hashtextextended(v_key,0));
  select * into v_row from public.shifts where client_close_tx_id=v_key limit 1;
  if found then return to_jsonb(v_row); end if;

  select * into v_row from public.shifts where id=p_shift_id and employee_id=v_emp for update;
  if not found then raise exception 'الوردية غير موجودة أو غير مطابقة للموظف'; end if;
  if not public.has_branch_access(v_row.branch_id) then raise exception 'ليس لديك صلاحية على هذا الفرع'; end if;
  if v_row.status='closed' and v_row.closed_at is not null then return to_jsonb(v_row); end if;

  v_cash:=public.shift_cash_metrics_v2(p_shift_id);
  v_expected:=coalesce((v_cash->>'expected_drawer_cash')::numeric,0);
  v_diff:=round(p_closing_cash-v_expected,2);

  update public.shifts set
    closing_cash=p_closing_cash,closed_at=now(),status='closed',closed_by_employee_id=v_emp,
    sales_total=coalesce((p_metrics->>'sales_total')::numeric,0),
    cash_sales=coalesce((v_cash->>'cash_sales_net')::numeric,0),
    wallet_sales=coalesce((p_metrics->>'wallet_sales')::numeric,0),
    instapay_sales=coalesce((p_metrics->>'instapay_sales')::numeric,0),
    expenses_total=coalesce((v_cash->>'expenses')::numeric,0),
    expected_cash=v_expected,cash_difference=v_diff,
    orders_count=coalesce((p_metrics->>'orders_count')::integer,0),
    client_close_tx_id=v_key,
    cash_sales_gross=coalesce((v_cash->>'cash_sales_gross')::numeric,0),
    cash_returns_total=coalesce((v_cash->>'cash_returns')::numeric,0),
    delivery_cash_originated=coalesce((v_cash->>'delivery_cash_originated')::numeric,0),
    driver_custody_unsettled=coalesce((v_cash->>'driver_custody_unsettled')::numeric,0),
    driver_settlements_received=coalesce((v_cash->>'driver_settlements_received')::numeric,0)
  where id=p_shift_id returning * into v_row;

  insert into public.audit_logs(employee_id,branch_id,action,entity_type,entity_id,details)
  values(v_emp,v_row.branch_id,'close_pos_shift_v2','shift',v_row.id,
    jsonb_build_object('expected_drawer_cash',v_expected,'closing_cash',p_closing_cash,'cash_difference',v_diff,
      'driver_custody_unsettled',v_row.driver_custody_unsettled,'driver_settlements_received',v_row.driver_settlements_received,'client_tx_id',v_key));

  return to_jsonb(v_row);
end;
$$;

revoke all on function public.delivery_mark_delivered_v2(bigint,text,text) from public;
revoke all on function public.delivery_driver_settle_v2(bigint,bigint[],text) from public;
revoke all on function public.delivery_driver_pending_v2(bigint) from public;
revoke all on function public.shift_cash_metrics_v2(bigint) from public;
revoke all on function public.close_pos_shift_v2(bigint,numeric,jsonb,text) from public;

grant execute on function public.delivery_mark_delivered_v2(bigint,text,text) to authenticated;
grant execute on function public.delivery_driver_settle_v2(bigint,bigint[],text) to authenticated;
grant execute on function public.delivery_driver_pending_v2(bigint) to authenticated;
grant execute on function public.shift_cash_metrics_v2(bigint) to authenticated;
grant execute on function public.close_pos_shift_v2(bigint,numeric,jsonb,text) to authenticated;

notify pgrst,'reload schema';
commit;
