-- Sharawla POS 10.5.8 — Top Burger Production Recipe Soft Consumption V1
-- Additive / fail-open. Core sale and return functions are NOT replaced.
-- New sales consume the legacy recipes table after each order_item insert.
-- Any recipe/stock failure is caught and logged; the sale/return continues.
-- Returns restore the frozen quantities captured at sale time, never the current recipe.

begin;

create table if not exists public.recipe_order_item_consumption_v1 (
  id bigint generated by default as identity primary key,
  order_item_id bigint not null,
  order_id bigint not null,
  branch_id bigint not null,
  product_id bigint not null,
  ingredient_id bigint not null,
  sold_quantity numeric(18,6) not null,
  recipe_quantity_per_unit numeric(18,6) not null,
  consumed_quantity numeric(18,6) not null,
  unit_cost_snapshot numeric(18,6) not null default 0,
  created_at timestamptz not null default now(),
  unique(order_item_id, ingredient_id)
);

create index if not exists idx_recipe_order_consumption_order_v1
  on public.recipe_order_item_consumption_v1(order_id);
create index if not exists idx_recipe_order_consumption_ingredient_v1
  on public.recipe_order_item_consumption_v1(branch_id, ingredient_id);

create table if not exists public.recipe_return_consumption_v1 (
  id bigint generated by default as identity primary key,
  return_item_id bigint not null,
  return_id bigint not null,
  order_item_id bigint not null,
  order_id bigint not null,
  branch_id bigint not null,
  ingredient_id bigint not null,
  return_quantity numeric(18,6) not null,
  restored_quantity numeric(18,6) not null,
  unit_cost_snapshot numeric(18,6) not null default 0,
  created_at timestamptz not null default now(),
  unique(return_item_id, ingredient_id)
);

create index if not exists idx_recipe_return_consumption_return_v1
  on public.recipe_return_consumption_v1(return_id);
create index if not exists idx_recipe_return_consumption_ingredient_v1
  on public.recipe_return_consumption_v1(branch_id, ingredient_id);

create table if not exists public.recipe_consumption_errors_v1 (
  id bigint generated by default as identity primary key,
  direction text not null check(direction in ('sale','return')),
  order_id bigint,
  order_item_id bigint,
  return_id bigint,
  return_item_id bigint,
  sqlstate text,
  error_message text,
  created_at timestamptz not null default now()
);

alter table public.recipe_order_item_consumption_v1 enable row level security;
alter table public.recipe_return_consumption_v1 enable row level security;
alter table public.recipe_consumption_errors_v1 enable row level security;

revoke all on table public.recipe_order_item_consumption_v1 from anon, authenticated;
revoke all on table public.recipe_return_consumption_v1 from anon, authenticated;
revoke all on table public.recipe_consumption_errors_v1 from anon, authenticated;
grant select on table public.recipe_order_item_consumption_v1 to service_role;
grant select on table public.recipe_return_consumption_v1 to service_role;
grant select on table public.recipe_consumption_errors_v1 to service_role;

create or replace function public.recipe_apply_order_item_consumption_v1(p_order_item_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_order_id bigint;
  v_branch_id bigint;
  v_product_id bigint;
  v_sold_quantity numeric(18,6);
  v_recipe record;
  v_need numeric(18,6);
  v_snapshot_id bigint;
  v_stock_id bigint;
  v_stock_quantity numeric;
  v_applied integer := 0;
begin
  if p_order_item_id is null then
    return jsonb_build_object('status','skipped','reason','missing_order_item');
  end if;

  perform pg_advisory_xact_lock(hashtextextended('recipe-order-item-v1:' || p_order_item_id::text,0));

  select oi.order_id, o.branch_id, oi.product_id, coalesce(oi.quantity,0)
  into v_order_id, v_branch_id, v_product_id, v_sold_quantity
  from public.order_items oi
  join public.orders o on o.id=oi.order_id
  where oi.id=p_order_item_id;

  if v_order_id is null or v_branch_id is null or v_product_id is null or v_sold_quantity<=0 then
    return jsonb_build_object('status','skipped','reason','order_item_not_eligible');
  end if;

  for v_recipe in
    select r.ingredient_id,
           r.quantity::numeric(18,6) recipe_quantity,
           coalesce(i.cost_per_unit,0)::numeric(18,6) unit_cost
    from public.recipes r
    join public.ingredients i on i.id=r.ingredient_id
    where r.product_id=v_product_id
      and r.quantity>0
      and i.active is distinct from false
    order by r.ingredient_id
  loop
    v_need := round(v_recipe.recipe_quantity * v_sold_quantity,6);
    if v_need<=0 then
      continue;
    end if;

    v_snapshot_id := null;
    insert into public.recipe_order_item_consumption_v1(
      order_item_id,order_id,branch_id,product_id,ingredient_id,
      sold_quantity,recipe_quantity_per_unit,consumed_quantity,unit_cost_snapshot
    ) values(
      p_order_item_id,v_order_id,v_branch_id,v_product_id,v_recipe.ingredient_id,
      v_sold_quantity,v_recipe.recipe_quantity,v_need,v_recipe.unit_cost
    )
    on conflict(order_item_id,ingredient_id) do nothing
    returning id into v_snapshot_id;

    if v_snapshot_id is null then
      continue;
    end if;

    insert into public.ingredient_stock(branch_id,ingredient_id,quantity)
    values(v_branch_id,v_recipe.ingredient_id,0)
    on conflict(branch_id,ingredient_id) do nothing;

    select s.id,s.quantity
    into v_stock_id,v_stock_quantity
    from public.ingredient_stock s
    where s.branch_id=v_branch_id and s.ingredient_id=v_recipe.ingredient_id
    for update;

    if v_stock_id is null then
      raise exception 'ingredient stock row unavailable';
    end if;

    update public.ingredient_stock
    set quantity=round(coalesce(v_stock_quantity,0)-v_need,6),
        updated_at=clock_timestamp()
    where id=v_stock_id;

    insert into public.stock_movements(
      branch_id,ingredient_id,movement_type,quantity,reference_type,reference_id,notes
    ) values(
      v_branch_id,v_recipe.ingredient_id,'sale',-v_need,'order_item',p_order_item_id,
      'Recipe Soft Consumption V1'
    );

    v_applied := v_applied + 1;
  end loop;

  return jsonb_build_object('status','ok','order_item_id',p_order_item_id,'ingredients_applied',v_applied);
end;
$function$;

create or replace function public.recipe_apply_return_item_restore_v1(p_return_item_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_return_id bigint;
  v_order_id bigint;
  v_order_item_id bigint;
  v_branch_id bigint;
  v_return_quantity numeric(18,6);
  v_original_quantity numeric(18,6);
  v_snapshot record;
  v_restore numeric(18,6);
  v_already_restored numeric(18,6);
  v_remaining numeric(18,6);
  v_restore_id bigint;
  v_stock_id bigint;
  v_stock_quantity numeric;
  v_applied integer := 0;
begin
  if p_return_item_id is null then
    return jsonb_build_object('status','skipped','reason','missing_return_item');
  end if;

  perform pg_advisory_xact_lock(hashtextextended('recipe-return-item-v1:' || p_return_item_id::text,0));

  select ri.return_id, r.order_id, ri.order_item_id, r.branch_id,
         coalesce(ri.quantity,0), coalesce(oi.quantity,0)
  into v_return_id,v_order_id,v_order_item_id,v_branch_id,
       v_return_quantity,v_original_quantity
  from public.return_items ri
  join public.returns r on r.id=ri.return_id
  join public.order_items oi on oi.id=ri.order_item_id
  where ri.id=p_return_item_id;

  if v_return_id is null or v_order_id is null or v_order_item_id is null
     or v_branch_id is null or v_return_quantity<=0 or v_original_quantity<=0 then
    return jsonb_build_object('status','skipped','reason','return_item_not_eligible');
  end if;

  -- Serialize all returns that refer to the same original order item.
  -- This makes the recipe restore independently safe even if the core return
  -- owner is ever changed later and multiple returns arrive concurrently.
  perform pg_advisory_xact_lock(
    hashtextextended('recipe-return-order-item-v1:' || v_order_item_id::text,0)
  );

  for v_snapshot in
    select s.ingredient_id,s.consumed_quantity,s.unit_cost_snapshot
    from public.recipe_order_item_consumption_v1 s
    where s.order_item_id=v_order_item_id
    order by s.ingredient_id
  loop
    select coalesce(sum(r.restored_quantity),0)::numeric(18,6)
    into v_already_restored
    from public.recipe_return_consumption_v1 r
    where r.order_item_id=v_order_item_id
      and r.ingredient_id=v_snapshot.ingredient_id;

    v_remaining := greatest(v_snapshot.consumed_quantity-v_already_restored,0);

    v_restore := least(
      round(
        v_snapshot.consumed_quantity * least(v_return_quantity,v_original_quantity)
        / greatest(v_original_quantity,0.000001),
        6
      ),
      v_remaining
    );
    if v_restore<=0 then
      continue;
    end if;

    v_restore_id := null;
    insert into public.recipe_return_consumption_v1(
      return_item_id,return_id,order_item_id,order_id,branch_id,ingredient_id,
      return_quantity,restored_quantity,unit_cost_snapshot
    ) values(
      p_return_item_id,v_return_id,v_order_item_id,v_order_id,v_branch_id,v_snapshot.ingredient_id,
      v_return_quantity,v_restore,v_snapshot.unit_cost_snapshot
    )
    on conflict(return_item_id,ingredient_id) do nothing
    returning id into v_restore_id;

    if v_restore_id is null then
      continue;
    end if;

    insert into public.ingredient_stock(branch_id,ingredient_id,quantity)
    values(v_branch_id,v_snapshot.ingredient_id,0)
    on conflict(branch_id,ingredient_id) do nothing;

    select s.id,s.quantity
    into v_stock_id,v_stock_quantity
    from public.ingredient_stock s
    where s.branch_id=v_branch_id and s.ingredient_id=v_snapshot.ingredient_id
    for update;

    if v_stock_id is null then
      raise exception 'ingredient stock row unavailable';
    end if;

    update public.ingredient_stock
    set quantity=round(coalesce(v_stock_quantity,0)+v_restore,6),
        updated_at=clock_timestamp()
    where id=v_stock_id;

    insert into public.stock_movements(
      branch_id,ingredient_id,movement_type,quantity,reference_type,reference_id,notes
    ) values(
      v_branch_id,v_snapshot.ingredient_id,'return',v_restore,'return',v_return_id,
      'Recipe Return Snapshot Restore V1'
    );

    v_applied := v_applied + 1;
  end loop;

  return jsonb_build_object('status','ok','return_item_id',p_return_item_id,'ingredients_restored',v_applied);
end;
$function$;

create or replace function public.recipe_order_item_fail_open_trigger_v1()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$
begin
  begin
    perform public.recipe_apply_order_item_consumption_v1(new.id);
  exception when others then
    begin
      insert into public.recipe_consumption_errors_v1(
        direction,order_id,order_item_id,sqlstate,error_message
      ) values(
        'sale',new.order_id,new.id,sqlstate,left(sqlerrm,1000)
      );
    exception when others then
      null;
    end;
  end;
  return new;
end;
$function$;

create or replace function public.recipe_return_item_fail_open_trigger_v1()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_order_id bigint;
begin
  begin
    perform public.recipe_apply_return_item_restore_v1(new.id);
  exception when others then
    begin
      select r.order_id into v_order_id from public.returns r where r.id=new.return_id;
      insert into public.recipe_consumption_errors_v1(
        direction,order_id,order_item_id,return_id,return_item_id,sqlstate,error_message
      ) values(
        'return',v_order_id,new.order_item_id,new.return_id,new.id,sqlstate,left(sqlerrm,1000)
      );
    exception when others then
      null;
    end;
  end;
  return new;
end;
$function$;

do $block$
begin
  if not exists(
    select 1 from pg_trigger
    where tgrelid='public.order_items'::regclass
      and tgname='trg_recipe_order_item_fail_open_v1'
      and not tgisinternal
  ) then
    create trigger trg_recipe_order_item_fail_open_v1
    after insert on public.order_items
    for each row execute function public.recipe_order_item_fail_open_trigger_v1();
  end if;

  if not exists(
    select 1 from pg_trigger
    where tgrelid='public.return_items'::regclass
      and tgname='trg_recipe_return_item_fail_open_v1'
      and not tgisinternal
  ) then
    create trigger trg_recipe_return_item_fail_open_v1
    after insert on public.return_items
    for each row execute function public.recipe_return_item_fail_open_trigger_v1();
  end if;
end;
$block$;

revoke all on function public.recipe_apply_order_item_consumption_v1(bigint) from public, anon, authenticated;
revoke all on function public.recipe_apply_return_item_restore_v1(bigint) from public, anon, authenticated;
revoke all on function public.recipe_order_item_fail_open_trigger_v1() from public, anon, authenticated;
revoke all on function public.recipe_return_item_fail_open_trigger_v1() from public, anon, authenticated;

comment on table public.recipe_order_item_consumption_v1 is
  'Frozen per-sale legacy recipe consumption snapshot. New sales only; used for exact historical return restore.';
comment on table public.recipe_return_consumption_v1 is
  'Per-return restoration snapshot derived only from the frozen sale snapshot, never from the current recipe.';
comment on table public.recipe_consumption_errors_v1 is
  'Fail-open diagnostics. Recipe/stock failures never reject the sale or return.';
comment on function public.recipe_order_item_fail_open_trigger_v1() is
  'AFTER INSERT fail-open stock consumption. Any recipe error is swallowed after best-effort logging.';
comment on function public.recipe_return_item_fail_open_trigger_v1() is
  'AFTER INSERT fail-open return restore using frozen sale snapshots. Any stock error is swallowed.';

commit;
