-- SOURCE ONLY. Do not deploy without explicit authorization.
-- Offline V2 recipe master-data owners. Receipt replay protects non-idempotent canonical actions.
create or replace function public.offline_food_recipe_save_draft_action_v2(p_product_id bigint,p_variant_id bigint,p_name text,p_output_quantity numeric,p_output_unit_code text,p_lines jsonb,p_modifier_impacts jsonb,p_removal_mappings jsonb,p_notes text,p_client_tx_id text,p_payload_digest text)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_tx text:=nullif(trim(coalesce(p_client_tx_id,'')),'');v_d text:=nullif(trim(coalesce(p_payload_digest,'')),'');r public.offline_restaurant_reference_receipts_v1%rowtype;v_id bigint;v_recipe bigint;v_result jsonb;
begin if auth.uid() is null then raise exception 'UNAUTHENTICATED';end if;if v_tx is null or v_d is null then raise exception 'OFFLINE_FOOD_RECIPE_IDENTITY_REQUIRED';end if;perform pg_advisory_xact_lock(hashtextextended('offline-food-recipe-draft:'||v_tx,0));select * into r from public.offline_restaurant_reference_receipts_v1 where client_tx_id=v_tx;
 if found then if r.operation_type<>'food_recipe_save_draft' or r.payload_digest<>v_d then raise exception 'OFFLINE_RESTAURANT_REFERENCE_REPLAY_MISMATCH';end if;return r.result_json||jsonb_build_object('idempotent_replay',true);end if;
 if not exists(select 1 from public.products where id=p_product_id and active is distinct from false) then raise exception 'OFFLINE_FOOD_RECIPE_PRODUCT_DEPENDENCY_UNRESOLVED';end if;
 if p_variant_id is not null and not exists(select 1 from public.product_variants where id=p_variant_id and product_id=p_product_id and active=true) then raise exception 'OFFLINE_FOOD_RECIPE_VARIANT_DEPENDENCY_UNRESOLVED';end if;
 if exists(select 1 from jsonb_to_recordset(coalesce(p_lines,'[]'::jsonb)) x(ingredient_id bigint) left join public.ingredients i on i.id=x.ingredient_id where i.id is null) then raise exception 'OFFLINE_FOOD_RECIPE_INGREDIENT_DEPENDENCY_UNRESOLVED';end if;
 v_id:=public.food_recipe_save_draft_action_v2(p_product_id,p_variant_id,p_name,p_output_quantity,p_output_unit_code,p_lines,p_modifier_impacts,p_removal_mappings,p_notes);select recipe_id into v_recipe from public.food_recipe_versions where id=v_id;
 v_result:=jsonb_build_object('ok',true,'recipe_version_id',v_id,'recipe_id',v_recipe,'client_tx_id',v_tx,'idempotent_replay',false);insert into public.offline_restaurant_reference_receipts_v1(client_tx_id,operation_type,payload_digest,entity_id,result_json) values(v_tx,'food_recipe_save_draft',v_d,v_id,v_result);return v_result;end;$$;
create or replace function public.offline_food_recipe_activate_version_action_v2(p_recipe_version_id bigint,p_client_tx_id text,p_payload_digest text)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_tx text:=nullif(trim(coalesce(p_client_tx_id,'')),'');v_d text:=nullif(trim(coalesce(p_payload_digest,'')),'');r public.offline_restaurant_reference_receipts_v1%rowtype;v_id bigint;v_result jsonb;
begin if auth.uid() is null then raise exception 'UNAUTHENTICATED';end if;if v_tx is null or v_d is null then raise exception 'OFFLINE_FOOD_RECIPE_IDENTITY_REQUIRED';end if;perform pg_advisory_xact_lock(hashtextextended('offline-food-recipe-activate:'||v_tx,0));select * into r from public.offline_restaurant_reference_receipts_v1 where client_tx_id=v_tx;
 if found then if r.operation_type<>'food_recipe_activate' or r.payload_digest<>v_d then raise exception 'OFFLINE_RESTAURANT_REFERENCE_REPLAY_MISMATCH';end if;return r.result_json||jsonb_build_object('idempotent_replay',true);end if;
 if not exists(select 1 from public.food_recipe_versions where id=p_recipe_version_id) then raise exception 'OFFLINE_FOOD_RECIPE_VERSION_DEPENDENCY_UNRESOLVED';end if;
 v_id:=public.food_recipe_activate_version_action_v2(p_recipe_version_id);v_result:=jsonb_build_object('ok',true,'recipe_version_id',v_id,'client_tx_id',v_tx,'idempotent_replay',false);insert into public.offline_restaurant_reference_receipts_v1(client_tx_id,operation_type,payload_digest,entity_id,result_json) values(v_tx,'food_recipe_activate',v_d,v_id,v_result);return v_result;end;$$;
revoke all on function public.offline_food_recipe_save_draft_action_v2(bigint,bigint,text,numeric,text,jsonb,jsonb,jsonb,text,text,text) from public,anon;
revoke all on function public.offline_food_recipe_activate_version_action_v2(bigint,text,text) from public,anon;
grant execute on function public.offline_food_recipe_save_draft_action_v2(bigint,bigint,text,numeric,text,jsonb,jsonb,jsonb,text,text,text) to authenticated;
grant execute on function public.offline_food_recipe_activate_version_action_v2(bigint,text,text) to authenticated;
