-- SOURCE ONLY. Do not deploy without explicit authorization.
-- Central Warehouse stock lifecycle owners. Server remains stock authority.
create or replace function public.offline_inventory_supply_request_dispatch_v1(p_request_id bigint,p_items jsonb,p_note text,p_client_tx_id text,p_payload_digest text) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare t text:=nullif(trim(coalesce(p_client_tx_id,'')),'');d text:=nullif(trim(coalesce(p_payload_digest,'')),'');r public.offline_restaurant_reference_receipts_v1%rowtype;i bigint;j jsonb;begin
 if auth.uid() is null or t is null or d is null then raise exception 'OFFLINE_SUPPLY_DISPATCH_IDENTITY_REQUIRED';end if;perform pg_advisory_xact_lock(hashtextextended('offline-supply-stock:'||t,0));select * into r from public.offline_restaurant_reference_receipts_v1 where client_tx_id=t;if found then if r.operation_type<>'inventory_supply_request_dispatch' or r.payload_digest<>d then raise exception 'OFFLINE_RESTAURANT_REFERENCE_REPLAY_MISMATCH';end if;return r.result_json||jsonb_build_object('idempotent_replay',true);end if;
 i:=public.inventory_supply_request_dispatch_v1(p_request_id,p_items,p_note,t);j:=jsonb_build_object('ok',true,'request_id',i,'client_tx_id',t);insert into public.offline_restaurant_reference_receipts_v1(client_tx_id,operation_type,payload_digest,entity_id,result_json)values(t,'inventory_supply_request_dispatch',d,i,j);return j;end;$$;
create or replace function public.offline_inventory_supply_request_receive_v1(p_request_id bigint,p_items jsonb,p_final boolean,p_note text,p_client_tx_id text,p_payload_digest text) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare t text:=nullif(trim(coalesce(p_client_tx_id,'')),'');d text:=nullif(trim(coalesce(p_payload_digest,'')),'');r public.offline_restaurant_reference_receipts_v1%rowtype;i bigint;j jsonb;begin
 if auth.uid() is null or t is null or d is null then raise exception 'OFFLINE_SUPPLY_RECEIVE_IDENTITY_REQUIRED';end if;perform pg_advisory_xact_lock(hashtextextended('offline-supply-stock:'||t,0));select * into r from public.offline_restaurant_reference_receipts_v1 where client_tx_id=t;if found then if r.operation_type<>'inventory_supply_request_receive' or r.payload_digest<>d then raise exception 'OFFLINE_RESTAURANT_REFERENCE_REPLAY_MISMATCH';end if;return r.result_json||jsonb_build_object('idempotent_replay',true);end if;
 i:=public.inventory_supply_request_receive_v1(p_request_id,p_items,p_final,p_note,t);j:=jsonb_build_object('ok',true,'request_id',i,'client_tx_id',t);insert into public.offline_restaurant_reference_receipts_v1(client_tx_id,operation_type,payload_digest,entity_id,result_json)values(t,'inventory_supply_request_receive',d,i,j);return j;end;$$;
revoke all on function public.offline_inventory_supply_request_dispatch_v1(bigint,jsonb,text,text,text) from public,anon;grant execute on function public.offline_inventory_supply_request_dispatch_v1(bigint,jsonb,text,text,text) to authenticated;
revoke all on function public.offline_inventory_supply_request_receive_v1(bigint,jsonb,boolean,text,text,text) from public,anon;grant execute on function public.offline_inventory_supply_request_receive_v1(bigint,jsonb,boolean,text,text,text) to authenticated;