-- Restaurant POS V7
-- Branch permissions, call-center multi-branch access, delivery settlements, website-ready catalog.

begin;

create table if not exists public.employee_branches (
  employee_id bigint not null references public.employees(id) on delete cascade,
  branch_id bigint not null references public.branches(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (employee_id, branch_id)
);

-- Every employee keeps access to the home branch.
insert into public.employee_branches (employee_id, branch_id)
select id, branch_id from public.employees where branch_id is not null
on conflict do nothing;

-- Existing call-center/delivery accounts can work across all current branches.
insert into public.employee_branches (employee_id, branch_id)
select e.id, b.id
from public.employees e cross join public.branches b
where e.role in ('callcenter','delivery') and coalesce(e.active,true)=true
on conflict do nothing;

alter table public.orders add column if not exists driver_settled_at timestamptz;

create table if not exists public.driver_settlements (
  id bigint generated by default as identity primary key,
  driver_id bigint not null references public.delivery_drivers(id) on delete restrict,
  branch_id bigint not null references public.branches(id) on delete restrict,
  employee_id bigint references public.employees(id) on delete set null,
  orders_count integer not null default 0,
  amount numeric(12,2) not null default 0,
  notes text,
  created_at timestamptz not null default now()
);

-- Website-ready product controls. The future website can use the same catalog safely.
alter table public.products add column if not exists website_visible boolean not null default true;
alter table public.products add column if not exists website_sort_order integer not null default 0;
alter table public.categories add column if not exists website_visible boolean not null default true;
alter table public.categories add column if not exists website_sort_order integer not null default 0;

create index if not exists idx_employee_branches_branch on public.employee_branches(branch_id,employee_id);
create index if not exists idx_orders_driver_unsettled on public.orders(driver_id,driver_settled_at,status);
create index if not exists idx_driver_settlements_driver_date on public.driver_settlements(driver_id,created_at desc);

-- Helpers used by RLS. SECURITY DEFINER prevents recursive policy lookups.
create or replace function public.current_employee_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select id from public.employees where auth_user_id = auth.uid() limit 1
$$;

create or replace function public.current_employee_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.employees where auth_user_id = auth.uid() limit 1
$$;

create or replace function public.has_branch_access(p_branch_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_admin()
     or exists (
       select 1 from public.employee_branches eb
       where eb.employee_id = public.current_employee_id()
         and eb.branch_id = p_branch_id
     )
$$;

grant execute on function public.current_employee_id() to authenticated;
grant execute on function public.current_employee_role() to authenticated;
grant execute on function public.has_branch_access(bigint) to authenticated;

grant select,insert,update,delete on public.employee_branches to authenticated;
grant select,insert,update,delete on public.driver_settlements to authenticated;

alter table public.employee_branches enable row level security;
alter table public.driver_settlements enable row level security;

-- Employee branch mapping: user can read own mappings; admin manages all.
drop policy if exists employee_branches_read on public.employee_branches;
create policy employee_branches_read on public.employee_branches
for select to authenticated
using (employee_id = public.current_employee_id() or public.is_admin());

drop policy if exists employee_branches_admin_write on public.employee_branches;
create policy employee_branches_admin_write on public.employee_branches
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Delivery settlements follow branch permissions; creation is manager-only.
drop policy if exists driver_settlements_read on public.driver_settlements;
create policy driver_settlements_read on public.driver_settlements
for select to authenticated
using (public.has_branch_access(branch_id));

drop policy if exists driver_settlements_admin_write on public.driver_settlements;
create policy driver_settlements_admin_write on public.driver_settlements
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Allow employees to resolve their own profile during bootstrap.
drop policy if exists employees_self_read on public.employees;
create policy employees_self_read on public.employees
for select to authenticated
using (auth_user_id = auth.uid() or public.is_admin());

-- Shared customer directory: staff can search/create customers, while financial data remains branch-separated.
drop policy if exists customers_staff_read on public.customers;
create policy customers_staff_read on public.customers
for select to authenticated
using (public.current_employee_id() is not null);

drop policy if exists customers_staff_insert on public.customers;
create policy customers_staff_insert on public.customers
for insert to authenticated
with check (public.current_employee_id() is not null);

drop policy if exists customers_staff_update on public.customers;
create policy customers_staff_update on public.customers
for update to authenticated
using (public.current_employee_id() is not null)
with check (public.current_employee_id() is not null);

drop policy if exists customer_addresses_staff_read on public.customer_addresses;
create policy customer_addresses_staff_read on public.customer_addresses
for select to authenticated
using (public.current_employee_id() is not null);

drop policy if exists customer_addresses_staff_write on public.customer_addresses;
create policy customer_addresses_staff_write on public.customer_addresses
for all to authenticated
using (public.current_employee_id() is not null)
with check (public.current_employee_id() is not null);

-- Branch separation for operational/financial tables.
drop policy if exists orders_branch_read on public.orders;
create policy orders_branch_read on public.orders
for select to authenticated using (public.has_branch_access(branch_id));
drop policy if exists orders_branch_insert on public.orders;
create policy orders_branch_insert on public.orders
for insert to authenticated with check (public.has_branch_access(branch_id));
drop policy if exists orders_branch_update on public.orders;
create policy orders_branch_update on public.orders
for update to authenticated using (public.has_branch_access(branch_id)) with check (public.has_branch_access(branch_id));

drop policy if exists order_items_branch_read on public.order_items;
create policy order_items_branch_read on public.order_items
for select to authenticated using (exists(select 1 from public.orders o where o.id=order_id and public.has_branch_access(o.branch_id)));
drop policy if exists order_items_branch_insert on public.order_items;
create policy order_items_branch_insert on public.order_items
for insert to authenticated with check (exists(select 1 from public.orders o where o.id=order_id and public.has_branch_access(o.branch_id)));

drop policy if exists order_payments_branch_read on public.order_payments;
create policy order_payments_branch_read on public.order_payments
for select to authenticated using (exists(select 1 from public.orders o where o.id=order_id and public.has_branch_access(o.branch_id)));
drop policy if exists order_payments_branch_insert on public.order_payments;
create policy order_payments_branch_insert on public.order_payments
for insert to authenticated with check (exists(select 1 from public.orders o where o.id=order_id and public.has_branch_access(o.branch_id)));

drop policy if exists shifts_branch_read on public.shifts;
create policy shifts_branch_read on public.shifts
for select to authenticated using (public.has_branch_access(branch_id));
drop policy if exists shifts_own_insert on public.shifts;
create policy shifts_own_insert on public.shifts
for insert to authenticated with check (public.has_branch_access(branch_id) and employee_id=public.current_employee_id());
drop policy if exists shifts_own_update on public.shifts;
create policy shifts_own_update on public.shifts
for update to authenticated using (public.is_admin() or employee_id=public.current_employee_id()) with check (public.has_branch_access(branch_id));

drop policy if exists expenses_branch_read on public.expenses;
create policy expenses_branch_read on public.expenses
for select to authenticated using (public.has_branch_access(branch_id));
drop policy if exists expenses_branch_insert on public.expenses;
create policy expenses_branch_insert on public.expenses
for insert to authenticated with check (public.has_branch_access(branch_id) and employee_id=public.current_employee_id());

drop policy if exists delivery_drivers_branch_read on public.delivery_drivers;
create policy delivery_drivers_branch_read on public.delivery_drivers
for select to authenticated using (public.has_branch_access(branch_id));

drop policy if exists delivery_zones_branch_read on public.delivery_zones;
create policy delivery_zones_branch_read on public.delivery_zones
for select to authenticated using (public.has_branch_access(branch_id));

-- Admin retains management rights for drivers/zones. (Existing admin_all policies may already cover this.)
drop policy if exists delivery_drivers_admin_write on public.delivery_drivers;
create policy delivery_drivers_admin_write on public.delivery_drivers
for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists delivery_zones_admin_write on public.delivery_zones;
create policy delivery_zones_admin_write on public.delivery_zones
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Catalog remains readable to authenticated staff; future public website should use a controlled API/Edge Function.
drop policy if exists categories_staff_read on public.categories;
create policy categories_staff_read on public.categories for select to authenticated using (true);
drop policy if exists products_staff_read on public.products;
create policy products_staff_read on public.products for select to authenticated using (true);
drop policy if exists branch_products_staff_read on public.branch_products;
create policy branch_products_staff_read on public.branch_products for select to authenticated using (public.has_branch_access(branch_id));

notify pgrst, 'reload schema';
commit;
