-- V10.5.16 PostgreSQL contract fixture.
-- Represents the minimum Top Burger Production contracts already present before this port.

do $$ begin
  if not exists(select 1 from pg_roles where rolname='anon') then create role anon; end if;
  if not exists(select 1 from pg_roles where rolname='authenticated') then create role authenticated; end if;
  if not exists(select 1 from pg_roles where rolname='service_role') then create role service_role; end if;
end $$;

create schema if not exists auth;
create or replace function auth.uid() returns uuid
language sql stable as $$select '00000000-0000-0000-0000-000000000001'::uuid$$;

create table public.branches(
  id bigint generated by default as identity primary key,
  name text not null
);
create table public.employees(
  id bigint generated by default as identity primary key,
  name text not null,
  active boolean default true,
  role text,
  branch_id bigint references public.branches(id)
);
create table public.audit_logs(
  id bigint generated by default as identity primary key,
  employee_id bigint,
  branch_id bigint,
  action text,
  entity_type text,
  entity_id bigint,
  details jsonb,
  created_at timestamptz default now()
);
create table public.shifts(
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  employee_id bigint not null references public.employees(id),
  status text not null default 'open',
  opened_at timestamptz not null default now(),
  closed_at timestamptz
);

create table public.products(
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12,2) not null default 0,
  cost numeric(12,2) not null default 0,
  active boolean not null default true
);
create table public.product_variants(
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  name text not null,
  price numeric(12,2) not null default 0,
  cost numeric(12,2) default 0,
  active boolean not null default true
);
create table public.modifiers(
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12,2) not null default 0,
  active boolean not null default true
);

create table public.ingredients(
  id bigint generated by default as identity primary key,
  name text not null,
  unit text not null default 'g',
  cost_per_unit numeric(18,6) not null default 0,
  minimum_quantity numeric(18,6) not null default 0,
  active boolean not null default true
);
create table public.recipes(
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id),
  ingredient_id bigint not null references public.ingredients(id),
  quantity numeric(18,6) not null
);
create table public.ingredient_stock(
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  ingredient_id bigint not null references public.ingredients(id),
  quantity numeric(18,6) not null default 0,
  updated_at timestamptz not null default now(),
  unique(branch_id,ingredient_id)
);
create table public.stock_movements(
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  ingredient_id bigint not null references public.ingredients(id),
  movement_type text not null,
  quantity numeric(18,6) not null,
  reference_type text,
  reference_id bigint,
  notes text,
  created_at timestamptz not null default now()
);

create table public.orders(
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  employee_id bigint references public.employees(id),
  shift_id bigint references public.shifts(id),
  bon_number bigint,
  invoice_number bigint,
  order_type text default 'takeaway',
  payment_method text default 'cash',
  subtotal numeric(12,2) default 0,
  discount numeric(12,2) default 0,
  tax_amount numeric(12,2) default 0,
  service_amount numeric(12,2) default 0,
  total numeric(12,2) default 0,
  status text default 'completed',
  client_tx_id text unique,
  created_at timestamptz not null default now()
);
create table public.order_items(
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id),
  product_name text not null,
  quantity numeric(18,6) not null,
  unit_price numeric(12,2) default 0,
  cost numeric(18,6) default 0,
  total numeric(12,2) default 0,
  notes text
);
create table public.order_item_modifiers(
  id bigint generated by default as identity primary key,
  order_item_id bigint not null references public.order_items(id) on delete cascade,
  modifier_id bigint references public.modifiers(id),
  modifier_name text not null,
  price numeric(12,2) default 0,
  quantity integer not null check(quantity between 1 and 99)
);
alter table public.order_item_modifiers enable row level security;

create table public.order_payments(
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  method text not null,
  amount numeric(12,2) not null
);
create table public.returns(
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id),
  branch_id bigint not null references public.branches(id),
  employee_id bigint references public.employees(id),
  shift_id bigint references public.shifts(id),
  reason text,
  notes text,
  total numeric(12,2) default 0,
  client_tx_id text unique,
  created_at timestamptz not null default now()
);
create table public.return_items(
  id bigint generated by default as identity primary key,
  return_id bigint not null references public.returns(id) on delete cascade,
  order_item_id bigint not null references public.order_items(id),
  product_name text,
  quantity numeric(18,6) not null,
  unit_price numeric(12,2) default 0,
  total numeric(12,2) default 0
);
create table public.return_payments(
  id bigint generated by default as identity primary key,
  return_id bigint not null references public.returns(id) on delete cascade,
  method text,
  amount numeric(12,2)
);

create table public.suppliers(
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  address text,
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create table public.purchases(
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  supplier_id bigint references public.suppliers(id),
  invoice_number text,
  total numeric(18,6) not null default 0,
  paid numeric(18,6) not null default 0,
  notes text,
  created_at timestamptz not null default now()
);
create table public.purchase_items(
  id bigint generated by default as identity primary key,
  purchase_id bigint not null references public.purchases(id) on delete cascade,
  ingredient_id bigint not null references public.ingredients(id),
  quantity numeric(18,6) not null,
  unit_cost numeric(18,6) not null default 0,
  total numeric(18,6) not null default 0
);
create table public.stock_transfers(
  id bigint generated by default as identity primary key,
  from_branch_id bigint not null references public.branches(id),
  to_branch_id bigint not null references public.branches(id),
  status text not null default 'draft',
  notes text,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);
create table public.stock_transfer_items(
  id bigint generated by default as identity primary key,
  transfer_id bigint not null references public.stock_transfers(id) on delete cascade,
  ingredient_id bigint not null references public.ingredients(id),
  quantity numeric(18,6) not null
);

create table public.permission_actions_v2(
  code text primary key,
  name_ar text not null,
  domain text not null,
  legacy_permission text,
  active boolean not null default true,
  sort_order integer not null default 0
);

create table public.return_approval_requests(
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id),
  order_id bigint not null references public.orders(id),
  requester_employee_id bigint not null references public.employees(id),
  requester_shift_id bigint not null references public.shifts(id),
  requester_name text not null,
  order_bon_number bigint,
  order_invoice_number bigint,
  reason text not null,
  notes text,
  items jsonb not null,
  payments jsonb not null,
  expected_total numeric(12,2) not null,
  status text not null default 'pending',
  client_tx_id text not null unique,
  request_digest text not null,
  expires_at timestamptz not null,
  approver_employee_id bigint references public.employees(id),
  decision_at timestamptz,
  decision_note text,
  decision_client_tx_id text,
  decision_digest text,
  return_id bigint references public.returns(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.current_employee_id() returns bigint
language sql stable as $$select 1::bigint$$;
create or replace function public.is_admin() returns boolean
language sql stable as $$select true$$;
create or replace function public.has_permission(text) returns boolean
language sql stable as $$select true$$;
create or replace function public.has_branch_access(bigint) returns boolean
language sql stable as $$select true$$;
create or replace function public.has_action_permission_v2(text) returns boolean
language sql stable as $$select true$$;

-- Production 10.5.15 contract: base atomic sale persists exact modifier quantity.
create or replace function public.create_pos_order_atomic(
  p_order jsonb,p_items jsonb,p_payments jsonb
) returns jsonb
language plpgsql security definer set search_path=public as $$
declare
  v_order_id bigint;
  v_item jsonb;
  v_mod jsonb;
  v_item_id bigint;
  v_saved jsonb:='[]'::jsonb;
begin
  insert into public.orders(
    branch_id,employee_id,shift_id,bon_number,invoice_number,order_type,payment_method,
    subtotal,total,status,client_tx_id
  ) values(
    (p_order->>'branch_id')::bigint,
    coalesce(nullif(p_order->>'employee_id','')::bigint,1),
    nullif(p_order->>'shift_id','')::bigint,
    nullif(p_order->>'bon_number','')::bigint,
    nullif(p_order->>'invoice_number','')::bigint,
    coalesce(nullif(p_order->>'order_type',''),'takeaway'),
    coalesce(nullif(p_order->>'payment_method',''),'cash'),
    coalesce((p_order->>'subtotal')::numeric,0),
    coalesce((p_order->>'total')::numeric,0),
    coalesce(nullif(p_order->>'status',''),'completed'),
    nullif(p_order->>'client_tx_id','')
  ) returning id into v_order_id;

  for v_item in select * from jsonb_array_elements(p_items) loop
    insert into public.order_items(order_id,product_id,product_name,quantity,unit_price,cost,total,notes)
    values(
      v_order_id,nullif(v_item->>'product_id','')::bigint,coalesce(v_item->>'product_name',''),
      (v_item->>'quantity')::numeric,coalesce((v_item->>'unit_price')::numeric,0),
      coalesce((v_item->>'cost')::numeric,0),coalesce((v_item->>'total')::numeric,0),
      nullif(v_item->>'notes','')
    ) returning id into v_item_id;

    v_saved:=v_saved||jsonb_build_array(jsonb_build_object(
      'id',v_item_id,'order_id',v_order_id,'product_id',v_item->>'product_id',
      'quantity',v_item->>'quantity'
    ));

    for v_mod in select * from jsonb_array_elements(coalesce(v_item->'modifiers','[]'::jsonb)) loop
      insert into public.order_item_modifiers(order_item_id,modifier_id,modifier_name,price,quantity)
      values(
        v_item_id,nullif(v_mod->>'id','')::bigint,coalesce(v_mod->>'name',''),
        coalesce((v_mod->>'price')::numeric,0),
        greatest(1,coalesce(nullif(v_mod->>'qty','')::integer,1))
      );
    end loop;
  end loop;

  return jsonb_build_object(
    'order',jsonb_build_object('id',v_order_id,'branch_id',(p_order->>'branch_id')::bigint),
    'items',v_saved,
    'duplicate_prevented',false
  );
end;$$;

create or replace function public.create_order_return_idempotent(
  p_order_id bigint,p_reason text,p_notes text,p_items jsonb,p_payments jsonb,p_client_tx_id text
) returns bigint
language plpgsql security definer set search_path=public as $$
declare v_id bigint; v_branch bigint; v_item jsonb; v_oi public.order_items%rowtype;
begin
  select id into v_id from public.returns where client_tx_id=p_client_tx_id;
  if v_id is not null then return v_id; end if;
  select branch_id into v_branch from public.orders where id=p_order_id;
  insert into public.returns(order_id,branch_id,employee_id,shift_id,reason,notes,total,client_tx_id)
  values(p_order_id,v_branch,1,1,p_reason,p_notes,0,p_client_tx_id)
  returning id into v_id;
  for v_item in select * from jsonb_array_elements(coalesce(p_items,'[]'::jsonb)) loop
    select * into v_oi from public.order_items where id=(v_item->>'order_item_id')::bigint;
    insert into public.return_items(return_id,order_item_id,product_name,quantity,unit_price,total)
    values(v_id,v_oi.id,v_oi.product_name,(v_item->>'quantity')::numeric,v_oi.unit_price,0);
  end loop;
  return v_id;
end;$$;

create or replace function public.return_approval_validate_v1(
  p_order_id bigint,p_items jsonb,p_payments jsonb
) returns numeric
language sql stable as $$
  select coalesce(sum((x->>'amount')::numeric),0)
  from jsonb_array_elements(coalesce(p_payments,'[]'::jsonb)) x
$$;

-- Legacy Recipe Soft owners exist before the transition and must be removed by V10.5.16.
create or replace function public.fixture_legacy_sale_trigger() returns trigger
language plpgsql as $$begin return new; end$$;
create or replace function public.fixture_legacy_return_trigger() returns trigger
language plpgsql as $$begin return new; end$$;
create trigger trg_recipe_order_item_fail_open_v1
after insert on public.order_items for each row execute function public.fixture_legacy_sale_trigger();
create trigger trg_recipe_return_item_fail_open_v1
after insert on public.return_items for each row execute function public.fixture_legacy_return_trigger();

insert into public.branches(id,name) values(1,'العشرين'),(2,'الدقي');
insert into public.employees(id,name,active,role,branch_id) values(1,'Admin',true,'admin',1);
insert into public.shifts(id,branch_id,employee_id,status,opened_at) values(1,1,1,'open',now());
