'use strict';
const fs=require('fs');
const p='app.js';
let s=fs.readFileSync(p,'utf8');
if(s.includes('SHARAWLA_OFFLINE_AUTH_55_3_OFFICIAL')){console.log('55.3 official app.js flow already applied');process.exit(0)}
const anchor="$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();try{await signIn($('#email').value.trim(),$('#password').value);if(navigator.onLine)await bootstrap();else await loadOfflineBootstrap()}catch(err){session=null;toast(err.message)}});";
if(!s.includes(anchor))throw new Error('55.3 patch refused: official loginForm anchor not found');
const replacement=`// SHARAWLA_OFFLINE_AUTH_55_3_OFFICIAL — authoritative Offline Auth ownership lives in app.js.\nlet sharawlaOfflineAuthReadiness={ready:false,status:'NOT_READY',reason:'NOT_ENROLLED'};\nfunction setSharawlaOfflineAuthReadiness(ready,reason=null,extra={}){\n  sharawlaOfflineAuthReadiness={ready:ready===true,status:ready===true?'READY':'NOT_READY',reason,...extra};\n  try{window.dispatchEvent(new CustomEvent('sharawla:offline-auth-readiness',{detail:sharawlaOfflineAuthReadiness}))}catch{}\n  return sharawlaOfflineAuthReadiness;\n}\nasync function enrollOfflineAuthAfterOfficialBootstrap(email,password){\n  const a=window.topBurgerDesktop?.offlineV2;\n  if(!a?.authEnroll||!a?.authState){const e=new Error('Offline V2 authorization غير متاح');e.code='OFFLINE_V2_AUTH_API_UNAVAILABLE';throw e}\n  const bootstrap=await odbGet('bootstrap');\n  if(!bootstrap?.employee?.id){const e=new Error('Offline bootstrap غير محفوظ');e.code='OFFLINE_V2_AUTH_BOOTSTRAP_REQUIRED';throw e}\n  const license=await loadLicenseState();\n  const identity={device_id:String(license?.device_id||'').trim(),business_id:String(license?.business_id||'').trim(),device_fingerprint:String(license?.device_fingerprint||'').trim()};\n  if(!identity.device_id||!identity.business_id||!identity.device_fingerprint){const e=new Error('Canonical identity غير مكتملة');e.code='OFFLINE_V2_CANONICAL_IDENTITY_REQUIRED';throw e}\n  const enrolled=await a.authEnroll({identity,license,bootstrap,email:String(email||'').trim().toLowerCase(),password:String(password||'')});\n  if(enrolled?.enrolled!==true){const e=new Error('Offline credential persistence failed');e.code=enrolled?.code||'OFFLINE_V2_AUTH_ENROLL_FAILED';throw e}\n  const authState=await a.authState({identity});\n  if(authState?.enrolled!==true||authState?.valid!==true){const e=new Error('Offline credential read-back failed');e.code=authState?.code||'OFFLINE_V2_AUTH_NOT_READY';e.auth_state=authState;throw e}\n  setSharawlaOfflineAuthReadiness(true,null,{enrolled:true,valid:true});\n  return {ok:true,enrolled:true,valid:true};\n}\n$('#loginForm').addEventListener('submit',async e=>{\n  e.preventDefault();\n  const email=$('#email').value.trim(),password=$('#password').value;\n  try{\n    await signIn(email,password);\n    if(navigator.onLine){\n      await bootstrap();\n      try{\n        await enrollOfflineAuthAfterOfficialBootstrap(email,password);\n      }catch(authErr){\n        const reason=authErr?.code||authErr?.message||'OFFLINE_V2_AUTH_ENROLL_FAILED';\n        setSharawlaOfflineAuthReadiness(false,reason);\n        console.error('Offline NOT READY',reason,authErr);\n        try{toast('Offline NOT READY: '+reason)}catch{}\n      }\n    }else await loadOfflineBootstrap();\n  }catch(err){session=null;toast(err.message)}\n});`;
s=s.replace(anchor,replacement);
fs.writeFileSync(p,s,'utf8');
console.log('55.3 official app.js Offline Auth flow applied');